### ISSUE TITLE
Add `IO.sequence`

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#10]
Uses `par` for parallel composition.

```scala
object IO {
  def sequence[E, A, M[X] <: TraversableOnce[X]](in: M[IO[E, A]])(
    implicit cbf: CanBuildFrom[M[IO[E, A]], A, M[A]]): IO[E, M[A]]
}
```

**Comment by regiskuckaertz** [comment]
I'll pick this one and [traverse](https://github.com/scalaz/scalaz-zio/issues/11) too if nobody already has.

**Comment by regiskuckaertz** [comment]
Yes, of course, great idea 👍

**Comment by jdegoes** [comment]
We already have `RTSSpec`, so the method sshould probably be added there.

**Comment by leandrob13** [comment]
Since `IO.traverse` is already merged, are we going to implement `IO.sequence` from `IO.traverse(list)(identity)`? @regiskuckaertz are you still going to take care of this one?

**Comment by regiskuckaertz** [comment]
Yeah sorry, it's there https://github.com/scalaz/scalaz-zio/pull/39
