### ISSUE TITLE
Introduce raceAll

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#120]
Define `raceAll` in the companion object of `IO` that is capable of racing many actions of the same type.

```scala
final def raceAll[E, A, M[X] <: TraversableOnce[X]](as: M[IO[E, A]]): IO[E, A] = ???
```

This can be implemented using `race` method on `IO`.

**Comment by plokhotnyuk** [comment]
`Traversable` and `TraversableOnce` are deprecated  since Scala 2.13.0-M4: https://confadmin.trifork.com/dl/2018/GOTO_Berlin/Migrating_to_Scala_2.13.pdf&ved=2ahUKEwi8rNTQ5qbcAhVKKywKHUFEDNAQFjABegQIAhAB&usg=AOvVaw3KTAUBQ_jNhIQR2SsCVSKI

**Comment by jdegoes** [comment]
@plokhotnyuk Created #123:

https://github.com/scalaz/scalaz-zio/issues/123

**Comment by jupposessho** [comment]
Isn't it the same implementation as the current raceAll has?

`final def raceAll[E, A](t: TraversableOnce[IO[E, A]]): IO[E, A]`
