### ISSUE TITLE
Generalize supervisor

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#124]
Currently, using the `supervise` combinator will interrupt child fibers at the boundary, waiting until they have all been successfully terminated.

However, this can be generalized so that user-code can choose to join the fibers, instead of interrupting them, allowing them to complete normally:

```scala
sealed abstract class IO[E, A] {
  ..
  def supervised0(supervisor: List[Fiber[_, _]] => IO[Void, Unit]): IO[E, A] = ???
  ..
}
```

**Comment by regiskuckaertz** [comment]
I'll be on hols next week but if that hasn't been picked up when I'm back, I'm happy to help here, I've got experience now 😅 (or if there's more urgent to get zio closer to a 1.0, lmk).
