### ISSUE TITLE
Add exit handler

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#125]
With a new primitive that merely registers an adapted listener onto a fiber (`FiberContext.register`), users can register an action for when a fiber terminates, and receive information on whether the fiber terminated normally, with unhandled error, or with exception.

```scala
object IO {
  def onExit(f: ExitResult[Unit, Unit] => IO[Void, Unit]): IO[Nothing, Unit]
}
```

This primitive is enough to implement `run`, as well as enhance bracket to its former level of power (providing `ExitResult[E, B]` on the use action).

### Semantics

The specified action will be invoked after the fiber has finished running (including all finalizers). If the specified action throws an exception, it will be reported to the parent fiber's unhandled error handler, **not__ the fiber's own unhandler (since the fiber is already done running?).

### Usage

```scala
for {
  _ < IO.onExit(_ => putStrLn("This fiber is done now"))
} yield ()
```

**Comment by regiskuckaertz** [comment]
@jdegoes I'd like to help here but can't wrap my head around this one.
```scala
def register(f: ExitResult[E, A]    => Unit)              : Async[E, A]
def run                                                   : IO[Nothing, ExitResult[E, A]]
def onExit  (f: ExitResult[E, Unit] => IO[Nothing, Unit]) : IO[Nothing, Unit]
```
I can't figure out how to write `run` using `onExit`. Changing it to:
```scala
def onExit  (f: ExitResult[E, A]    => IO[Nothing, Unit]) : IO[Nothing, Unit]
```
gets me closer, but not without changing `register` to
```scala
def register(f: ExitResult[E, A]    => IO[Nothing, Unit]) : Async[E, A] =
  join0(x => unsafeRun(f(x)))
```
... once in `IO`, always in `IO` 😄 Then I can write:
```scala
def run = IO.asyncPure { cb =>
  IO.onExit { x => cb(x) }
}
```
Is that what you had in mind?

**Comment by regiskuckaertz** [comment]
☝️ there probably should be a reference to `self` somewhere 🤔

**Comment by jdegoes** [comment]
Something like this:

```scala
def run[E, A](io: IO[E, A]): IO[Nothing, ExitResult[E, A]] = 
  for {
    p <- Promise.make[E, A]
    _ <- (onExit(p.done) *> io).fork
    v <- p.get
  } yield v
```

This isn't quite right because you have to set the `E` or `A` right after the `io` (using a `Ref`?), so you need something like `IO.absolve(io.attempt.flatMap(e => setter2(e).const(e))`, and then the exit handler must only set the termination causes (not the error).

Not 100% sure that it can be done though, and my initial type signature for `onExit` was wrong. 😄

**Comment by regiskuckaertz** [comment]
Would it make sense to add it to `Fiber`?
```scala
for {
  p <- Promise.make[E, A]
  f <- io.fork
  _ <- f.onExit(p.done)
  v <- p.get
} yield v
```

**Comment by regiskuckaertz** [comment]
I set up a branch to explore that line of thought, adding a new abstract `Fiber.finished`. It’s promising except for `Fiber.zipWith` et al.

**Comment by jdegoes** [comment]
@regiskuckaertz We need to think about that, but I think if both sides fail or are terminated, then we have to invoke the callback 2 times. The callback will be invoked only a single time in the event that both left and right succeed, in which case it gets the `C`.

Also we should reconstruct `ExitResult` to avoid the type casts because this is not performance sensitive code.

**Comment by regiskuckaertz** [comment]
Did that 👍
