### ISSUE TITLE
Implement Queue.dropping, Queue.sliding

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#126]
- [ ] **Queue.dropping** — dropping new elements when full
- [ ] **Queue.sliding** — dropping old elements when full

**Comment by wi101** [comment]
@jdegoes should we add this issue in `scalaz-ioqueue` ?

**Comment by jdegoes** [comment]
@wi101 Yes, and then we can delete it here.

**Comment by jczuchnowski** [comment]
I can see `dropping` and `sliding` are already in ZIO's master. This issue can be closed.
