### ISSUE TITLE
Add `IO.reduceAll`

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#13]
Uses `par` for parallel composition.

```scala
object IO {
 def reduceAll[E, A](a: IO[E, A], as: TraversableOnce[IO[E, A]])(f: (A, A) => A): IO[E, A]
}
```

**Comment by fabianpage** [comment]
Would that be a good testcase:

```scala
    unsafePerformIO(
      IO.reduceAll[Nothing, Int](IO.point(1), List(2, 3, 4).map(IO.point(_)))(_ + _)
    ) must_=== 10
```

Why is the a seperated from the as?

**Comment by jdegoes** [comment]
To make sure there is at least one A (or an error).

**Comment by fabianpage** [comment]
Ah because i can't construct an IO[E, A] out of thin air.

I will try to implement this function
