### ISSUE TITLE
Error compiling project

### ISSUE THREAD

**Issue by Vilkina** [scalaz/scalaz-zio#130]
[error.txt](https://github.com/scalaz/scalaz-zio/files/2216306/error.txt)

**Comment by Vilkina** [comment]
Hi, thank you for reply. I need your help. Can I share screen with you and you will help me to compile a project? Step by step setup?


22 июля 2018, 05:27:20, от "Ondra Pelech" <notifications@github.com>:

this is a wild guess, but after you backup you work, try git clean -xdf
perhaps it will help you

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



--
Best regards,

Oleksandra Golubitska
Co-CEO
coyoteworks.com
aleksandrag@ukr.net
+380672242385

**Comment by jdegoes** [comment]
@Vilkina I found [this](https://github.com/scala/bug/issues/10717).

Can you say what version of Java you are running (`java -version`)?

**Comment by Vilkina** [comment]
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
mini:~ admin$

**Comment by jmcardon** [comment]
Yeah, you need to downgrade to java 8.

**Comment by jdegoes** [comment]
@Vilkina According to the ticket, your version of Java may be a problem. 😞 

I found [these instructions](https://stackoverflow.com/questions/46513639/how-to-downgrade-java-from-9-to-8-on-a-macos-eclipse-is-not-running-with-java-9) which may help to explain how to change the default version of Java.

**Comment by anilanar** [comment]
Java 8 worked.

**Comment by Vilkina** [comment]
Thanks guys! You are amazing. I though it is Scala affecting project. I've installed everything form   from scratch to a different computer and project wasn't compile. This morning I've followed instructions:
https://stackoverflow.com/questions/46513639/how-to-downgrade-java-from-9-to-8-on-a-macos-eclipse-is-not-running-with-java-9

This is how I did it. You don't need to delete Java 9.

Step 1: Install Java 8

You can download Java 8 from here: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

Step 2: After installation of Java 8. Confirm installation of all versions.Type the following command in your terminal.

/usr/libexec/java_home -V
Step 3: Edit .bash_profile

sudo nano ~/.bash_profile
Step 4: Add 1.8 as default. (Add below line to bash_profile file).

export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
Now Press CTRL+X to exit the bash. Press 'Y' to save changes.

Step 5: Reload bash_profile

source ~/.bash_profile
Step 6: Confirm current version of Java

java -version

And now it is [success].
Thanks for the help. It is really good morning.
