### ISSUE TITLE
Readme is missing simple usage section

### ISSUE THREAD

**Issue by baank** [scalaz/scalaz-zio#133]
It would be nice to have a simple "Getting Started" or "Usage" section which lists out how to integrate ZIO with your app using SBT:

Similar to:
https://github.com/scalaz/scalaz

And I assuming that since there are no releases/Maven artefacts that this isn't ready for mainstream usage yet ?  Could be useful to mention who/how we should be using it.

**Comment by jdegoes** [comment]
@baank There are releases:

https://oss.sonatype.org/content/repositories/snapshots/org/scalaz/scalaz-zio_2.12/

**Comment by barambani** [comment]
I notice ([here](https://oss.sonatype.org/content/repositories/snapshots/org/scalaz/)) that there are releases only for `2.12`. Is there any reason not to have one for `2.11` ? I see the cross build is already supported.

**Comment by jdegoes** [comment]
We should definitely do 2.11.
