### ISSUE TITLE
Scalaz Streams Project

### ISSUE THREAD

**Issue by virdis** [scalaz/scalaz-zio#139]
Hi John, I am the lead for Scalaz-Streams project and I don't have access to the repository. Also this project already exists https://github.com/scalaz/scalaz-stream. Should we come up with a new name for Scalaz8 streams project.

**Comment by ktonga** [comment]
Well, it does not have a master branch, so I'd say you can start with an empty one and leave the other branches alone for historical reasons.

**Comment by jdegoes** [comment]
@virdis Done! Accept the invite and feel free to add anyone else to the project.

I think we can do our work in a new master branch.
