### ISSUE TITLE
Demote `KleisliIO` from being a function

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#14]
Instead of being a function `A => IO[E, B]`, it should have a field called `run` which is a function `A => IO[E, B]`.

**Comment by fabianpage** [comment]
Hi

Why do you want to have KleisliIO to have a run field insted of being a function?

I tried to do that but have the feeling it's to simple and i have probably done something wrong. ;) (Just added a val run to KleisliIO, removed the extends and made all test work again)

**Comment by ktonga** [comment]
@fabianpage more info in this thread https://github.com/scalaz/scalaz/pull/1857#discussion_r193571323
