### ISSUE TITLE
WIP: Abstract out notion of clock from timer-related methods

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#140]
- [x] Introduce `Clock` class with methods for getting the current time, nano time, and sleeping
 - [x] Create production implementation (`Live`).
 - [ ] Create test implementation (`Test`).
 - [ ] Make retry / repeat methods and Schedule methods take a Clock w/default to `Live`.
 - [ ] Add tests as appropriate
 - [ ] Document any changes in interface

```scala
import java.util.concurrent.TimeUnit
import scala.concurrent.duration.Duration
import scala.concurrent.duration._

trait Clock {
  def currentTime(unit: TimeUnit): IO[Nothing, Long]
  def nanoTime: IO[Nothing, Long]
  def sleep(length: Long, unit: TimeUnit): IO[Nothing, Unit]
}
object Clock {
  object Live extends Clock { ... }
  case class Test(startTime: Long, sleeps: List[Duration]) extends Clock { ... }
}
```

**Comment by barambani** [comment]
I'll have a look at this

**Comment by barambani** [comment]
If still needs to be discussed a bit more I'm happy to wait, I will do some research in the meantime. I don't want to rush. Thanks

**Comment by Vilkina** [comment]
@barambani can I work with you on this issue?

**Comment by barambani** [comment]
@Vilkina sure thing 👍 😃. Also my info collecting activity for this has slowed down a lot due to travelling ad work so feel free. Thanks

**Comment by jdegoes** [comment]
I have additional ideas on how this can be done. I'll discuss shortly.

**Comment by Vilkina** [comment]
Here is a some code of Clock.scala file

import java.util.concurrent.TimeUnit
import scala.concurrent.duration.Duration
import scala.concurrent.duration._


trait Clock[F[_]] {
  def now(unit: TimeUnit): F[Long]
  def sleep(length: Long, unit: TimeUnit): F[Unit]
}
object Clock {
  def apply[F[_]](implicit F: Clock[F]): Clock[F] = F

  implicit val ClockIO: Clock[IO[Nothing, ?]] = new Clock[IO[Nothing, ?]] {
    def now(unit: TimeUnit): IO[Nothing, Long] = IO.sync(unit.convert(System.nanoTime(), NANOSECONDS))
    def sleep(length: Long, unit: TimeUnit): IO[Nothing, Unit] = ???
  }
}

Is there any mistakes in this file(except implicit val ClockIO)?
I'm going to implement sleep method and will do commit after.
Also, I want to change package.scala file, but I'm not sure that my implementation is correct.

**Comment by edmundnoble** [comment]
Please don't make `Clock` a type class, it's just a value. *Just pass it explicitly.* Users can deal with this; if they can't they can go back to using `Future` with implicit `ExecutionContext`.

**Comment by Vilkina** [comment]
@edmundnoble I can see the Future but it is too bright :)

**Comment by jdegoes** [comment]
@edmundnoble I was thinking about this the whole week. I agree. It should be an ordinary value.

**Comment by jdegoes** [comment]
@Vilkina The main change is that we will remove the implicit from `val ClockIO`, and also delete the `Clock.apply` method.

Also, correct me if I'm wrong @edmundnoble, but we should monomorphize to `IO`, letting us simplify to:

```scala
import java.util.concurrent.TimeUnit
import scala.concurrent.duration.Duration
import scala.concurrent.duration._

trait Clock {
  def currentTime(unit: TimeUnit): IO[Nothing, Long]
  def nanoTime: IO[Nothing, Long]
  def sleep(length: Long, unit: TimeUnit): IO[Nothing, Unit]
}
object Clock {
  object Live extends Clock { ... }
  case class Test(startTime: Long, sleeps: List[Duration]) extends Clock { ... }
}
```

**Comment by Vilkina** [comment]
`import java.util.concurrent.TimeUnit
import scala.concurrent.duration.Duration
import scala.concurrent.duration._



trait Clock {
  def currentTime(unit: TimeUnit): IO[Nothing, Long]
  def nanoTime: IO[Nothing, Long]
  def sleep(length: Long, unit: TimeUnit): IO[Nothing, Unit]
}

object Clock {

  object Live extends Clock {
    def currentTime(unit: TimeUnit): IO[Nothing, Long] = IO.sync(unit.convert(System.nanoTime(), NANOSECONDS))

    def nanoTime: IO[Nothing, Long] = IO.sync(System.nanoTime())

    def sleep(length: Long, unit: TimeUnit): IO[Nothing, Unit] = IO.sleep(FiniteDuration(length, unit))
  }

  case class Test(startTime: Long, sleeps: List[Duration]) extends Clock {
    def startTime: Long = ???

    def sleeps: List[Duration] = ???
  }

}`

**Comment by Vilkina** [comment]
https://github.com/Vilkina/scalaz-zio/commit/ddcd124ddb5b26be24d9c52d20574c2cda97f37f

**Comment by Vilkina** [comment]
I’m ready to do next PR. But I have previous PR opened.
