### ISSUE TITLE
Move Future into seperate Interop

### ISSUE THREAD

**Issue by baank** [scalaz/scalaz-zio#144]
Feel free to close this if it doesn't make sense.

But some (maybe many) of us are looking at IO as what Future should have always been. Unfortunately some existing libraries e.g HTTP Clients have Future return types and so it makes sense to include the interop module. Including the interop library I assume brings alongs all the scalaz/cats/etc dependencies as well. 

Might be worth treating Future as a seperate case ?

**Comment by ktonga** [comment]
Both dependencies are optional and won't be pulled by interop if the user's project doesn't yet depend on them

https://github.com/scalaz/scalaz-zio/blob/1af623cce75d20fc09feace67295c69b781ec8e3/build.sbt#L80-L81
