### ISSUE TITLE
Implement auto-deployment

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#145]
Every time there is a successful Travis build in master, we should increment the `RC` version number, commit the change, and trigger and publish a build (e.g. `0.1.0-RC1`, `0.1.0-RC2`, `0.1.0-RC3`, ..., `0.1.0.RC999999`). The idea is to give people stable releases for "in-between" versions.

@NeQuissimus Would be great to get any insight you have into doing this.

**Comment by ktonga** [comment]
Increasing the micro is meaningless. I'd like append commit sha better.

**Comment by NeQuissimus** [comment]
Appending the SHA is what we did with Scalaz 8.
Personally, I generally use `-SNAPSHOT` and cut frequent tags rather than have the CI do these things.

**Comment by prayagupd** [comment]
Hi @jdegoes and @NeQuissimus this is something i can pick up and contribute as "good first issue", if we decided to
- update the RC version number, which I understand as update the `build.sbt` and create a tag

```bash
ci_build_number=1 #provided by the CI

# or we can increment whatever it was previously
ci_build_number="$(echo 'version in ThisBuild := "0.1-RC2"' | cut -d'=' -f 2 | cut -d"-" -f 2 | cut -c 3- | rev | cut -c 2- | rev)"
ci_build_number = "$((ci_build_number + 1))"

current_version="0.1.0-RC${ci_build_number}"

sed -i '.bak' 's/^version in ThisBuild .*$/version in ThisBuild := "${current_version}"/' build.sbt
git tag ${current_version}
git commit build.sbt -m "update RC version number to ${current_version}"
git push origin ${current_version}
```

- publish the artifact

```bash
sbt publish
```

**Comment by NeQuissimus** [comment]
@prayagupd I would really hate for the CI to commit changes...
Also, I am pretty sure there are sbt plugins for that logical you have.

**Comment by prayagupd** [comment]
thank you @NeQuissimus for the feedback. The updated `build.sbt` is not really necessary to be committed (commit is in tag not master) in my example, but important thing is to tag the current set of features in the build and push it.

I have seen https://github.com/sbt/sbt-release which i will look into it and see if it can increment the version number.

**Also, do you prefer to use the "CI build number" to be part of release or the "previous release version"?**
Using CI build number is easy but if the build fails we won't have a release for that build which means we have gap in release numbers.

**Comment by jdegoes** [comment]
@prayagupd Let's definitely try to use the sbt-releases plugin. 

There are two workflows to support:

1. Auto-building release candidates for the "next version".
2. Building releases for the "next version" and then incrementing to the "next, next version".

The process should handle both of them. 

> Using CI build number is easy but if the build fails we won't have a release for that build which means we have gap in release numbers.

I'd prefer not to have gaps in the release numbers.

**Comment by ktonga** [comment]
I think with the public API still being subject to changes we should be producing milestones instead. Eg: `...-M1`, `...-M2`

**Comment by ktonga** [comment]
I think:

- The version should never be updated by the build
- On merge to master we publish to sonatype
- We don't use snapshot anymore coz they're evil
- We append commit SHA to the version so we give to peeps something immutable to depend on
- When we think it's time to publish something more visible (Milestone, RC or Release) we do it manually since it should be published to Maven central

**Comment by jdegoes** [comment]
So we auto-publish the SHA builds (`0.1.0-7f27e9c`), and then manually build the release numbers? That seems sensible.

**Comment by prayagupd** [comment]
Hi @ktonga and @jdegoes created a PR to publish an artifact of versioning `0.1.0-$commitSha` - https://github.com/scalaz/scalaz-zio/pull/151/files

I might have to to update [travis.yaml](https://github.com/scalaz/scalaz-zio/blob/master/.travis.yml), as I see it is using `sbt publish`, instead we need `sbt "release with-defaults"`.

If we want to publish manually we can use sbt-release as

```bash
sbt "release release-version 0.1.0 next-version 0.1.1 with-defaults"
```
