### ISSUE TITLE
Sleep can't handle infinite durations

### ISSUE THREAD

**Issue by JD557** [scalaz/scalaz-zio#148]
Right now, running `IO.sleep(Duration.Inf)` blows up with `java.lang.IllegalArgumentException: toNanos not allowed on infinite Durations`.

This method can either be changed to only accept `FiniteDurations` or such that `IO.sleep(Duration.Inf)` behaves like `IO.never`.

**Comment by jdegoes** [comment]
@JD557 

Let's make infinite durations behave like `IO.never`.

**Comment by jczuchnowski** [comment]
Did some quick digging. There are three values of `sealed abstract class Infinite`: `Duration.Inf`, 'Duration.MinusInf` and `Duration.Undefined` - all of which will result in `java.lang.IllegalArgumentException: toNanos not allowed on infinite Durations`. 

I guess a simple match for `Duration.Infinite` should do the trick. I'd be happy to take it as my **good first issue**.

**Comment by ktonga** [comment]
In this case I think the safest option is to match on `FiniteDuration` to get the nanos, and make everything else behave like `IO.never`

**Comment by jczuchnowski** [comment]
Also there's a similar problem with `def repeatFixed` - it calls `toNanos` on any `Duration` passed. Only this one is on IO.scala level while the `IO.sleep` is in RTS.scala.

**Comment by jdegoes** [comment]
@jczuchnowski We should look for and eliminate all of these. In fact, maybe we should just wrap `Long` and `TimeUnit` in our own `Duration` which does not provide any unsafe functions? Otherwise I feel like the `toNanos` problem will be repeated, maybe again in ZIO, and definitely in user-land code.

**Comment by sideeffffect** [comment]
But `FiniteDuration` is *safe*, right? If so, shouldn't we just change every method to accept `FiniteDuration` instead of `Duration`?

**Comment by jczuchnowski** [comment]
@jdegoes wouldn't that be the same as if we used `FiniteDuration` instead of `Duration`? `FiniteDuration` is `final` so it would be safe to use in our context.
Unless our own `Duration` would include also `infinite` values, but that again forces us to handle these cases internally.

**Comment by sideeffffect** [comment]
I would consider something like

```
Finite (and that of course includes 0) => business as usual
+Inf => like IO.never
Anything else, like -Inf, Undefined or whatever else => just blatantly throw exception
```

or rolling our own fancy Duration as @jdegoes suggested

```scala
object zio {

  sealed trait Duration {
    def toDuration: scala.concurrent.duration.Duration
  }

  object Duration {

    case class Finite(duration: FiniteDuration) extends Duration {
      final def toDuration = duration
    }

    case class Infinite() extends Duration {
      final def toDuration = scala.concurrent.duration.Duration.Inf
    }

    def fromDuration(duration: scala.concurrent.duration.Duration): Either[IllegalArgumentException, Duration] = duration match {
      case finiteDuration: FiniteDuration => Right(Finite(finiteDuration))
      case inf if inf == scala.concurrent.duration.Duration.Inf => Right(Infinite())
      case x => Left(new IllegalArgumentException(s"Woah dude, $x is not a meaningful zio.Duration!"))
    }
  }
}
```
Having infinite duration seems like a legitimate use case. That is why I didn't add any `+` or `*` (etc) methods on `zio.Duration`, because adding or multiplying values where some may be infinite just doesn't make sense to me -- more like space for bugs to hide.

what would you guys prefer?

**Comment by jdegoes** [comment]
I prefer rolling our own `Duration` with `Finite` and `Infinite`, and forcing code to handle both possibilities, i.e. you cannot call `toNanos` until you know you have a `FiniteDuration`.

**Comment by jczuchnowski** [comment]
So I took the implementation @sideeffffect proposed and tried to apply it as is. There are couple of problems there, but the PR #152 highlights the patterns of current usage of `Duration`. I suggest we move the discussion there?

**Comment by JD557** [comment]
I haven't tested #152, but I guess this issue can be closed now.
