### ISSUE TITLE
`Fiber.interrupt` sometimes returns before fiber is actually interrupted 

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#15]
By spec, `Fiber.interrupt` should not return until the fiber is interrupted and all finalizers have been successfully run. Yet this test and at least one other in `IOQueueSpec` demonstrate that `interrupt` is returning prematurely. This may be as simple as a `@volatile` bug somewhere or something more complex. It may be related to #7.

```scala
 def e9 = unsafePerformIO(
    for {
      queue <- IOQueue.make[Void, Int](100)
      f     <- queue.take[Void].fork
      _     <- f.interrupt(new Exception("interrupt fiber in e9"))
      _     <- waitForSize(queue, 0)
      size  <- queue.size[Void]
    } yield size must_=== 0
  )
```

**Comment by ktonga** [comment]
Close in favor of #16

**Comment by jdegoes** [comment]
I know @wi101 fixed this bug, I don't think there's any outstanding issues left with interruption.
