### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by NeQuissimus** [scalaz/scalaz-zio#150]
I would like to change the logo to something like this, using the font [Fabulous Steampunk](http://www.fontspace.com/marta-van-eck-designs/fabulous-steampunk).

![ZIO](http://www.fontspace.com/preview/m/6f2ecc8b1335a52d34a325ff7901bd8a.png)

The license says "Licensed as: Freeware, commercial use requires donation". Which one of the two would we fall under? :)

**Comment by ktonga** [comment]
I like the old logo better :stuck_out_tongue_closed_eyes: 

![image](https://user-images.githubusercontent.com/1324947/43495153-d4cf6f20-9579-11e8-8732-078df581ab44.png)

**Comment by jdegoes** [comment]
I know that @wi101 created a nice one, it looked like splash paint font or something. I don't know if she did high-resolution / vector version or just the mock I saw.

We should do a proper logo.

**Comment by wi101** [comment]
@jdegoes Actually I didn't do a high-resolution.. but what do you think about it?

<img width="210" alt="zio" src="https://user-images.githubusercontent.com/3535357/43529703-274e2f48-95ac-11e8-8a17-ef529d19645e.png">

**Comment by NeQuissimus** [comment]
@ktonga lol, does this work better: https://imgur.com/a/zrVm5jF
I just find the current logo a bit "plain" :) I thought that it could represent the "essential plumbing", that's why I grabbed a steampunky font.

**Comment by richardbmx** [comment]
@NeQuissimus  Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project

**Comment by NeQuissimus** [comment]
@richardbmx Give it a shot :)

**Comment by richardbmx** [comment]
perfect I'm going to work on it

**Comment by richardbmx** [comment]
@NeQuissimus  Here I present my proposal based on the original logo but with an improved version more personal and with different versions, it can be used as a favicon and in a vertical and horizontal version. with an icon that represents the letter Z with cuts that express and provide an optical illusion, which makes the icon a personalized Z for your project. If you want some change you can ask for it without problems... I hope you like it


![logo95](https://user-images.githubusercontent.com/35604837/43556054-c9c096ca-95cb-11e8-9432-9d372d45e6fb.png)

**Comment by jdegoes** [comment]
@wi101 I really like it, though I think the 'z' should be the same size as the other letters.

@NeQuissimus I do like steampunk. 😄 

@richardbmx Thank you for mocking these up. They look very professional. My own personal taste is for something a little more adventurous and spicy. By the way I saw you donated logos to other open source projects. Thank you for your extremely generous contributions to FLOSS!

**Comment by richardbmx** [comment]
@NeQuissimus  I present a folder with all the necessary files to manipulate the logo, I deliver the logo in two versions, one vertical and one additional horizontal, that I deliver an icon version to be used where they want, all the archos are 100% editable and in vector format.

If they want to change something, they inform me. regards ;-)

All File
[Google drive](https://drive.google.com/open?id=1NOo-hvyotDtOxkBaNvzJobLY7NLINjY-)

**Comment by NeQuissimus** [comment]
I am going to leave it to the group to voice opinions. I just came up with the steampunky theme on a whim since I thought it would be fitting.

**Comment by hepin1989** [comment]
![image](https://user-images.githubusercontent.com/501740/49425099-96830b80-f7d7-11e8-8472-324fa1a925b1.png)

**Comment by jdegoes** [comment]
@hepin1989 This is very much along the lines of something coming soon... stay tuned! 😉

**Comment by jdegoes** [comment]
![zio-full-color-rgb](https://user-images.githubusercontent.com/156745/49623570-6f6d3b00-f98b-11e8-8aec-6c4eb5fc4121.png)

**Comment by hepin1989** [comment]
Really like it, both are speedy, mine is running, the new one is soaring,much better,very nice.

**Comment by regiskuckaertz** [comment]
😍
