### ISSUE TITLE
Add sonatype version badge to README

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#155]
To prevent the version numbers from becoming out of date, we should use a Sonatype version badge in the README to represent version numbers (and a Maven Central one once #50 is done).

**Comment by ktonga** [comment]
I think it would be better to use placeholders together with a note to pick the latest version and add a Sonatype badge to the README, and a Maven Central one once #50 is done.

**Comment by jdegoes** [comment]
When we have a microsite this will be easy, because when we build the HTML we can insert the version tags in doc pages.

**Comment by ktonga** [comment]
I agree with that, but the issue title is a bit misleading, it might suggest to update the READMEs which are versioned, a commit per deploy would be too much noise.

**Comment by sideeffffect** [comment]
[![Sonatype Nexus (Snapshots)](https://img.shields.io/nexus/s/https/oss.sonatype.org/org.scalaz/scalaz-zio_2.12.svg)](https://oss.sonatype.org/content/repositories/snapshots/org/scalaz/scalaz-zio_2.12/)

```
[![Sonatype Nexus (Snapshots)](https://img.shields.io/nexus/s/https/oss.sonatype.org/org.scalaz/scalaz-zio_2.12.svg)](https://oss.sonatype.org/content/repositories/snapshots/org/scalaz/scalaz-zio_2.12/)
```

?
