### ISSUE TITLE
Invariance of ordering under sequence / traverse

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#157]
We need tests for `IO.traverse`, `IO.parTraverse` (as well as `sequence`, `parSequence`) to ensure the order of results is correct (and matches the input order), and if not, flip the order of parameters to `zip` / `seq`.

**Comment by AL333Z** [comment]
I'm gonna submit a PR for this one soon.

My assumptions are:
- for `IO.traverse` and `IO.sequence` both the evaluation and the results should be in order
- for `IO.parTraverse` and `IO.parSequence` only the results should be in order

I'll add an alias `IO.seq` for `IO.zipWith` as well.

**Comment by ktonga** [comment]
I would make the change for all of them, but only assert order on the effects for the sequential ones.
We already did the renaming in the "composable retry" PR, so I would suggest to avoid the alias by now.

**Comment by AL333Z** [comment]
That's great!
If your PR will come sooner that mine, I'll rebase afterwards.

**Comment by jdegoes** [comment]
@AL333Z Yes, that's the correct set of assumption.
