### ISSUE TITLE
Rename `toUnit` => `void`

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#160]
Now that we have replaced `Void` by `Nothing`, it makes sense to rename the methods currently named `toUnit` as `void`, which is their more idiomatic name in Haskell, PureScript, etc.

**Comment by jdegoes** [comment]
@saucam In the pull request or a commit message, next time use "Fixes #162", and then Github will automatically close the ticket when the pull request is merged. 😄

**Comment by regiskuckaertz** [comment]
> use "Fixes #162", and then Github will automatically close the ticket

😮 I didn't know that

**Comment by ktonga** [comment]
I like fixes for bugs, closes for features.
