### ISSUE TITLE
microsite dependency example not working?

### ISSUE THREAD

**Issue by MarkRBM** [scalaz/scalaz-zio#168]
should this be working

`libraryDependencies += "org.scalaz" %% "scalaz-zio" % "0.1.0-02a5ac6"`

It wont resolve for me I tried adding all the various sonotype resolvers snapshots/releases/public to no avail and I dont see it here https://oss.sonatype.org/#nexus-search;quick~scalaz-zio

0.1.0-SNAPSHOT works when I have the right resolver added

**Comment by NeQuissimus** [comment]
hmmm, no... That's a commit sha that was only valid for my fork...

**Comment by NeQuissimus** [comment]
https://travis-ci.org/scalaz/scalaz-zio/jobs/414191482#L1175

I updated the microsite

**Comment by Ir1sh** [comment]
thanks but I dont think the new one is valid either "0.1.0-d315153"

**Comment by prayagupd** [comment]
I am wondering the same - https://github.com/scalaz/scalaz-zio/pull/161#issuecomment-411967813

Though build says `0.1.0-d315153` artifacts are published, they are not available.

**Comment by NeQuissimus** [comment]
ooooooooooooohhhhhhhhhhhhhhhhhhh!
They are all sitting in my staging buckets! The build stages the artifacts but does not release them.

**Comment by NeQuissimus** [comment]
#172

**Comment by kamilkloch** [comment]
It looks like microsite auto-publishing is not working. Getting started section is broken. ZIO newcomers quit right there.

**Comment by prayagupd** [comment]
@kamilkloch neither of snapshot(https://oss.sonatype.org/content/repositories/snapshots/org/scalaz/scalaz-zio_2.12/) or staging(https://oss.sonatype.org/content/repositories/staging/org/scalaz/scalaz-zio_2.12/) have the version mentioned in microsite `"79527a84-SNAPSHOT"`. Also, commit SHA `79527a84` does not exist. Weird that `79527a84-SNAPSHOT` does not have major version attached either.

At least the snapshot publish for last commit seems to be 

```scala
libraryDependencies +=  "org.scalaz" %% "scalaz-zio" % "0.2.1+2-ea655328-SNAPSHOT"

resolvers += "sonatype releases" at "https://oss.sonatype.org/content/repositories/staging"
```

**Comment by kamilkloch** [comment]
@prayagupd Yes, I figured it myself, thanks. Still, microsite is listing a non-existent version and lacks the resolver for sonatype snapshots. See https://github.com/scalaz/scalaz-zio/pull/226.

**Comment by NeQuissimus** [comment]
This should no longer be an issue. Please reopen if it is.
