### ISSUE TITLE
Implement sandboxed method on IO class

### ISSUE THREAD

**Issue by pshirshov** [scalaz/scalaz-zio#171]
What would you say about adding 3-way `redeem` which would allow to recover from `Terminated` state?
 
This can be easily implemented by forking with `run` and matching on `ExitResult`. At the same time it may give user a peace of mind in situations where he isn't sure if his code wouldn't terminate and wishes to recover from bad states as cheap as he can in case of using `redeem` for error recovery.

In case you like the idea I would open a P/R. 

You may find an example here: https://github.com/pshirshov/triadic-result-model/blob/master/src/main/scala/MyApp.scala#L30

**Comment by kaishh** [comment]
Hi, we've decided to put ZIO in production as our main monad, but would like a bit more flexibility in API without keeping a lot of custom extension methods...

**Comment by jdegoes** [comment]
How about a design like this:

```scala
trait IO[E, A] {
  ...
  def sandboxed: IO[List[Throwable] \/ E, A] = ???
}
```

Then you do `io.sandboxed.redeem(...)`.

**Comment by pshirshov** [comment]
I think we should try it first but this looks nice.

**Comment by jmcardon** [comment]
Sorry if I'm a tad late to this, but doesn't this sort of subvert the entire point of `zio`?

(For the record @jdegoes I've not left scala just yet and will stick around for a tad longer :). Just backed up on things to do)

being completely serious, this is what `syncThrowable` is for. When we've chatted about this over and over about separating programmer error from benign errors in the scalaz channel, gitter and in person with otehr scalaz contributors, `syncThrowable` yielded this exact principle.

Why are we cushioning this now all of the sudden? This seems wrong

**Comment by kaishh** [comment]
@jmcardon

> but doesn't this sort of subvert the entire point of zio?

No, it's trivially done with `.run` today.

> being completely serious, this is what syncThrowable is for.

`syncThrowable` does not address the case when exception is nested deeply inside IO expression:

`def x: IO[E, Unit] = for { y <- IO.void; z = ??? } yield ()`
