### ISSUE TITLE
commit hash releases badly broken

### ISSUE THREAD

**Issue by NeQuissimus** [scalaz/scalaz-zio#172]
Those non-SNAPSHOT commit hash versions are considered "stable" by Sonatype, not snapshots.

Hence, these artifacts need to go through the correct release procedure.
Here is the workflow with the steps we are already doing checked off:

- [ ] Create POM with license, website, developer list
- [X] Generate artifacts
- [ ] Sign artifacts
- [X] Publish artifacts
- [ ] Release staging repository

Need to add this to the top of the `build.sbt`:

```
import xerial.sbt.Sonatype._

licenses in ThisBuild := Seq("APL2" -> url("http://www.apache.org/licenses/LICENSE-2.0.txt"))
homepage in ThisBuild := Some(url("https://scalaz.github.io/scalaz-zio/"))
developers in ThisBuild := List(
  Developer(id = "jdegoes", name = "John De Goes", url = url("http://degoes.net"), email = "john@degoes.net")
)
publishMavenStyle := true
```

The `.travis.yml` should invoke `publishSigned` and `sonatypeRelease` instead of `publish`.

A GPG signing key will be required, the password to the key should please be sent to me.

This may be very useful reading: https://alexn.org/blog/2017/08/16/automatic-releases-sbt-travis.html

**Comment by pshirshov** [comment]
By the way, you may use any key you wish, sonatype just requires the key to be published.

You may find a short doc here: https://github.com/pshirshov/izumi-r2/blob/develop/doc/md/flow.md#secrets

**Comment by pshirshov** [comment]
I've updated the P/R, pls check

**Comment by pshirshov** [comment]
One more P/R, #176 

What is left: 

- [ ] provide pgp keys and a `local.sbt` file through travis. 

An example of `local.sbt`:

```
pgpPassphrase := Some("XXXXX".toCharArray)
pgpSecretRing := file(".secrets/gnupg/secring.gpg")
pgpPublicRing := file(".secrets/gnupg/pubring.gpg")
```

**Comment by pshirshov** [comment]
So, I've extended my patch with couple more settings and successfully published zio to central under my own identifier. Will update P/R soon.

```
➜  scalaz-zio git:(feature/sonatype-publishing) ✗ export SONATYPE_USERNAME=pshirshov@gmail.com
➜  scalaz-zio git:(feature/sonatype-publishing) ✗ export SONATYPE_PASSWORD=XXXXX
➜  scalaz-zio git:(feature/sonatype-publishing) ✗ export PGP_SECRING=/Users/liyon/work/izumi-r2/.secrets/gnupg/secring.gpg
➜  scalaz-zio git:(feature/sonatype-publishing) ✗ export PGP_PUBRING=/Users/liyon/work/izumi-r2/.secrets/gnupg/pubring.gpg
➜  scalaz-zio git:(feature/sonatype-publishing) ✗ export PGP_PASSPHRASE=XXXX
➜  scalaz-zio git:(feature/sonatype-publishing) ✗ sbt clean publishSinged
```

**Comment by pshirshov** [comment]
So, I've published current master tip as-is under my own prefix. Whose who are eager to use release artifact may depend on

```
libraryDependencies += "com.github.pshirshov.izumi.r2" %% "scalaz-zio" % "0.1.0"
```
