### ISSUE TITLE
Don't catch `StackoverflowError` and `UnknownError`

### ISSUE THREAD

**Issue by jmcardon** [scalaz/scalaz-zio#173]
https://github.com/scalaz/scalaz-zio/blob/master/core/jvm/src/main/scala/scalaz/zio/RTS.scala#L110

It doesn't make sense to specify to those two cases. `!isInstanceOf[VirtualMachineError]` makes more sense.

**Comment by pshirshov** [comment]
Guys, please allow the user to redefine `nonFatal`. Sometimes it may be _very_ important to be able to customize default behavior.

**Comment by jmcardon** [comment]
What? In what situation is it appropriate to catch any version of `VirtualMachineError`?

Such errors may leave your VM in an undefined state. How on earth is this desirable behavior to customize?

**Comment by pshirshov** [comment]
Once in my life I've been catching `OutOfMemoryError`s calling some native cleanup code through JNI for example.

In other situation I had to deal with a stupid library. The author has been throwing `UnknownError` and it was real pain in my ass bcs of this infamous method which is used everywhere:

```
   def apply(t: Throwable): Boolean = t match {
     // VirtualMachineError includes OutOfMemoryError and other fatal errors
     case _: VirtualMachineError | _: ThreadDeath | _: InterruptedException | _: LinkageError | _: ControlThrowable => false
     case _ => true
   }
```
