### ISSUE TITLE
IO.forkAll should return a composite fiber

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#18]
Right now we have:

```scala
def forkAll[E, A](ios: List[IO[E, Unit]]): IO[E, Unit]
```

Instead we should have:

```scala
def forkAll[E, E2, A](as: List[IO[E, A]]): IO[E2, Fiber[E, List[A]]]
```

**Comment by DennisVDB** [comment]
I'll work on this one. 
However, I only see a `def forkAll[E2](l: List[IO[E2, Unit]]): IO[E2, Unit]` or did I miss it?

**Comment by jdegoes** [comment]
@DennisVDB That's the right one. It needs to be replaced.

**Comment by jdegoes** [comment]
*Hint: `Fiber.zipWith` can be used to solve this problem*
