### ISSUE TITLE
Allow the user to redefine `nonFatal` classes 

### ISSUE THREAD

**Issue by pshirshov** [scalaz/scalaz-zio#182]
1. In some cases we may want to consider some exceptions as critical and let the code crash
2. In some cases we have to integrate with badly written libraries which are using fatal exceptions to signal about their issues. In my case it was `UnknownError`
3. In some rare cases we may want to handle VM errors. In my case I've been handling OOMs to trigger a chunk of native code through JNI.

Related: #173 

@jmcardon please look.

**Comment by jdegoes** [comment]
@pshirshov I am tempted to delete `NonFatal` entirely and catch all errors. Would that be equivalent or do you prefer a custom `NonFatal` handler?

**Comment by jmcardon** [comment]
But _why_? There's literally [syncthrowable](https://github.com/scalaz/scalaz-zio/blob/master/core/shared/src/main/scala/scalaz/zio/IO.scala#L759) for this!

**Comment by pshirshov** [comment]
Depends on your situation. I agree on the argument about improper usage and don't agree on the argument about broken state where you need to try to do something (pass execution to native code) but the vm can't continue to work.

**Comment by kaishh** [comment]
@jmcardon

The point is being able e.g. immediately kill the VM with `System.exit()` on OutOfMemory exception to prevent additional allocations on shutdown and potential total freeze.

I can't describe how completely unrelated `syncThrowable` is for this case.

**Comment by jdegoes** [comment]
@jmcardon A simple argument for having this customizable (or deleting it entirely) is that no two libraries agree on the set of `NonFatal` throwables.

My own personal preference is to catch everything because all the other libraries are broken anyway (for example, performing heap allocation on fatal exceptions!!!), and in general everything about the runtime is undefined after a truly fatal exception, so who cares whether you catch or not (in some cases you may make enough progress to log something useful or shutdown somewhat more cleanly).

**Comment by pshirshov** [comment]
My P/R doesn't make things worse but makes them better - behavior is exactly the same as it is right now but you may alter it. So I don't know what may be an objection for this :(

**Comment by jdegoes** [comment]
@pshirshov I'm inclined to agree about your PR since it just moves `nonFatal` to `RTS` which is perhaps a better place for it anyway. We need the build to pass though. 😄

**Comment by pshirshov** [comment]
Build failed bcs of microsite generator I guess. Ok, I will rebase.

**Comment by pshirshov** [comment]
@jdegoes , @NeQuissimus : at the moment the build is broken by a line from my other P/R:

```
The command "if [[ "$TRAVIS_PULL_REQUEST" = "false" ]] ; then sbt ++$TRAVIS_SCALA_VERSION sonatypeRelease ; fi" exited with 1.
```

Someone need to drop all the old unclosed staging repositories from sonatype.

**Comment by NeQuissimus** [comment]
I can drop the staging artifacts when I am home. Can you send a PR with the key stuff?
