### ISSUE TITLE
retryFor isn't flexible enough to be convenient

### ISSUE THREAD

**Issue by pshirshov** [scalaz/scalaz-zio#193]
Let's consider the following snippet:

```
    def dispatch(): ZIO[Throwable, String] = {
      val id = "xxx"
      val timeout: FiniteDuration = 2.seconds
      
      val onTimeout = new RuntimeException() // TODO: ZIO interface isn't nice
      val responses = new ConcurrentHashMap[String, String]

      IO.sync {
        id
      }
        .flatMap {
          id =>
            Option(responses.get(id)) match {
              case None =>
                IO.fail(onTimeout)
              case Some(value) =>
                IO.point(Some(value))
            }
        }
        .retryFor[Option[String]](None)(id => id)(timeout)
        .flatMap {
          case Some(value) =>
            logger.debug(s"Have response: $value")
            IO.point(value)

          case None =>
            IO.terminate(new TimeoutException(s"No response for $id in $timeout"))
        }
    }
```

So, here I'm doing a simple thing - I'm attempting to read from an external mutable state until I get a value or timeout occurs. Though I had to do that dirty trick with `onTimeout` because `.retryFor` does not allow me to modify "left" branch.

I guess we should implement another kind of `retryFor` which would allow us to consider last failure value returned from our action. Though it may be kinda tricky to implement because atm `retryFor` just `race`s timeout actin with the primary action, so there is no way to get the latest value.

**Comment by ktonga** [comment]
We are reworking the retry combinators on #141 and when it's done you can complain about anything except about lack of flexibility :laughing:

**Comment by pshirshov** [comment]
Would it be possible to consider last action error while handling timeout and change left branch type? Would be perfect if so.

**Comment by jdegoes** [comment]
@pshirshov Good spot! Looking at your motivating use case, I was able to generalize the retry method on `IO` under the new composable retry policy framework.

Now you get something like this (simplified):

```scala
trait IO[E, A] {
  def retryOrElse[S, E2](policy: Retry[E, S], orElse: (E, S) => IO[E, A]): IO[E2, A] = ???
}
```

You also a more powerful variant (`retryOrElse0`), but I don't think you need that power here.

These methods allow you to look at the last error, and decide to change the error type.

Is this sufficient?

**Comment by pshirshov** [comment]
Yeah, that should be enough. Thank you!

**Comment by pshirshov** [comment]
So, now it looks like 

```
  def poll(id: RpcPacketId, interval: FiniteDuration, timeout: FiniteDuration): IO[Nothing, Option[RawResponse]] = {
    IO.sleep(interval)
      .flatMap {
        _ =>
          checkResponse(id) match {
            case None =>
              IO.fail(None)
            case Some(value) =>
              IO.point(Some(value))
          }
      }
      .retryOrElse(Retry.duration(timeout), {
        (_: Any, _: Any) =>
          IO.point(None)
      })
  }
```

Which is lot better.

**Comment by jdegoes** [comment]
This is the best I could do:

```scala
(IO.sleep(interval) *> 
  IO.sync(checkResponse(id)).flatMap { case None => IO.fail(()); case x => IO.now(x) })
  .retryOrElse(Schedule.duration(timeout), (_, _) => IO.point(None))
```

The main problem is that it's just awkward to convert from `Option[A]` => `IO[Unit, A]`. Probably we could add, `IO.fromOption` to do that. We already have `fromEither`.

Then it could be:

```scala
(IO.sleep(interval) *> IO.fromOption(IO.sync(checkResponse(id))))
  .retryOrElse(Schedule.duration(timeout), (_, _) => IO.point(None))
```

which is pretty elegant.
