### ISSUE TITLE
Snapshot artifacts published as releases

### ISSUE THREAD

**Issue by sideeffffect** [scalaz/scalaz-zio#196]
Artefacts created from `master` are not releases. Although the tests passed, they might contain code not ready for production use. And if we want to publish *actual* release artefacts, there should be a distinction.

Unfortunately artefacts created from `master` are published to both
 * https://oss.sonatype.org/content/repositories/releases/org/scalaz/scalaz-zio_2.12/
 * https://repo1.maven.org/maven2/org/scalaz/scalaz-zio_2.12/

repositories are dedicated only to release artefacts.
The [maven metadata](https://oss.sonatype.org/content/repositories/releases/org/scalaz/scalaz-zio_2.12/maven-metadata.xml) deceivingly suggest that `0.1.0-1167e15` is not only the latest, but also a release.
```xml
<metadata>
  ...
  <versioning>
    <latest>0.1.0-1167e15</latest>
    <release>0.1.0-1167e15</release>
    <versions>
      ...
      <version>0.1.0-1167e15</version>
    </versions>
    ...
  </versioning>
</metadata>
```

This breaks [Ivy versioning semantics in dependency resolution](https://ant.apache.org/ivy//history/latest-milestone/ivyfile/dependency.html), i. e. `latest.release`.

What prohibits from publishing snapshot artefacts to https://oss.sonatype.org/content/repositories/snapshots/org/scalaz/scalaz-zio_2.12/ ?

**Comment by NeQuissimus** [comment]
Sonatype requires artifacts published to the `snapshots` repository to be suffixed `-SNAPSHOT`.
Currently, our artifacts are rejected by Sonatype's Snapshot repository.

There are three options:
1) We keep what we have, commit hash versions as releases
2) We switch back to using `0.1.0-SNAPSHOT` and skip on the commit hash logic
3) We manually create logic in our build to add the `-SNAPSHOT` suffix to the version string. (for example, we would have `0.1.0-1167e15-SNAPSHOT`)

@ktonga @jdegoes

**Comment by pshirshov** [comment]
From my point of view you should use standard approach with tagged releases. And release after each major P/R merge.

**Comment by sideeffffect** [comment]
@NeQuissimus 
[we're using `sbt-dynver`](https://github.com/scalaz/scalaz-zio/blob/master/project/plugins.sbt#L7)
according to the documentation, we [shouldn't be trying to meddle with the version settings ourselves](https://github.com/dwijnand/sbt-dynver#setup), it will set `version`, `isSnapshot` and `isVersionStable` for us

> make sure to **NOT set the version setting**, otherwise you will override `sbt-dynver`
> ...
> `sbt-dynver` is an AutoPlugin that is all that is required

we just need to set `dynverSonatypeSnapshots` to `true`:
 * https://github.com/dwijnand/sbt-dynver/issues/53#issuecomment-368936969
 * https://github.com/dwijnand/sbt-dynver/pull/64/files#diff-1aca51e17eb6d8522b702c1e094aecb3R16

and [there needs to be a tag on the master branch indicating the version number](https://github.com/dwijnand/sbt-dynver#tag-requirements), `0.1.0` in our case
what do you guys think? does this sounds OK?

**Comment by NeQuissimus** [comment]
I was not aware of `dynverSonatypeSnapshots`. It seems to do what I suggest above, simple suffix `-SNAPSHOT`.
We should no longer need `sbt-release`, correct.
You are welcome to give that a shot.

**Comment by ktonga** [comment]
@NeQuissimus I haven't changed my mind, still think this https://github.com/scalaz/scalaz-zio/pull/151#issuecomment-410579078

By:

> move away from snapshots

I meant to add the SHA so CI artifacts are reproducible and don't break build depending on a continuously changing thing.

To me, it was over complicated for no reason.

**Comment by sideeffffect** [comment]
@ktonga is using `sbt-ci-release` with default settings (plus `dynverSonatypeSnapshots` set to `true`) in conflict with your ideal situation?

**Comment by ktonga** [comment]
@sideeffffect totally the contrary, it seems to do exactly what I want and even better since you can automate the release part by using tags. It is a big :+1: on my side.

**Comment by NeQuissimus** [comment]
Let's try that then... Once we have this PR, we will need to cut a 0.1.0 in order for it to work correctly, if I understand what I am reading (correct me if I'm wrong).
