### ISSUE TITLE
Enhance test suite for retry schedules

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#197]
This is an excellent ticket for someone who wants to thoroughly learn and master Retry schedules in ZIO. I'm happy to offer 1-on-1 support to anyone who has any questions about completing this ticket.

 - [ ] Create a new `RetrySpec`
 - [ ] Move retry-testing methods of `IOSpec` to `RetrySpec`.
 - [ ] Systematically test methods of `Schedule` by using `IO.retry`, `IO.retryOrElse`, and `IO.retryOrElse0`

**Comment by jdegoes** [comment]
@nicodelpiano That would be fantastic! Would love your help on this one. Happy to walk through any of the methods. There's also a bit of documentation in the microsite.

**Comment by NeQuissimus** [comment]
Can this issue be closed?

**Comment by nicodelpiano** [comment]
I think the first two items are done, but we definitely need to add more tests to the test suite. I'm happy to do it!
