### ISSUE TITLE
ioeffect Task

### ISSUE THREAD

**Issue by NeQuissimus** [scalaz/scalaz-zio#200]
I have been using the ioeffect Task type alias/object to bring Java APIs into a pure context.
Is this (https://github.com/scalaz/ioeffect/blob/master/ioeffect/src/main/scala/scalaz/ioeffect/package.scala#L17) something you'd consider for ZIO as well?
I have found it to make operating with Java APIs much more convenient.

**Comment by jdegoes** [comment]
@NeQuissimus Yes, for sure. In the `interop` module.

**Comment by jdegoes** [comment]
Also I believe @fommil has a much more extensive version of this somewhere on Gitlab.

**Comment by fommil** [comment]
@jdegoes I have my own prelude which has a few extensions to this, but not much (it's back on github because that's what my publisher wants me to use for continuous release of the book) https://github.com/fommil/fpmortals/blob/master/example/src/main/scala/fommil/prelude/prelude.scala

I'm not sure there is anything in here you'd want to take, it's mostly convenience methods to turn IO things into Task so I don't have to write `Throwable` everywhere

**Comment by jdegoes** [comment]
Hmm, that's not what I was thinking about. There's somewhere that you defined `IO` specialized to `ZIO[Throwable, ?]`, and added lots of functions to deal with the fixed error types (e.g. `IO.fail` with `Throwable`). That could make a good basis for `Task` if it's more fleshed out than @NeQuissimus snippet.

**Comment by fommil** [comment]
I think that's just the code in the scalaz-ioeffect repo in the package object

**Comment by jdegoes** [comment]
@fommil What happened to `upgrade-scalaz-to-cats` repo on Gitlab?

**Comment by fommil** [comment]
I moved it to the attic... oh you don't want to go near that dumpster fire. I was doing horrible things.

https://gitlab.com/fommil/attic/tree/master/upgrade-typelevel-to-scalaz/src/main/scala

**Comment by jdegoes** [comment]
Ah, this is what I was looking for:

```scala
 // bless me father...
  type ZIO[E, A] = scalaz.ioeffect.IO[E, A]
  @inline final val ZIO: scalaz.ioeffect.IO.type = scalaz.ioeffect.IO
  type IO[A] = scalaz.ioeffect.Task[A]
  object IO {
    type Par[a] = scalaz.ioeffect.Task[a] @@ scalaz.Tags.Parallel

    final def apply[A](effect: =>A): IO[A] = ZIO.syncThrowable(effect)

    final def now[A](effect: A): IO[A]     = ZIO.now(effect)
    final def point[A](effect: =>A): IO[A] = ZIO.point(effect)
    final def pure[A](effect: =>A): IO[A]  = ZIO.point(effect)

    final def sync[A](effect: =>A): IO[A] = ZIO.sync(effect)
    final def async[A](
      register: (scalaz.ioeffect.ExitResult[Throwable, A] => Unit) => Unit
    ): IO[A] = ZIO.async(register)

    final def fail[A](error: Throwable): IO[A] = ZIO.fail(error)

    final def unit: IO[Unit] = ZIO.unit

    import scala.concurrent.duration.Duration
    final def sleep(duration: Duration): IO[Unit] = ZIO.sleep(duration)

    import scala.concurrent.{ ExecutionContext, Future }
    final def fromFuture[E, A](io: IO[Future[A]]): IO[A] =
      ZIO.fromFuture(io)(ExecutionContext.global)
  }

```

**Comment by jdegoes** [comment]
Looks the same as `ioeffect` though...

**Comment by NeQuissimus** [comment]
So, let's just bring the `ioeffect.Task` in here?!

**Comment by fommil** [comment]
Yeah that's just your originally quoted code :-)

**Comment by fommil** [comment]
Btw, please make sure everything in my book's coverage of ioeffect makes it into zio, it'll mean I don't need to rewrite anything :grinning:
