### ISSUE TITLE
Fix failing raceAll test case

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#206]
In `RTSSpec`, the following test case is failing:

```
raceAll of failures
```

This test times out. Likely this is due to a change in the implementation of `raceAll` from using `terminate` to using `IO.never` as the base case for the race. The `raceWith` implementation in `RTS` is possibly where the issue is. Likely the failure can be minimized into a new test case that will make fixing easier.

**Comment by regiskuckaertz** [comment]
I think the problem lies in the combination of two things: (1) if two actions fail, return the last failure, (2) `never` will neither fail nor succeed ever. I can see two ways out: either create a `Never` primitive so that it can be accounted for in `raceWith`, or only allow `raceAll` on non-empty lists.

**Comment by jdegoes** [comment]
@regiskuckaertz It's true that `never` will not succeed or fail, but it can still be interrupted. You can think of it as an `async` task that takes a really long time to complete.

If `race` doesn't work for `never`, it will not work for a long async task.

The correct behavior of `raceAll(never, a, b, c)` is to return the first success of `a`, `b`, or `c`, and to interrupt `never`, which is the same as the correct behavior of `raceAll(z, a, b, c)`, for some `z` that takes 2000 years to finish.

There's a test that `never` can be interrupted, so I expect this is a very subtle bug somewhere, possibly in `RTS.raceWith`.

**Comment by jdegoes** [comment]
@regiskuckaertz 

Ah, you're right. If `a`, `b`, and `c` fail, then you never know if `never` is going to end, so you have to wait it out. That's intentional and good behavior in the general case, since you can always `timeout` the product of a `race`.

So maybe there are no bugs in the current behavior. Just a "bad" test. OTOH, we probably don't want this behavior.

Perhaps we can do the following in `raceAll`:

1. If the list is empty, then terminate (it's a bug).
2. If the list is not empty, race them all, starting from the first task. This way, if all of them fail, you'll get back some error, ideally `race` would error with the last (or first) failure.

So I think a small one-line fix is all it takes to "fix" this. We could also add another variant of `raceAll` that takes an `io: IO[E, A]` and also `ios: List[IO[E, A]]`. In fact, maybe that should be the only one so the user isn't surprised at termination.

**Comment by regiskuckaertz** [comment]
> That's intentional and good behavior in the general case, since you can always timeout the product of a race.

Yes, it's a if `never` was to `race` as `0` is for `*`.

> Perhaps we can do the following in raceAll:

That's better! There is still the possibility that `io` or one of `ios` will reduce to `never`, but then it's a user concern.

**Comment by jdegoes** [comment]
> That's better! There is still the possibility that io or one of ios will reduce to never, but then it's a user concern.

Exactly, and it's indistinguishable from really, really-long async tasks, too. The way I think about it is that if you're doing any kind of potentially long-running task or need to return a result to requestor in a guaranteed amount of time, you need to use timeouts to protect against (a) long-running sync code, (b) long-running async code.

**Comment by jdegoes** [comment]
So how about this:

```scala
def raceAll(io: IO[E, A], ios: List[IO[E, A]]): IO[E, List[A]]
```

Then a user can also do:

```scala
raceAll(IO.terminate)(myList)
raceAll(IO.never)(myList)
raceAll(myFirst)(myOthers)
```

...all from the same API.

**Comment by regiskuckaertz** [comment]
Yes 👍 I'll raise a PR tonight.

**Comment by jdegoes** [comment]
@regiskuckaertz Thank you! 🙏
