### ISSUE TITLE
Randomly (?) failing GPG on Travis

### ISSUE THREAD

**Issue by sideeffffect** [scalaz/scalaz-zio#216]
[this is how it's supposed to look like](https://travis-ci.org/scalaz/scalaz-zio/jobs/419334978#L567)
>
>```
>Running ci-release.
> TRAVIS_SECURE_ENV_VARS=true
> TRAVIS_BRANCH=master
>  TRAVIS_TAG=
>gpg: key 682C4AEC: secret key imported
>gpg: key 682C4AEC: public key "Tim Steinbach <steinbach.tim@gmail.com>" imported
>gpg: Total number processed: 1
>gpg:               imported: 1  (RSA: 1)
>gpg:       secret keys read: 1
>gpg:   secret keys imported: 1
>Snapshot releases must have -SNAPSHOT version number, doing nothing
>```

but sometimes it fails

[like this](https://travis-ci.org/scalaz/scalaz-zio/jobs/419353902)
>```
>Running ci-release.
>  TRAVIS_SECURE_ENV_VARS=true
>  TRAVIS_BRANCH=master
>  TRAVIS_TAG=
>base64: invalid input
>gpg: no valid OpenPGP data found.
>gpg: Total number processed: 0
>No tag push, publishing SNAPSHOT
>```

[or this](https://travis-ci.org/scalaz/scalaz-zio/jobs/419459930#L569)

> ```
>Running ci-release.
>  TRAVIS_SECURE_ENV_VARS=true
>  TRAVIS_BRANCH=master
>  TRAVIS_TAG=
>base64: invalid input
>gpg: no valid OpenPGP data found.
>gpg: Total number processed: 0
>I/O error Pipe closed for process: [echo, ��`�|
>```

is that because somebody was messing with the Travis variable(s) (like `$encrypted_316f730cabee_key` and so on...)?

**Comment by NeQuissimus** [comment]
:sob:

**Comment by sideeffffect** [comment]
@NeQuissimus hasn't this been fixed by your recent changes?

**Comment by NeQuissimus** [comment]
You are right!
