### ISSUE TITLE
Make ZIO microsite look really nice

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#220]
The aesthetics of the microsite leave a lot to be desired. If someone has an eye for design and some CSS / HTML chops, they could make this really beautiful.

**Comment by NeQuissimus** [comment]
Check out scalaz/scalaz@e1198dfbbf8b64a9cb5e48410fbe4bc59902f7eb. It is possible to just define a template for pages.
I have virtually no design skills though :D

**Comment by regiskuckaertz** [comment]
Something like this may help: https://jekyllthemes.io/

**Comment by NeQuissimus** [comment]
I like this for the actual docs: https://jekyllthemes.io/theme/carte
And this could be sweet for the landing page: https://jekyllthemes.io/theme/personal-jekyll-theme But we'd need a nice graphic for the background.

**Comment by Vilkina** [comment]
I can help with html/css :) and some php and js.

**Comment by Vilkina** [comment]
I want to take this ticket.

**Comment by Vilkina** [comment]
I've run microsite locally. @jdegoes, please, assign this ticket to me :)

**Comment by NeQuissimus** [comment]
@Vilkina No need to assign, we don't usually use that. Just send a PR that says "Closes #220" in its description and the PR will be linked to this ticket

**Comment by Vilkina** [comment]
https://github.com/scalaz/scalaz-zio/commit/c2324bc1c499d2c9a3fb73d9c5e9a4669710545f#diff-ca3e85860d2530f979dc78f5b52f9915

**Comment by jdegoes** [comment]
@Vilkina 

Here's the process to submit a pull request:

1. Fork the Scalaz ZIO repository.
2. Clone the ZIO repository into your local folder.
3. Make your changes locally.
4. Preview and commit your changes to Git.
5. Pull in the latest changes from Scalaz ZIO (typically `git pull upstream master`).
6. Resolve any conflicts and run all the tests.
7. Push your changes to your own fork of the repository (Vilkina/scalaz-zio).
8. Open up a new pull request using the Github interface, a pull request "across forks", which compares scalaz/scalaz-zio to Vilkina/scalaz-zio.
9. Review your changes here to make sure they are exactly as you want, otherwise go back to (3).
10. If your changes are as you want, open up the pull request.
11. Make sure the Travis build succeeds.
12. Wait for a reviewer or two to review your pull request.

I took a quick look at your own repository but it looks like the Git client you are using has added lots of directories (`.DS_Store`) on the Mac, way beyond just the changes to the microsite. You can try to undo these additions, or you can reapply your changes to a new fork. Then proceed from step (5) and continue.

Thanks and good luck, holler if you need something!

**Comment by Vilkina** [comment]
How to undo this changes?

**Comment by jdegoes** [comment]
<https://docs.gitlab.com/ee/topics/git/numerous_undo_possibilities_in_git/#undo-remote-changes-with-modifying-history>

**Comment by Vilkina** [comment]
Git client is "crab".
