### ISSUE TITLE
Yeah baby yeah

### ISSUE THREAD

**Issue by NeQuissimus** [scalaz/scalaz-zio#231]
https://travis-ci.org/scalaz/scalaz-zio/builds/421652339

- Tags release artifacts
- Tags publish the microsite

:tada: 

![Yeah Baby](https://i.ytimg.com/vi/T5-Nx9o1yOk/maxresdefault.jpg)

**Comment by NeQuissimus** [comment]
My happiness may have been premature... -.-

**Comment by NeQuissimus** [comment]
https://scalaz.github.io/scalaz-zio/

and

```
 λ amm
Loading...
Welcome to the Ammonite Repl 1.1.2
(Scala 2.12.6 Java 1.8.0_181)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ import coursier.maven.MavenRepository 
import coursier.maven.MavenRepository

@ interp.repositories() ++= Seq(MavenRepository("https://oss.sonatype.org/content/repositories/releases")) 


@ import $ivy.`org.scalaz::scalaz-zio:0.2.6` 
import $ivy.$                             

@ import scalaz.zio._ 
import scalaz.zio._

@ console.putStrLn("Oooooh baby!") 
res4: IO[java.io.IOException, Unit] = scalaz.zio.IO$FlatMap@4a0f4282
```

**Comment by jdegoes** [comment]
@NeQuissimus Hurray! 🕺 🎉 🥂 

This is amazing news, and not a moment too soon, since I have a ZIO workshop this weekend. 😄

**Comment by jdegoes** [comment]
@NeQuissimus Thank you for all your hard work on this! I owe you several beers, at least. 😆 ❤️ 🙏

**Comment by ktonga** [comment]
Great job @NeQuissimus. Turned out it's crazy hard to have a decent release/publish process with the current state of the tooling and its documentation. Maybe a good opportunity for a blog post :slightly_smiling_face:

**Comment by NeQuissimus** [comment]
@jdegoes I am going to try to make it to LambdaConf 2019, we'll definitely hang out...

@ktonga I have https://github.com/NeQuissimus/test-and-stuff that I will hook up a microsite to. That shall serve as my documentation. If we had a "Scalaz blog", I would post there. My own blog is not for these kinds of things (I mostly keep odd one-liners around :D)

**Comment by sideeffffect** [comment]
however, opening gitter on the zio website gives you `404. This is not the chat you're looking for. Sorry. :(`

**Comment by NeQuissimus** [comment]
Oh, that's because there is no ZIO Gitter.. We should probably turn it off.
