### ISSUE TITLE
Blocking IO deadlocks `App`

### ISSUE THREAD

**Issue by kaishh** [scalaz/scalaz-zio#241]
Example:

```scala
import scalaz.zio._
import scalaz.zio.console.{getStrLn, putStrLn}

object Main extends App {

  override def run(args: List[String]): IO[Nothing, ExitStatus] = {
    IO.forkAll {
      List.fill(256)(getStrLn)
    } *> putStrLn("1").forever
  }.catchAll(_ => IO.now(ExitStatus.ExitNow(0)))

}
```

Expected output: `1 1 1 1 1 1 1` ...

Actual result: hangs forever

Works as expected with unbounded thread pool though:

```scala
override val threadPool: ExecutorService = {
  new ThreadPoolExecutor(
    0, Int.MaxValue,
    60, TimeUnit.SECONDS,
    new SynchronousQueue[Runnable](false),
    Executors.defaultThreadFactory())
}
```

Question: 
As of now, I think there are only two ways I can handle blocking IO in a ZIO app - use a separate unbounded RTS and `unsafeRun` blocking tasks there, or run the entire app in unbounded thread pool. Do we need to think of another way to idiomatically handle blocking IO without using `unsafeRun`?

**Comment by kaishh** [comment]
Same with `global` executionContext:

```scala
override val threadPool: ExecutorService = ExecutionContext.global.asInstanceOf[{val executor: ExecutorService}].executor
```

Future can handle this, but **ONLY** if `scala.concurrent.blocking` marker is used:

```scala
  val executorService = ExecutionContext.global.asInstanceOf[{val executor: ExecutorService}].executor
  implicit val executionContext: ExecutionContext = ExecutionContext.fromExecutorService(executorService)

  List.fill(32)(Future(scala.concurrent.blocking(scala.io.StdIn.readLine())))
  def loop: Future[Unit] = Future(println("1")).flatMap(_ => loop)
  Await.result(loop, Inf)
```

**Comment by jdegoes** [comment]
This will definitely be fixed by 1.0.

**Comment by pshirshov** [comment]
Could you give us a hint how are you going to address it?

I would propose something like:

1. Use work-stealing threadpool (not neccessarily unbounded!) for ZIO itself
2. Put all the effect computations into a separate threadpool. Unbounded or with a high upper bound.
3. Allow users to redefine both pools.

What would you say?

**Comment by kaishh** [comment]
NB you can use `IO.shift(ec: ExecutionContext)` to put blocking tasks on a separate thread pool

**Comment by jdegoes** [comment]
@pshirshov 

The problem with this proposal is that (2) will make ZIO very slow in common cases. Although it has nice ergonomics from the user's point of view.

I will write up my current proposal in separate ticket and reference it here.

**Comment by jdegoes** [comment]
@pshirshov @kaishh See #248 for the current proposed solution.

**Comment by regiskuckaertz** [comment]
This seems to be working as expected now, can we consider it fixed?
