### ISSUE TITLE
2.11 test locks

### ISSUE THREAD

**Issue by NeQuissimus** [scalaz/scalaz-zio#246]
OK, so I have seen this a few times. Now I am opening an issue for somebody smarter than me to investigate:

Every now and then (yay!), the 2.11 tests (I have never seen this with 2.12) will hang at the very end. I have only ever seen this if resources are not cleaned up properly and the forked JVM cannot shut down. Not sure if that is the case here.

Example build:
https://travis-ci.org/scalaz/scalaz-zio/jobs/425071678

If you have Travis retry, it will likely work.

**Comment by jdegoes** [comment]
Probably we should make sure that all tests run `supervised` in case where any ongoing work is done in fibers.

Also we should hook into the testing framework to shut down the thread pools after each test suite is done.

**Comment by jdegoes** [comment]
Most likely fixed.
