### ISSUE TITLE
Create a microsite using sbt-microsites

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#25]
This ticket is to create machinery to give us a microsite at `http://scalaz.github/scalaz-zio/`.

[SBT Microsites](https://47deg.github.io/sbt-microsites/)

Copy and examples can be added later, and are not considered part of this ticket.

**Comment by NeQuissimus** [comment]
@jdegoes Can you add me to the project and assign this to me? Then I'll take care of the microsite machinery.
