### ISSUE TITLE
Add a solution for composing bracketed resources

### ISSUE THREAD

**Issue by iravid** [scalaz/scalaz-zio#254]
Composing brackets is a pain:
```scala
val resource1: IO[E, R1]
val resource2: IO[E, R2]

resource1.bracket(release1) { r1 =>
  resource2.bracket(release2) { r2 =>
    // ...
  }
}
```

Prior art:
- http://hackage.haskell.org/package/managed - very simple to port, partially applies `IO.bracket` to create a monad
- http://hackage.haskell.org/package/resourcet - allows more fine-grained control on resource cleanup (e.g. cleanup handlers can run before the bracket region ends), abstracts over the effect type. Would be harder to port; I don't know if ZIO needs this data type built in.
- https://github.com/typelevel/cats-effect/blob/master/core/shared/src/main/scala/cats/effect/Resource.scala - abstracts over the effect type and uses a separate algebra to facilitate interpreters that need different resource scoping rules (e.g. streams). Also has a nice utility for easily lifting resources that are `<: AutoCloseable`.
- https://github.com/scala/scala/pull/6907 - hardcoded to `Try`

**Comment by kaishh** [comment]
There's also `Using` in 2.13 standard library that does this for `Try` - https://github.com/scala/scala/pull/6907

**Comment by iravid** [comment]
True. Added that and cats-effect's `Resource`
