### ISSUE TITLE
Replace remaining examples with compiled code

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#26]
Edit by @NeQuissimus:

The microsite contains various example snippets in `scala` code blocks that do not currently compile.
We should replace those with `tut` blocks that are type-checked and executed as part of the microsite generation.

**Comment by nebtrx** [comment]
Hey, I'm looking at `good first issues` tag to see where can I start doing small contributions and I found this one.

Can you elaborate a little bit more on this one @jdegoes? 

The only lead I have on this is the 8af2db6 commit which actually is not very self-explanatory

**Comment by jdegoes** [comment]
@nebtrx Please see [the website for tut](https://github.com/tpolecat/tut).

We should have lots of executable code snippets as part of the documentation.

**Comment by nebtrx** [comment]
Cool thx! I'll take a look at the tool and the proper way to use it

**Comment by NeQuissimus** [comment]
In #163 I am doing most of the heavy-lifting.
I think this ticket here should probably be to replace the remaining non-tut blocks.
What do you think, @jdegoes ?

**Comment by jdegoes** [comment]
@NeQuissimus Sounds good to me!

**Comment by NeQuissimus** [comment]
Issue description updated
