### ISSUE TITLE
Add circuit breaker?

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#272]
@wi101 suggested a circuit breaker can be built atop `Schedule`, in which case it should be just a few lines of code.

```scala
trait CircuitBreaker[-E] {
  def apply[E1 <: E, A](io: IO[E1, A]): IO[E1, A]
}
object CircuitBreaker {
  sealed trait State
  final case object Closed   extends State 
  final case object Open     extends State
  final case object HalfOpen extends State

  sealed trait Message[E]
  case object TestState extends Message[Nothing]
  case object Success extends Message[Nothing]
  case class Failed[E](error: E) extends Message[E]
  
  /**
   * Create a new circuit breaker with the given default error for rejected tasks, and the given policy.
   */
  def apply[E](rejected: E, policy: Schedule[Message[E], State]): IO[Nothing, CircuitBreaker[E]] = 
    ???
}

/**
// Example usage
for {
  breaker <- circuitBreaker(RejectedError, myPolicy)
  as     <- IO.parAll(List.fill(100)(breaker(io1)))
} yield as
*/
```

Creating a circuit breaker will involve allocating a `Ref` to hold the state of the `policy` (and maybe other things).

**Comment by jdegoes** [comment]
Probably, it would help to provide a `default` circuit breaker, or maybe just combinators that allow more easier production of the three closed/open/half-open states.

**Comment by lemastero** [comment]
I think that `circuit breaker` is one of essential feature for good streaming library. Is there a way to achieve this currently in ZIO?

**Comment by ahoy-jon** [comment]
@lemastero, @jdegoes wrote this article a while back http://degoes.net/articles/zio-challenge.
