### ISSUE TITLE
Synchronous flatMaps cause fiber starvation

### ISSUE THREAD

**Issue by kaishh** [scalaz/scalaz-zio#273]
Given:

```scala
import scalaz.zio._

object App extends App {
  def worker(i: Int) =
    IO.sync(println(s"running $i")).forever

  override def run(args: List[String]): IO[Nothing, ExitStatus] =
    IO.traverse(1 to 50)(worker(_).fork)
      .flatMap(Fiber.joinAll(_))
      .const(ExitStatus.ExitNow(0))
}
```

Expected:

Prints for `running 1-50`

Actual:

Prints `running 1-$numCores` for ~15 seconds, then slowly climbs to a higher number.

Inserting an asynchronous boundary fixes that, but note that ZIO lacks a `.yield` function in API for this use case, such as cats-effect's `ContextShift.shift` – 

```scala
def worker(i: Int) =
  (IO.sync(println(s"running $i")) *> 
    IO.async((cb: Callback[Nothing, Unit]) => cb(ExitResult.Completed(()))))
  .forever
```

However, AFAIK, explicit cooperative concurrency via `.yield` combinator is a non-goal for ZIO. So, what's the current plan for a scheme that manages this better than the `YieldMaxOpCount` in 1.0?

**Comment by jdegoes** [comment]
This is closely related to #248, and the proper fix probably depends on how that ticket turns out (please contribute feedback!).

For now you can switch to an unbounded thread pool, you can use `IO.sleep(0.seconds)`, which is a semantic `yield` (I'd accept a PR that added the function), or you can reduce `YieldMaxOpCount` to something like `1000`.

**Comment by cuongthamhl** [comment]
@jdegoes Can you provide an example on how to switch to an unbounded thread pool by using `IO.sleep(0.seconds)`?

Also how can I reduce the `YieldMaxOpCount` in RTS?  I thought it's marked as `final`. Here's how I run an IO:

```
class IORuntime extends RTS {}
val ioRunTime = new IORuntime
ioRunTime.unsafeRun(io)
```

**Comment by RaasAhsan** [comment]
@cuongthamhl You can shift to another thread pool with the `IO.shift` combinator. However, to shift back to the RTS pool, you will need to insert an explicit asynchronous boundary via `IO.sleep(0.seconds)`.

```scala
val ec: ExecutionContext = ...
taskA *> IO.shift(ec) *> taskB *> IO.sleep(0 seconds)
```

**Comment by regiskuckaertz** [comment]
This one can be closed, can't it? Just ran it and it looks fine.

**Comment by kaishh** [comment]
Yes, this example should be ok now, as long as the user keeps flatMapping they should eventually get unstuck...
