### ISSUE TITLE
Parallelism level for parAll and traverseAll

### ISSUE THREAD

**Issue by ioleo** [scalaz/scalaz-zio#278]
Use case: say you want to send thousands of requests to another service, but you do know, that it can't handle more than 20 open connections. One of the possible approaches would be simply use `IO.parAll(requests)`, however, I don't think there is a way in current API to control the parallelism level.

**Comment by pshirshov** [comment]
I guess a semaphore primitive would work

**Comment by regiskuckaertz** [comment]
Also, there is ongoing work for abstracting all that in https://github.com/scalaz/scalaz-zio/pull/262 , keep your eyes peeled.

**Comment by jdegoes** [comment]
Fixed in #262
