### ISSUE TITLE
.timeout always loses errors in timed out computations & waits for full duration

### ISSUE THREAD

**Issue by kaishh** [scalaz/scalaz-zio#281]
Example:
```
import scalaz.zio._
import scalaz.zio.console._
import scala.concurrent.duration._

object App extends App {
  override def run(args: List[String]): IO[Nothing, ExitStatus] = {
    for {
      p <- Promise.make[Throwable, Option[Int]]
      _ <- p.error(new RuntimeException("Everything is bad!"))
        .fork
      timedOut <- p.get.timeout(true)(_ => false)(30.seconds)
      _ <- if (timedOut) putStrLn("Timed out, no errors reported") else IO.unit
    } yield ExitStatus.ExitNow(0)
  }.catchAll(_ => IO.now(ExitStatus.ExitNow(1)))
}
```

Expected: Immediate exit with an exception

Actual: Waits for 30 seconds, then reports true.

Cause: The error on the left side of the `.race` is ignored and the right branch with the timer is taken.

Also happens if the second argument of timeout throws:

```scala
IO.now(1).timeout(5)(_ / 0)(30.seconds)
// 30 second block
```

`.timeout` is secretly `IO[Nothing, B]`, not `IO[E, B]` as of now due to this

**Comment by kaishh** [comment]
The problem persists if the action terminated, not failed:

```scala
IO.terminate.timeout[Option[Int]](None)(Some(_))(1.hour)
// res0 = waits 1 hour
```

**Comment by jdegoes** [comment]
@kaishh Noted.

**TODO**: We should make semantics such that termination of the action results in immediate timeout.

**Comment by regiskuckaertz** [comment]
This is fixed with the reworked `raceWith` 🤗
