### ISSUE TITLE
IO.fromTry 

### ISSUE THREAD

**Issue by xplosunn** [scalaz/scalaz-zio#283]
The current implementation of fromTry is just a conversion from a Try value. This means that if I have a side-efectfull method that returns a Try, I have to do some weird workaround to avoid it getting evaluated on the parameter resolution, such as `IO.point(()).flatMap(_ => tryMethod())`. If I had a method that I could call which would evaluate the Try body later, then I wouldn't have this issue.

Does it make sense to create a new function for this use case or changing the fromTry implementation?

**Comment by jdegoes** [comment]
The current one could be changed to be by name `=>`. Basically, `IO.sync(try).flatMap { case Success(v) => IO.now(v); case Failure(t) => IO.fail(t) }`.
