### ISSUE TITLE
Finalize method / data type names for 1.0

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#287]
List of proposed changes:

 - [ ] `IO.traverse`: **Add** an alias: `IO.foreach`
 - [ ] `IO.parTraverse`: Rename to `IO.traversePar`
 - [ ] `IO.traversePar`: **Add** an alias: `IO.foreachPar`
 - [ ] `io.redeemPure` Rename to `io.fold` (?)
 - [ ] `io.redeem` **Add** an alias `io.foldM` (?)
 - [ ] `io.asyncPure` rename to `io.asyncM`
 - [ ] `IO.sequence`: **Add** an alias: `IO.collect`.
 - [ ] `IO.parAll` rename to `IO.collectPar`
 - [ ] `IO.collectPar`: **Add** an alias `IO.sequencePar`.
 - [ ] `raceBoth` rename to `raceEither` (?)
 - [ ] `ref.setLater` rename to `ref.setAsync`
 - [ ] `refM.setLater` rename to refM.setAsync
 - [ ] `sandboxed` rename to `sandbox`
 - [ ] `unsandboxed` rename to `unsandbox`
 - [ ] `par` rename to `zipPar`
 - [ ] `parWith` rename to `zipWithPar`
 - [ ] `seq` rename to `zip`
 - [ ] `seqWith` rename to `zipWith`
 - [ ] `supervised` rename to `supervise`
 - [ ] `supervised(handler)` rename to `superviseWith`
 - [ ] `fork0(handler)` rename to `forkWith(handler)`
 - [ ] `uninterruptibly` rename to `uninterruptible`
 - [ ] `promise.error` rename to `promise.raiseChecked`
 - [ ] `promise.get` rename to `promise.await`
 - [ ] `promise.complete` rename to `promise.succeed`
 - [ ] `<||>` (`Schedule`, `IO`) renamed to an alias (?)
 - [ ] `ExitResult.Succeeded` rename to `Success`
 - [ ] `ExitResult.Failed` rename to `Failure`
 - [ ] `ExitResult.succeeded` rename to `ExitResult.succeed`
 - [ ] `ExitResult.failed` rename to `ExitResult.fail`
 - [ ] `ExitResult` rename to `Exit`
 - [ ] `IO.now` rename to `IO.succeed`
 - [ ] `IO.point` **Add** an alias `IO.succeedLazy`
 - [ ] `IO.terminate` rename to `IO.die`
 - [ ] `IO.fail0` rename to `IO.halt`
 - [ ] `KleisliIO` rename to `FunctionIO` (?)

**Comment by kaishh** [comment]
`-` on traverse, parTraverse, sequence – IMHO it's better to retain common names for these, soft `-` on redeem – I personally haven't had a use for redeemPure yet, so I'd prefer to keep a shorter name for the variant I do use. `+` on asyncM and timeout

**Comment by ratoshniuk** [comment]
as @kaishh said I put `traverse`, `parTraverse`, `sequence` and `redeem`

implemented `timeout`

others are renamed

**Comment by regiskuckaertz** [comment]
- `raceEither` ⇒ `race` ([see](https://github.com/scalaz/scalaz-zio/pull/311#discussion_r227278862))
- `race` ⇒ `raceMerge`
- `raceWith` ⇒ `race0`
- `sandboxed` ⇒ `sandbox`
- `sandboxWith` ⇒ `sandbox0`
- `parWith` ⇒ `par0`
- `seqWith` ⇒ `seq0`
- `supervised` ⇒ `supervise`
- `supervised` ⇒ `supervise0` (the more powerful version)
- `timed` ⇒ `time`
- `timed0` ⇒ `time0`
- `uninterruptibly` ⇒ `atomic`

**Comment by regiskuckaertz** [comment]
In the companion:
- `asyncPure` ⇒ `asyncM`
- `superviseWith` ⇒ `supervise0`

I think indeed `traverse` and `sequence` are part of the functional vernacular, whereas foreach has an imperative after-taste.

**Comment by sideeffffect** [comment]
my 2 bikeshedding cents:

* names -- cannonical names and deprecated alisases, for example:
  * let `forEach` be the canonical name here, because it conveys better the specific meaning specific to `IO`
  * let `traverse` be a deprecated alias that is still easy to discover (not only in IDE) by people already familiar with the concept, but advising them to use `forEach`

* flavors -- good as suffixes, for example:
  * let the sequential variant be the default, so `forEach` (or just `each`), `all`, ...
  * let the specific variants come at the end, so `forEachPar` (or just `eachPar`), `allPar`, ...
  * this is easy to discover in IDE, when exploring via pressing *dot* -- first you zoom on the kind of operation you want, and then you see if it also comes in a parallel variant or whatever

**Comment by jdegoes** [comment]
- [ ] `promise.error` => `promise.fail`

Also I'm agreed on the desirability of aliases for `sequence`, `traverse`, etc. The aliases are for people who know FP (it's quite standard terminology) but the other ones are for the much larger non-FP market.

The "default = Seq" is interesting. We should be consistent. I also like designing for dot syntax so putting `Par` as a suffix always (rather than as a prefix sometimes, e.g. `parAll`) makes sense.

**Comment by jdegoes** [comment]
Oh, and for `With`, I think we should save that suffix for variants that take a "compose" function as a parameter, rather than using it for the "most powerful" variant. I admit I don't really like the `foo0` convention (I'd rather `foo'` 😄 ), but I feel `With` is a poor fit for the most powerful variant, too.

**Comment by jdegoes** [comment]
@kaishh I agree it's more common to use `redeem` than `redeemPure`. Though there's an emerging pattern in ZIO to suffix `M` for monadic versions of functions (e.g. `mapM` in `Schedule`). I'm not sure what to do about the tension between consistency in naming convention and the higher relative importance of `redeem`.

**Comment by jdegoes** [comment]
@kaishh @regiskuckaertz @sideeffffect 

I made some quite substantial modifications, incorporating all feedback from this thread. Summary of high-level changes:

1. Now `par` is always a suffix, rather than sometimes a suffix, and sometimes a prefix, to aid discoverability with auto-complete.
2. The sequential version is always the default, because parallel code has overhead and users should be explicit about that.
3. The `0` suffix is retained for now, for the "most powerful" version of a combinator.
4. The `With` suffix is retained in any case where a "more powerful" version accepts a function.
5. The "classic" names of functional programming primitives (sequence, traverse) are retained. However, aliases are introduced to make the specific meaning in the context of `IO` clear to those who aren't using FP libraries or don't come from an FP background.

@regiskuckaertz I didn't change `uninterruptibly` to `atomic` because I'm afraid users will think it means atomic in another sense (database, STM, etc.). But I did change it to be more consistent (`uninterruptible`).

I think another code audit or two are necessary to collect any outstanding deviations and incorporate them here.

**Comment by jdegoes** [comment]
Btw what do folks think of the `F` suffix rather than `M` suffix for the effectful versions? I see it's used by Cats in some places (`asyncF`) and has the nice benefit of starting with a sound that sounds similar to "eff" in "effect". Although `M` is more common in Haskell code.

**Comment by regiskuckaertz** [comment]
> Btw what do folks think of the F suffix

I like it. `M` and `A` are used in Haskell/[Scalaz](https://github.com/scalaz/scalaz/pull/2022#pullrequestreview-171333848) already to abstract over _any_ monad/applicative. `F` makes more sense locally.

**Comment by regiskuckaertz** [comment]
PureScript [uses `E`](https://pursuit.purescript.org/packages/purescript-eff/3.2.1/docs/Control.Monad.Eff#t:Eff) for `Eff`-specific functions.

**Comment by sideeffffect** [comment]
2 other bikeshedding cents:
regarding `F`, `A`, `M` suffixes -- shouldn't they be used for communicating if the function works with a `F`unctor, `A`pplicative functor or `M`onad respectively?
In that case, the decision should be made on case by case basis, considering each function and what functionality from the `IO` class it needs.
E.g. if it only uses `ap` or `pure` inside, it should use `A` as suffix. If it requires `flatMap`/`bind`, use the `M` suffix.

**Comment by jdegoes** [comment]
@sideeffffect Since ZIO is standalone, there are no dependencies on Scalaz / Cats, so no type classes, so no monad / applicative / functor.

I'd be nice to use name overloading here to bypass the issue entirely, although I think in most cases that would have no effect because after erasure, they end up the same, anyway.

**Comment by sideeffffect** [comment]
@jdegoes possible typos:

* [ ]  `IO.collectPar`: **Add** an alias `IO.parSequence`.

shouldn't it be 

* [ ]  `IO.collectPar`: **Add** an alias `IO.sequencePar`.

?

and

> `supervised` rename to `supervise`
> `supervised` rename to `superviseWith`

**Comment by jdegoes** [comment]
@regiskuckaertz How about `Exit` instead of `Result`? Thinking that `Result` is pretty generic but `Exit` is more specific.

**Comment by jdegoes** [comment]
@sideeffffect Fixed, thanks!

**Comment by regiskuckaertz** [comment]
```scala
trait Fiber {
  def observe: IO[Nothing, Exit[E, A]]
  // or
  def observe: IO[Nothing, Result[E, A]]
}
```
The longer I look at it, the more I think `Exit` works.

**Comment by regiskuckaertz** [comment]
What about:
- `Ref` ⇒ `Var`
- `RefM` ⇒ `VarF`
following the decision to drop the `M` suffix?

**Comment by jdegoes** [comment]
@regiskuckaertz 👍

If we actually do all this, we should make a ScalaFix migration to update code for the changes.

**Comment by sideeffffect** [comment]
@regiskuckaertz why would you want to rename the `Ref` class for *references* to `Var` even though the are not *variables*?

**Comment by jdegoes** [comment]
@regiskuckaertz They're not variables in the PLT / math sense, but they're variables in the Scala sense (`var` versus `val`). Makes a certain amount of sense to someone working in Scala.

**Comment by kaishh** [comment]
I'd rather we not introduce more names for the same concepts. I'm personally more in favor of keeping `RefM` or even `RefF`.

**Comment by regiskuckaertz** [comment]
@sideeffffect I know, `RefF` looked odd is all. I'm not attached to it so I will go with what the consensus is 🤗

I don't think this is too far off the PLT wisdom. In languages like Scala, Java, C etc, a `var x : A` is just a `val x : Ref[Option[A]]` with syntactic sugar; see Pierce 2002.
