### ISSUE TITLE
Semaphore broken?

### ISSUE THREAD

**Issue by kaishh** [scalaz/scalaz-zio#293]
Example:

```scala
import scalaz.zio._

object App extends App {
  new RTS{}.unsafeRun {
    for {
      s <- Semaphore(1).peek(_.acquire)
      _ <- s.release.fork
      _ <- s.acquire
    } yield ()
  }
}
```

Blocks forever. Removing `.fork` from `release` makes it work.

**Comment by jdegoes** [comment]
Possibly relevant since Semaphore was ported from FS2:

<https://github.com/typelevel/cats-effect/issues/380>

**Comment by jdegoes** [comment]
@kaishh We will switch to daemonic threads, see #295 / #294, which will hopefully solve problems like this.

This example looks unsound. The `s.acquireN(50)` should never succeed.

I will be finishing `STM` soon in which case we may as well delete this `Semaphore`. It would be interesting, though, to see if the source `Semaphore` also has this problem or if it was introduced in the port.

**Comment by jdegoes** [comment]
Confirmed, Semaphore is definitely broken. It works in simple examples but inevitably deadlocks in more complex examples. TBD if these changes were introduced in the port or not.

**Comment by regiskuckaertz** [comment]
I can have a look later this week
