### ISSUE TITLE
Change default thread pool used by RTS

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#294]
The current thread pool is fixed. We should change it to something that's more dynamic and will eventually shut down all threads after sufficient inactivity.

**Comment by RaasAhsan** [comment]
I'd like to work on this. I was thinking we can allocate a ThreadPoolExecutor (https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ThreadPoolExecutor.html), perhaps configured with a certain `corePoolSize` of 2 or so, a higher maximumPoolSize to handle bursts of activity, and a keepAliveTime of 60 seconds before threads are reclaimed.

**Comment by RaasAhsan** [comment]
Started some work in #295. Check it out!
