### ISSUE TITLE
Use readable fiber names when being co-opted by the RTS

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#296]
```scala
class NamingThreadFactory(name: String) extends ThreadFactory {
  final private val s: SecurityManager = System.getSecurityManager

  final private val parentGroup: ThreadGroup = {
    if (s != null) {
      s.getThreadGroup
    } else {
      Thread.currentThread.getThreadGroup
    }
  }

  final private val group = new ThreadGroup(parentGroup, name)

  final private val threadNumber = new AtomicInteger(1)

  def spawnedThreads: Int = {
    threadNumber.get() - 1
  }

  override def newThread(r: Runnable): Thread = {
    // hashcode added to make names unique in case of duplicated name
    val t = new Thread(group, r, s"$name-${threadNumber.getAndIncrement}-${Integer.toUnsignedString(hashCode())}", 0)
    if (t.isDaemon) {
      t.setDaemon(false)
    }
    if (t.getPriority != Thread.NORM_PRIORITY) {
      t.setPriority(Thread.NORM_PRIORITY)
    }
    t
  }
}
```

**Comment by pshirshov** [comment]
I'm still bit unhappy with this snippet, that's why I didn't submitted it as a P/R yet (this is a copypaste from our private codebase).

I kinda dislike hashcode usage, but the only sane alternative I see is to use a static counter which is even worse than hashcode.

So, would be happy to hear other ideas, then I may submit it.

**Comment by jdegoes** [comment]
I think we can do the following:

1. Assign each `RTS` a monotonically increasing integer.
2. Assign each `Fiber` in each `RTS` a monotonically increasing integer.
3. Have fibers utilize `Thread.setName` to dynamically change the names of threads based on their RTS and fiber identifier.

This would allow very good thread dumps, e.g.:

```
RTS #1, Fiber #2884 
```

**Comment by pshirshov** [comment]
I would not recommend to dynamically change thread name. It looks like hell in jvisualvm and other instrumentation/monitoring tools.

Not sure about perf impact, never measured it.
