### ISSUE TITLE
Separate thread pools for different kinds of zio tasks

### ISSUE THREAD

**Issue by pshirshov** [scalaz/scalaz-zio#297]
The proposal:

1. Introduce new method, `IO.blocking(a: => A): IO[Nothing, A]`, equivalent so `sync`
2. All the `blocking` computations  should be scheduled to a separate thread pool with high upper boundary and short queue
3. As well we may support scala's `blocking` and schedule such tasks to that thread pool (proposed by @kaishh in several discussions)
4. We may create one more thread pool inteded to serve all the internal waits. This pool should have low upper boundary and relatively long queue
5. Primary ZIO thread pool upper boundary should be intended for computations only and limited to `core_number + 1` threads. Queue size should be set to zero.

You may find the detailed motivation here: https://github.com/scalaz/scalaz-zio/pull/295#issuecomment-428927804

Related problem (ZIO computations should be terminated when thread pool rejects a task):  https://github.com/scalaz/scalaz-zio/issues/277#issuecomment-427916988

**Comment by RaasAhsan** [comment]
> Introduce new method, IO.blocking(a: => A): IO[Nothing, A], equivalent so sync
All the blocking computations should be scheduled to a separate thread pool with high upper boundary and short queue

So ZIO will maintain multiple pools as part of its RTS or will there be a single pool per RTS? Will this discourage users from creating their own pools?

> Primary ZIO thread pool upper boundary should be intended for computations only and limited to core_number + 1 threads.

If your processor supports hyperthreading on its cores, `core_number * 2` would yield a higher throughput. Do we want to take advantage of this by default, or would users be encouraged to optimize their own pool for such things?

> Queue size should be set to zero.

If all threads are busy in a fixed pool with a `SynchronousQueue`, submission of another task will fail or block at best (dictated by [a rejection handler](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ThreadPoolExecutor.html)). I imagine we wouldn't want to discard tasks, and if we block, there is a potential of a deadlock (a thread on the pool attempts to submit another task but it is blocked because all other threads are busy). I think an unbounded queue is necessary when using fixed pools where threads can submit tasks back to their own pool.

**Comment by pshirshov** [comment]
> So ZIO will maintain multiple pools as part of its RTS or will there be a single pool per RTS? 

Two pools (plus timers pool)

> Will this discourage users from creating their own pools?

Yes

> I imagine we wouldn't want to discard tasks, and if we block, there is a potential of a deadlock 

If we hit the limit of blocking pool (and get rejection exception), computation should be `Terminated` I think. It's better to set the limit instead of spawning thousands of threads effectively killing the OS scheduler (IMO). The limit itself is still discussable though I think that quadratic/qubic one is fine enough.

> If your processor supports hyperthreading on its cores, core_number * 2 would yield a higher throughput.

When I said "core number" I meant "hardware threads number".

**Comment by RaasAhsan** [comment]
> If we hit the limit of blocking pool (and get rejection exception), computation should be Terminated I think.

I was talking about the primary ZIO fixed pool for computation you mentioned in the OP. If you have 8 threads running fibers in a fixed pool of size 8 and one of them submits a task to a saturated queue, should the entire computation fail? Adding to work queue only spawns new threads if the current number of live threads is fewer than maximum and the work queue is full.

**Comment by pshirshov** [comment]
I've updated my comment.

I think you may make both the upper boundaries configurable. Primary pool should have `cores+1` by default, and blocking pool should have `pow(cores, 2)` by default.

`RTS.maximumBlockingOps : Option[Int] = Some(cores * cores)`
`RTS.maximumCPUOps : Option[Int] = Some(cores + 1)`

**Comment by RaasAhsan** [comment]
> UPD: I've misread your comment a bit. So, regarding the primary pool. The configuration (cores+1) already assumes that the pool takes the maximum computational throughput. So in case we got a rejection - most likely the queue would continue growing and at the end the app will die or computations will terminate. So, there is no real need (IMO) to set non-zero queue for computational pool. In case it's being overscheduled - in almost all the cases nothing may save us (this is not true only for apps with specific load profile, which are idle almost all the time but have peaks of high CPU intensity)

The purpose of a fixed pool is to prevent CPU overscheduling while still being productive. Those threads in the pool will pull and execute tasks to completion. If you submit a task and all threads are currently busy, the task is queued in memory. Whenever a thread finishes its task, it will begin processing the next one. This offers a means of graceful degradation: latency for a task may increase slightly, but it will eventually be processed. If the pool has to queue a task, chances are the task must only wait <1 ms before being picked up.

However, it is conceivable that at some point the work queue will become so large that latencies become exceptionally high and it may be a good idea to fail. If an unbounded queue isn't used, then a pool with a high upper boundary should be used (depends on hardware of course).

The queue size is also dependent on your workloads and SLAs. Workloads can change over time: for a web server, sometimes it may experience high traffic and sometimes it may experience low traffic. If all the threads in a web server's pool are busy and a new request comes in, should that request really be failed? It depends, but if another thread finishes soon after, it can pick the new one up (ties back to graceful degradation).

**Comment by pshirshov** [comment]
> This offers a means of graceful degradation: latency for a task may increase slightly, but it will eventually be processed. 

Depends on load profile. In case you produce more than you can consume - the app/machine will die anyway.

> If the pool has to queue a task, chances are the task must only wait <1 ms before being picked up.

You may set a short queue but it wouldn't change anything, really. In case you are producing faster than consuming - you have a problem. And your effective consumption speed is limited by number of cores. Plus one thread to fill the scheduling gaps.

> If an unbounded queue isn't used,

Unbounded queue is the worst thing I can imagine, honestly. It's a way to complete degradation of the app/machine KPIs/OOMs/etc.

> The queue size is also dependent on your workloads and SLAs. 

True. I've proposed "sane defaults" (based on my own experience) but my point was and is: we should allow the user to configure these things.

> Workloads can change over time: for a web server, sometimes it may experience high traffic and sometimes it may experience low traffic.

True. Actually, if you use the defaults I've proposed - it's very unlikely you may get rejections. Again - you can't consume cpu-bound tasks faster than it can be done by `cores+1` threads. And in case your tasks are being scheduled faster - you are in trouble. Short queue may work well for some load profiles - but wouldn't change much in general. Though I'm not agains short queue. I'm against unbounded pool sizes and queues.

> the threads in a web server's pool are busy and a new request comes in, should that request really be failed? 

Don't forget about NIO queue. 

> should that request really be failed? 

Better fail than freeze :)

> It depends, but if another thread finishes soon after, it can pick the new one up (ties back to graceful degradation).

`cores + 1` should be already at max CPU throughput.

**Comment by artempyanykh** [comment]
It's totally reasonable to have separate threadpools for IO vs CPU bound tasks. The question is -- do we want to introduce one more thread pool for blocking stuff into any RTS or maybe we would like to have separate `RTS`s for different types of workload and allow users to explicitly `shift` onto `RTS` of his choosing if needed? IIRC the latter was considered here https://github.com/scalaz/scalaz-zio/issues/36

I'm also all for back-pressure, but just putting bounds on those pesky queues doesn't seem enough. There should be a way for a user to specify exactly how they want to handle task rejections. Java `ExecutorService`s provide `RejectedExecutionHandler`s, but do we have a ZIO-style abstraction for this?

**Comment by pshirshov** [comment]
> Java ExecutorServices provide RejectedExecutionHandlers, but do we have a ZIO-style abstraction for this?

We do. `Terminated` :)

> The question is -- do we want to introduce one more thread pool 

I guess it a question for @jdegoes . I would vote for just one RTS.

**Comment by artempyanykh** [comment]
> We do. Terminated :)
@pshirshov not sure I follow. Terminated is an exit status that signals either interruption or unhandled exception during execution. Do you suggest using it for flow control as well?

**Comment by regiskuckaertz** [comment]
I like the idea of having multiple RTS that each capture an evaluation mechanism. It would be useful for the `SyncIO` data type (or other interesting subsets like `ParIO` 😋): we could enforce a composed RTS to have the ability (or lack thereof) to evaluate IO actions that may contain `SyncIO`s. The JS RTS would not have that ability and so trying to run a `SyncIO` in JS would fail at compile-time.

**Comment by RaasAhsan** [comment]
I thought that having `RTS` contain every type of pool seemed a bit at odds with the goal of having multiple composable RTS. If every `RTS` has a dedicated pool, should each also have a dedicated timer pool (what it looks like right now), or should a separate type be developed for that?
