### ISSUE TITLE
Fork not working correctly with new thread pool

### ISSUE THREAD

**Issue by pierangeloc** [scalaz/scalaz-zio#315]
With ZIO version `0.3.1` I run this code

```scala
object scheduleplayground extends App {

  val prg: IO[Nothing, Unit] = for {
    queue <- Queue.unbounded[String]

    worker = queue.take.flatMap(putStrLn).forever
    workers10K = List.fill(10000)(worker)

    _ <- IO.forkAll(workers10K)
    _ <- queue.offer("Chocolate").forever.fork

  } yield ()

  val prg2: IO[IOException, Unit] = for {
    _ <- putStrLn("Hello, who are you?")
    n <- getStrLn
    _ <- putStrLn(s"Good morning $n")
  } yield ()

  val rts: RTS = new RTS {}

  rts.unsafeRunSync(prg)
}
```

The program ends immediately, instead of printing continuously. With ZIO version `0.2.9` instead, it runs correctly.
If I replace the thread pool with the old one, the program runs again properly. 

```scala
val rts: RTS = new RTS {
    override val threadPool = Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors().max(2))
  }
```

Looks like something is not working properly in the new  default thread pool.

**Comment by kaishh** [comment]
It's correct. The program exits once the main fiber exits. If you want this program to run forever, put an `IO.never` at the end.

**Comment by artempyanykh** [comment]
@RaasAhsan btw, what was the reasoning behind setting pool threads as _deamon_? If some threads run fibers with cleanup actions, they may get killed before the cleanup is finished and thus the program will terminate incorrectly. 

Do we imply that main Fiber should always join forked Fibers?

**Comment by regiskuckaertz** [comment]
> Do we imply that main Fiber should always join forked Fibers?

@artempyanykh that's a great question. what is more sensible? at this point it becomes a usability issue, we should compare both behaviours with real-world examples

**Comment by RaasAhsan** [comment]
@artempyanykh I think its an appropriate choice for several reasons.

1. It forces the user to think about and explicitly define the criteria for application exit.
2. Waiting on the threads in the RTS pool to die can be unpredictable. This may be less of an issue with the pool that you defined (where core threads time out very quickly), but only when tasks finish quickly. Long-running tasks and non-terminating tasks that don't traverse the RTS can't be cancelled immediately. If we give users the liberty to override the pool, depending on their configuration, core pool threads may never time out either. (Should we provide factories for users?)
3. There are several ZIO types that offer synchronization for scenarios exactly like this. Joining on fibers is also a choice.
4. If the application is exiting, cleanup actions like releasing database connections isn't necessary; either the OS will close the connection or your database will. However, if you want to block until some condition holds true, you can. If you want to wait for a forked fiber to complete, you can. Also, you can never guarantee that some arbitrary cleanup action will successfully complete; the user can force kill the JVM process or it can even crash on its own. We can only offer some confidence that they will be run in a timely manner.

> Do we imply that main Fiber should always join forked Fibers?

I think this is an application-specific concern. We should try to make as few assumptions as possible about how users will use ZIO. 

> Even with this solution, the app keeps spawning new threads. After 3 minutes I had like 1200 Java Threads running on the JVM. This defies the purpose of fibers IMHO.

@pierangeloc Yeah, unbounded pool was a bad idea. :( I originally had a fixed thread pool but got swayed by many varying concerns.

**Comment by pshirshov** [comment]
> Yeah, unbounded pool was a bad idea.

I said that unbound pool or unbound queue aren't great at all. RN zio has a broad choice of crappy heuristics and there is no good way to address the problem except of task separation.

**Comment by jdegoes** [comment]
> Even with this solution, the app keeps spawning new threads. After 3 minutes I had like 1200 Java Threads running on the JVM. This defies the purpose of fibers IMHO.

I agree this is a problem. Unfortunately the change to default thread pool solved some real problems at the cost of others. It was a fast change, but a real change involves separating blocking IO as per @pshirshov's tickets.

**Comment by jdegoes** [comment]
@pierangeloc We should probably make `ExitStatus` handle this. That way if users use our `App`, they have to be explicit about what they want to happen when the main fiber ends.

**Comment by NeQuissimus** [comment]
Threw this into 1.0.0. I just ran into the same issue of semantics changing.

**Comment by regiskuckaertz** [comment]
Just ran this with the latest master and it's now running forever. Can we close this ticket and move the discussion over [there](#248 )?

**Comment by jdegoes** [comment]
@regiskuckaertz Sounds good! 👍 

Thanks for doing all this housecleaning. 😆
