### ISSUE TITLE
Write test suite for RefM

### ISSUE THREAD

**Issue by karolchmist** [scalaz/scalaz-zio#321]
RefM currently has no test suite. It should have a test suite similar to `RefSpec`.

**Comment by saucam** [comment]
I can take this one

**Comment by karolchmist** [comment]
It's in PR *https://github.com/scalaz/scalaz-zio/pull/322), I need to fix linting check

**Comment by saucam** [comment]
oh ok !

**Comment by karolchmist** [comment]
But if you see some possible improvements, please contribute as well :)
