### ISSUE TITLE
Make failure / error terminology consistent across zero

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#330]
### V2 proposal 

An `IO[E, A]` / `Fiber[E, A]` either fails for some `Cause[E]`, or returns an `A`.

 - **Failure** — Any means by which a program may fail, including:
    - _Failure due to interruption_
    - _Failure due to unchecked error_
    - _Failure due to checked error_
    - _Failure due to interruption_
 - **Checked Error** — A statically-typed error value. 
    Examples:
     - The `E` in `Either[E, A]`
     - The `E` in `IO[E, A]`
 - **Unchecked Error** — A dynamically-typed error value that extends `Throwable` and is thrown. There are several sources for unchecked errors:
     - _Exception thrown from main code_. For example: `myIO.map(throw new Error)`
     - _Exception thrown from finalizer_. For example: `myIO.ensuring(IO.point(throw new Error))`
 - **Exception** — An exception is an alternate name for _unchecked error_.
 - **Interruption** — A user-initiated (normal) early termination of a fiber before it has computed its result.

**Comment by jdegoes** [comment]
### V2 proposal 

An `IO[E, A]` / `Fiber[E, A]` either fails for some `Cause[E]`, or returns an `A`.

 - **Failure** — Any means by which a program may fail, including:
    - _Failure due to interruption_
    - _Failure due to unchecked error_
    - _Failure due to checked error_
 - **Checked Error** — A statically-typed error value. 
    Examples:
     - The `E` in `Either[E, A]`
     - The `E` in `IO[E, A]`
 - **Unchecked Error** — A dynamically-typed error value that extends `Throwable` and is thrown. There are several sources for unchecked errors:
     - _Exception thrown from main code_. For example: `myIO.map(throw new Error)`
     - _Exception thrown from finalizer_. For example: `myIO.ensuring(IO.point(throw new Error))`
 - **Exception** — An exception is an alternate name for _unchecked error_.

/cc @regiskuckaertz

**Comment by regiskuckaertz** [comment]
Add

- **Interruption** — A user-intended abortion of the enclosing action

?

**Comment by regiskuckaertz** [comment]
It really feels like things are coming together.

**Comment by jdegoes** [comment]
@regiskuckaertz Added. Also I vote for removing the interruption `Throwable`. We say interruption is never accompanied by a `Throwable`. Makes it more consistent and this is the way it's used in practice, anyway.

**Comment by regiskuckaertz** [comment]
Yes 👍 Interruption itself is the reason.

**Comment by jdegoes** [comment]
@regiskuckaertz The other think I'm thinking about is changing `Completed` to `Returned`. This way, a fiber either _failed_ with some cause or _returned_ a value. `Complete` is quite broad. A fiber that failed is also "completed" in some very real sense.

**Comment by regiskuckaertz** [comment]
I now realise that is the same vocabulary as in `scala.util.Try`, but I think _they_ got it wrong 😜

**Comment by jdegoes** [comment]
That works. Maybe just shorten to Failure and Success (present tense versus past).
