### ISSUE TITLE
Add 2 more tests to SemaphoreSpec

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#339]
These tests should be [inspired by and credit @mpilquist's work on Cats-Effect `Semaphore`](https://github.com/typelevel/cats-effect/pull/403/commits/0970f0f52c0d4410e329bc044888f23e4ed611a7).

**Comment by edvmorango** [comment]
I'm writing these tests, but I have a doubt:

```
    val n = 0L
    unsafeRun(for {
      s <- Semaphore(n)
      _ <- s.withPermit(s.release)
                .timeoutFail(new Exception("timeout"))(1.milli).attempt *> s.release
      permits <- s.release *> IO.sleep(10.millis) *> s.available
    } yield permits must_=== 1L)
```
 ```withPermit```  is ignoring the ```timeoutFail``` and blocking until get a ```acquire```  is this the expected behaviour?

**Comment by regiskuckaertz** [comment]
@edvmorango this is a sneaky one 🐍 `s.withPermit(action)` reduces to
```scala
IO.bracket(acquire)(_ => release)(_ => action)
```
and that's wrong, because `acquire` won't be interruptible (that is the guarantee given by `IO.bracket`), which explains why you experience the blocking behaviour. The fix requires a weaker version of `bracket`, so to speak, one where `acquire` would be interruptible. What about this:
```scala
def withPermit[E, A](task: IO[E, A]): IO[E, A] =
  Ref(false).flatMap { ref =>
    (for {
      _ <- acquire.ensuring(ref.set(true))
      a <- task
    } yield a).ensuring(IO.whenM(ref.get, release))
  }
```

**Comment by regiskuckaertz** [comment]
Hrm, no, sorry, the line
```scala
acquire.ensuring(ref.set(true))
```
is wrong. I need a few minutes.

**Comment by jdegoes** [comment]
@regiskuckaertz 

I don't think that version will be correct.

I think you have to adopt a similar approach to [Cats-Effect `Semaphore`](https://github.com/typelevel/cats-effect/pull/403/files): an internal acquire action produces the "promise getter" and the "cleanup action".

Then in `withPermit`, you bracket that (the internal acquire), and in the use action you "get" and in the release action you "cleanup". The cleanup action now has to decide what action to do based solely on the state of the `Semaphore`.

Since the internal acquire doesn't actually block to get the permit, this allows you to provide an interruptible acquisition (because what it's really interrupting is the `promise.get`, and the cleanup action takes care of whether or not to release).

**Comment by regiskuckaertz** [comment]
> I don't think that version will be correct.

What exactly? I tested it with the exact same test used in the cats-effect project and it worked correctly.

I looked into their solution (`sys.error` 😱). [The fix for `acquireN`](https://github.com/scalaz/scalaz-zio/pull/354#pullrequestreview-171893414) is pretty much going in that direction, but it would require getting rid of `Promise.bracket` to be able to extract an `acquireNInternal`. Somehow it does not feel as elegant. I also have tested my fix for `acquireN` with their test.

**Comment by jdegoes** [comment]
@regiskuckaertz 

For one, `withPermit` will not release the permit if `task` executes.

It might not be necessary to extract out `acquireNInternal`. But rather to make sure that the cleanup action is aware the acquisition could have succeeded (or not), and must undo the effects in the event of failure.

**Comment by regiskuckaertz** [comment]
I don't see my mistake 🤔 especially if `task` executes, then the `ref.get` will yield `true` and so `release` will get evaluated; this is guaranteed with `ensuring`. I tried it against Michael's test:
```scala
    unsafeRun(Semaphore(0L).flatMap { s =>
      // The inner s.release should never be run b/c the timeout will be reached before a permit
      // is available. After the timeout and hence cancelation of s.withPermit(...), we release
      // a permit and then sleep a bit, then check the permit count. If withPermit doesn't properly
      // cancel, the permit count will be 2, otherwise 1
      s.withPermit(s.release).timeout(1.milli).attempt *> s.release *> IO.sleep(10.millis) *> s.count
    }) must_=== 1L
```

**Comment by regiskuckaertz** [comment]
I've been able to make it fail once, so it definitely is wrong, I just don't see where. Anyway, let's move on to the proper solution then.

**Comment by edvmorango** [comment]
@regiskuckaertz When I write tests, sometimes I have problems using ```timeout```  functions, maybe is the same with your tests.

**Comment by jdegoes** [comment]
@regiskuckaertz You're right, I was reading it wrong.

The problem is that `acquire` can be interrupted after it's changed the state of the `Ref`, but before it returns (there's a `flatMap` or two in there after the state change). It's a very small window but if it's interrupted then, it will have been acquired and not yet released.

You can see it more clearly if you imagine the implementation of `acquire` to be something like:

```scala
val acquire = 
  for {
    ...
    _ <- ref.update(...)
    ...
  } yield ...
```

If it's interrupted anywhere after the ref update, then big trouble. This means the cleanup action has to look into the ref to see "what really happened", i.e. did the state change or not. Then it's OK to interrupt it.

**Comment by regiskuckaertz** [comment]
@jdegoes Thanks for the detailed explanation, I now see where my assumptions were incorrect. I've posted a draft version of Michael's fix in the PR thread, hope it helps @edvmorango !
