### ISSUE TITLE
Keep track of distinction between interruption and defect termination

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#341]
Currently we have only `ExitResult.Terminated`, which obscures the distinction between different types of termination:

 * Terminated due to interruption.
 * Terminated due to fatal error.

To solve this problem, we should do the following:

1. Add more cases to `ExitResult` that precisely capture the possible scenarios.
    ```scala
    trait ExitResult[+E, +A]
    object ExitResult {
      final case class Completed[A](value: A) extends ExitResult[Nothing, A]
      final case class Failed[E](error: E, defects: List[Throwable]) extends ExitResult[E, Nothing]
      final case class Interrupted(causes: List[Throwable], defects: List[Throwable]) extends ExitResult[Nothing, Nothing]
      final case class Fatal(defect: Throwable, defects: List[Throwable]) extends ExitResult[Nothing, Nothing] // Basically NonEmptyList[Throwable]
    }
    ```
2. Rename `terminate`: `IO.terminate` => `IO.fatal(t: Throwable)`, including all helpers.

This supersedes #169 and may block #267.

**Comment by kaishh** [comment]
- on rename, this will break most of the code written in ZIO and subjectively, I like current name better, being a verb that carries the semantic of unrecoverable termination

**Comment by ghostdogpr** [comment]
I had a shot at this: #342
