### ISSUE TITLE
Improve fromFuture in interop package

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#347]
Currently the signature has this type:

```scala 
IO.fromFuture[A](ftr: () => Future[A])(ec: ExecutionContext): IO[Throwable, A]
```

We should change to:

```scala 
IO.fromFuture[A](ftr: IO[Throwable, Future[A]])(ec: ExecutionContext): IO[Throwable, A]
```

Because in general the construction of a future is an effect, and rather than sticking it into a thunk (like we're doing now), we should probably be just sticking it into `IO`.

There will be `future.unsafeToIO` if people really want that.

**Comment by kaishh** [comment]
We already have this exact function in interop.Task.fromFuture

**Comment by jdegoes** [comment]
@kaishh It seems like the package is not consistent in where it places things (sometimes on the `IO` companion object, sometimes on the `Task` companion object).

**Comment by hepin1989** [comment]
Shouldn't be a call by name？
