### ISSUE TITLE
bracket0 breaks when cancelled

### ISSUE THREAD

**Issue by RaasAhsan** [scalaz/scalaz-zio#351]
```scala
def print(msg: String): IO[Nothing, Unit] =
    IO.sync(println(msg))

  new RTS {}.unsafeRun {
    for {
      p1    <- Promise.make[Nothing, Unit]
      p2    <- Promise.make[Nothing, Unit]
      f     <- print("acquired").bracket0[Nothing, Unit]((_, _) => print("released"))(_ => p1.complete(()) *> p2.get).fork
      _     <- p1.get
      _     <- f.interrupt
      _     <- IO.never
    } yield ()
  }
```

Output is:
```
acquired
```

There should also be a released in there. If you change the `bracket0` to `bracket`, the output is correct:
```
acquired
released
```

I'm going to try to find out what's going on here and attempt a fix, but please do let me know if you know why this is happening!

**Comment by RaasAhsan** [comment]
I think I've figure out why release isn't being called. The whole ensuring finalizer is being run, but the fiber that was forked to run `use` hasn't been completed, so it can't observe the `ExitResult` of it and tries to interrupt the `use` fiber, but never calls `release`.

Should the `tryObserve` `None` case invoke `release` w/ a `ExitResult.Terminated` after running `interrupt` on the fiber?

**Comment by jdegoes** [comment]
@RaasAhsan 

I think this code:

```scala
        case (a, f) =>
          f.tryObserve.flatMap {
            case Some(r) => release(a, r)
            case None    => f.interrupt
          }
```

is wrong and should be:

```scala
        case (a, f) =>
          f.interrupt *> f.observe.flatMap(release(a, ))
```

The reason is that the `f.join` will be interrupted, but not the inner forked fiber; so the finalizer will be run before the inner forked fiber exits.

/cc @regiskuckaertz

**Comment by regiskuckaertz** [comment]
That makes sense 🙌
