### ISSUE TITLE
Add `IOUnit` type synonym

### ISSUE THREAD

**Issue by regiskuckaertz** [scalaz/scalaz-zio#358]
There's shy of 100 occurrences of `IO[Nothing, Unit]` in the library, as it represents such a large subset of effects. I'd like it to be as easy to type as `IO.unit`:
```scala
IO.unit : IOUnit
```
Opinion?

**Comment by kaishh** [comment]
How about `UIO[Unit]`?

**Comment by regiskuckaertz** [comment]
Ha, [we had that previously](https://github.com/scalaz/scalaz-zio/pull/127), it was discarded because the alias was neither shorter nor self-explanatory enough.
