### ISSUE TITLE
Implement composable RTS

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#36]
```scala
sealed abstract class ThreadPool extends Serializable
object ThreadPool {
  def fromExecutorService(e: ExecutorService): ThreadPool = ???
  def fromExecutionContext(e: ExecutionContext): ThreadPool = ???
}

private[zio] trait ZioThreadPool extends ThreadPool {
  def concurrency: Int
  def capacity: Int 
  
  // Metrics
  def size: Int
  def enqueuedCount: Int 
  def dequeuedCount: Int

  def submit(runnable: Runnable): Boolean
  def shutdown(wait: Duration): Unit
  def shutdownNow: Unit
}

case class Environment(
  unhandled: Cause[Any] => IO[Nothing, Unit], 
  threadPool: ThreadPool)

trait RTS {
  def unsafeRun[E, A](env: Env)(io: IO[E, A]): A
  def unsafeRunSync[E, A](env: Env)(io: IO[E, A]): ExitResult[E, A]
  def unsafeRunAsync[E, A](env: Env)(io: IO[E, A], f: ExitResult[E, A] => Unit): Unit
}
```

**Comment by ktonga** [comment]
Hey @jdegoes I'll take a stab at this if you don't mind.

I want to cut a first release but I think a shift-like feature is a must for many people and since you mentioned this was related...

Would you tell me at least in a paragraph what you have in mind for it so I can get started?

Thanks!

**Comment by jdegoes** [comment]
@ktonga This is not a simple ticket.

First off, `shift` can be implemented in `interop` already using `async` (and probably should).

Second, we need the facility to have a pure construct representing a thread pool, and to run fibers on it, and combine these into larger things, and so forth.

`fork` is a natural place for it, `io.forkOn(rts)`. How to do this without modules (since the type of `RTS` is unknown) is part of the problem. Or perhaps everything should be modularized...

**Comment by artempyanykh** [comment]
I'm thinking about ZioThreadPool and the signature `submit(thunk: () => Unit): Unit` implies that submitting a task is always successful (i.e. there's a place in the queue or the caller blocks until there is).

Maybe something like 
```scala
offer(thunk: () => Unit): Boolean
```
would be a fairer choice? Then the caller can choose whether they want to busy spin, sleep, block (blocking will need some additional machinery) or choose some other strategy while waiting for the place.

**Comment by jdegoes** [comment]
@artempyanykh I agree. It makes the system more composable.

**Comment by jdegoes** [comment]
As can be seen in #132, a key property of the RTS must be enabling users to run computation on a given RTS with a fixed capacity, so you can achieve deeply composable throttling, rather than just ad hoc throttling for all possible function variants.

**Comment by jdegoes** [comment]
This one is the tricky one:

```scala
def submit(runnable: Runnable): Boolean
```

To implement composable throttling, we have to have back pressure on submission. The only way to do that with the above signature is to block. Which is not ideal.

I wonder if we could extract out a "pure" thread pool that has signatures like this:

```scala
def submit(runnable: IO[Any, Any]): IO[Nothing, Boolean]
```

Then we can "suspend" submissions, which allows us to quite easily due composable throttling.

This has some obvious bootstrapping problems but perhaps they can be solved somehow...
