### ISSUE TITLE
Improve and refine composite operations with the new Redeem/Fail

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#360]
With #342 about to land, a number of times `fork` is used to implement various operations can be reduced, because it is now possible to directly observe the result of executing a fiber.

 - [ ] **ADDITION** — Add a new operation (`io.redeem0`?) that has the full power of `Redeem`.

    ```scala
    trait IO[E, A] {
      ..
      final def redeem0[E2, C](err: Cause[E] => IO[E2, C], succ: A => IO[E2, C]): IO[E2, C] = ???
      ..
    }
    ```
 - [ ] `io.raceWith` — There are possibly 2 unnecessary instances of `fork` that use `observe`; these can be replaced by `run` on the `left` / `right`, which can `flatMap` to the `arbiter` right before they are forked
 - [x] `io.run`  — This no longer needs to use `fork`, but can instead directly use `redeem0` to generate the `ExitResult`.
 - [ ] `io.sandbox` — This currently goes through run, but it will be much faster to use `redeem0` directly.

Unfortunately, I don't think `bracket0` can be done without `fork`.

**Comment by kaishh** [comment]
Hmm, `.runSync` version of `.bracket0` worked fine for me in previous PR; at least it passed the testsuite. Will check again with `Redeem`.

**Comment by ghostdogpr** [comment]
About `raceWith`, how can we avoid using `fork` on left/right since the finishers require fibers as parameters?

I submitted #369 for the rest.
