### ISSUE TITLE
Ensure interruption is not catchable

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#363]
With the unified failure model, we need to ensure that interruption is not catchable.

Currently, the RTS cannot "forget" a request to perform interruption and will interrupt at the earliest possible opportunity, but I'm not actually sure what happens in all circumstances. In particular, it may be possible to appear to "catch" an interruption and recover although later be interrupted.

If `run` does not "catch" interruption, then the only way to do that would be to fork a fiber and observe the result. This might affect #360, necessitating a few more forks than otherwise necessary.

/cc @kaishh @regiskuckaertz

**Comment by kaishh** [comment]
`run` did not catch interruption previously - just passed it along with supervised. I think let's wait until runWith/ConcurrentEffect are finished and see if we can't come up with a solution that doesn't require catching interruption – in that case run semantics need not change and we don't expose a 4-state error model :^). We can already install post-mortems on individual closures with `.onTermination` and `.supervised`, that may be enough.

**Comment by kaishh** [comment]
OTOH it would be impossible to implement performant .bracket0, .onTermination, etc. without catching interruption

**Comment by kaishh** [comment]
Related: Seems like [`IO.to`](https://github.com/scalaz/scalaz-zio/blob/master/core/shared/src/main/scala/scalaz/zio/IO.scala#L722) will silently not fulfil a promise when it's interrupted, right now, because `.run` won't return on interrupt.

**Comment by regiskuckaertz** [comment]
@kaishh good catch (bad pun 😅)! I've just addressed that [here](#462 ).

**Comment by jdegoes** [comment]
Closed by #462.
