### ISSUE TITLE
Queue performance improvements

### ISSUE THREAD

**Issue by ghostdogpr** [scalaz/scalaz-zio#368]
Here are some ways we could improve the performance of Queue:

- [ ] Stop using `queue.length` or `queue.size` as it's a O(n) operation. One way would be to maintain the queue size ourselves since we know exactly how many items we add or remove.
- [ ] Stop using `queue.splitAt` (also O(n) op). It seems to me that calling `dequeue` multiple times would be faster as we would only go through the number of items we want and not the whole list. For example currently `takeUpTo(1)` causes a `splitAt` which runs through the whole list when we only need to get the first element.

**Comment by wi101** [comment]
Sounds good :) , I think for the second point, we can implement our `splitAt` using a better implementation to browse the `Queue` and `Iterable`

**Comment by wi101** [comment]
And we can use `RingBuffer` no idea about it, but I saw a PR
cc @artempyanykh

**Comment by ghostdogpr** [comment]
@regiskuckaertz nice suggestions! I’ve been observing as well that we always execute some unnecessary steps that are only needed with the back pressure strategy. The impact is currently lower than size/splitAt but still exists. 
On top of that, the code is getting too complicated when mixing all the cases so pushing logic to the strategy sounds good. 

I’ll fiddle with your idea 👍

**Comment by jdegoes** [comment]
The most significant improvement will come by using a lock-free buffer to back the queue. @artempyanykh should be able to help here, he's already done a good chunk of the work (#259).

Until then, I'd do some "low hanging fruit" optimizations that can make the current implementation perform better. However, it won't be high-performance until it uses a buffer.

**Comment by jdegoes** [comment]
@ghostdogpr As far as I know, it will be portable or mostly portable. /cc @artempyanykh 

Worst case we would just create one with a duplicate API but simpler implementation for Javascript.

**Comment by ghostdogpr** [comment]
Indeed from what I can see, we only use Java's `AtomicLong`, `AtomicLongArray` and `ConcurrentLinkedQueue` and they seem all supported by ScalaJS: https://github.com/scala-js/scala-js/tree/master/javalib/src/main/scala/java/util/concurrent

So I guess we can safely move the code to `shared`.

**Comment by artempyanykh** [comment]
@ghostdogpr thanks 😃 

Right, I was specifically avoiding `Unsafe` to keep the impl. portable. However, the patch I'm working on right now that brings substantial perf improvement in concurrent scenario on JVM requires `AtomicLongFieldUpdater` which currently seems to be missing in scala-js.

Not sure if there are any fundamental reasons `A*FU` classes are absent scala-js. Opened a ticket https://github.com/scala-js/scala-js/issues/3496

**Comment by artempyanykh** [comment]
Oh, and one more thing --

**Comment by artempyanykh** [comment]
Apparently, `A*FU` classes can't be implemented in scala-js. I'll go with a separate JVM impl in my patch then.

**Comment by ghostdogpr** [comment]
I started playing with `RingBuffer` and realized my tests failed because the capacity was higher than the requested one, which is intended for performance reasons.

I was initially relying on the result of `offer` to apply if needed the appropriate sliding/dropping/backpressure strategy. If we can't rely on it (currently, a queue of capacity 3 will let you add 4 items), it means we need to check the queue size and compare it with the desired capacity in order to apply the proper strategy. To avoid concurrent calls changing the size in the middle of this, it means we need to have that logic contained within an atomic function such as `Ref.modify`, which means we aren't really using the RingBuffer in a concurrent way (at least for `offer`).

Any thoughts about it? Is the performance gain of being not strict about the capacity of RingBuffer worth limiting concurrency (while also making the reasoning a bit more complex)?

**Comment by jdegoes** [comment]
@ghostdogpr 

This will be a large refactoring to `Queue`. In particular, the `RingBuffer` will be an ordinary `val` inside the `Queue`. We will need at least one `RingBuffer` for the values `A`, but possibly another one for callbacks. The logic will be quite tricky and careful thought must be used to ensure we don't accidentally suspend a taker when a value is available (example: poll value queue, if empty, push callback on callback queue, then check again the value queue).

The goal should be to eliminate or at least minimize the use of `Ref`, because that will be a bottleneck, and to get away from using immutable data structures such as Scala's immutable queue.

**Comment by artempyanykh** [comment]
@ghostdogpr re: queue size -- it's possible to drop the power of 2 requirement, but the result would be around 15% hit in max throughput IIRC. Still, -15% shouldn't be as much as when using some external strategy e.g. `Ref.modify`. 

So, if arbitrary sized queues is a must, then I'd do the change in the `RingBuffer`.

**Comment by jdegoes** [comment]
I don't think arbitrary queue size is necessary. Power of 2 is fine. We'll just have to update tests, and make sure it's labeled `requestedCapacity`, but that the returned `capacity` may be different.

**Comment by ghostdogpr** [comment]
@artempyanykh I think `isFull` is wrong. If you create a `RingBuffer` with capacity 2, then offer 1 item, `isFull` returns `true`.
If I remove `- 1` in `head.get() + capacity - 1` it works OK. Or did I miss something?

**Comment by artempyanykh** [comment]
@ghostdogpr nope, you're right, that's a bug :)
