### ISSUE TITLE
Create optimized version of RingBuffer for Scala.js

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#393]
The Scala.js implementation of `RingBuffer` (`/core/js/src/main/scala/scalaz/zio/internal/`) is unnecessarily complicated, because all code in Javascript is single-threaded. Therefore, the implementation can use a simple array and ordinary mutable values, without use of any atomic facilities or volatile variables.

**Comment by mijicd** [comment]
I'll take care of this one.
