### ISSUE TITLE
Split out interop into three modules

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#394]
Currently, the `interop` module holds `cats`, `scalaz72`, and `future` interop packages.

These should be split up into three top-level interop modules:

```
/interop-cats/
/interop-future/
/interop-scalaz7x/
```

This will allow three to evolve independently and provide clearer and more useful code organization.

**Comment by hepin1989** [comment]
Let me take it.

**Comment by ghostdogpr** [comment]
Closed by #408
