### ISSUE TITLE
Grab latest changes from scalaz/scalaz series/8.0.x

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#4]
This includes but is not limited to:

 - [x] `IOQueue`
 - [x] `IOQueueSpec`
 - [x] `IORefSpec`
 - [x] `KleisliIO`
 - [x] `KleisliIOSpec`
 - [x] `PromiseSpec`

And miscellaneous bug fixes and helpers added to `IO`, `RTS`, etc.

**Comment by ktonga** [comment]
Yup. That was the plan :+1:

**Comment by jdegoes** [comment]
More stuff is coming in tomorrow.

**Comment by ktonga** [comment]
Closed by #17
