### ISSUE TITLE
Not all v0.4 packages made it to Maven

### ISSUE THREAD

**Issue by regiskuckaertz** [scalaz/scalaz-zio#403]
Looks like only 2 packages were successfully uploaded 🤔

<img width="911" alt="screen shot 2018-11-30 at 20 54 22" src="https://user-images.githubusercontent.com/629976/49314256-c1244a00-f4e1-11e8-9c63-b4f4dae3bc5a.png">

**Comment by NeQuissimus** [comment]
https://travis-ci.org/scalaz/scalaz-zio/jobs/461842863

There were actually Scaladoc failures that caused this.
