### ISSUE TITLE
Change signature of Promise.poll 

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#419]
Currently, `promise.poll` has this signature:

```scala
def poll: IO[Unit, ExitResult[E, A]]
```

However, other `poll` methods are trending toward `Option`, so we should change this to be consistent:

```scala
def poll: IO[Nothing, Option[ExitResult[E, A]]]
```

You can find `Promise.scala` in `/shared/src/main/scala/scalaz/zio/Promise.scala`.

**Comment by Vilkina** [comment]
I'm working on this issue

**Comment by regiskuckaertz** [comment]
I'm a bit sad we're not going in the opposite direction, I liked the `Alternative`-style this permitted.

**Comment by jdegoes** [comment]
@regiskuckaertz I'm open to that! We just need to pick one style and stick to it. 😄 

The convention could be: _in any case where a result is optional and the returned `IO` cannot fail for other reasons, then the optional result should be encoded as a `Unit` error_.

I agree that doing `p.poll <> io` is quite convenient.

Can you write up this change in more depth so @Vilkina can catch all the places where we should convert to the `Unit` style?

**Comment by regiskuckaertz** [comment]
@jdegoes yes, tomorrow as today was Christmas party and I’m a bit 🥳🥴🤢

**Comment by jdegoes** [comment]
@regiskuckaertz No worries, enjoy your Christmas parties. 😆 🎉

**Comment by Vilkina** [comment]
Three weeks before Christmas. Anyway, you can go to the gym or drink some more for beating hungover. But don't drink alcohol in a gym, @regiskuckaertz :)

**Comment by regiskuckaertz** [comment]
@Vilkina 

> Three weeks before Christmas

I know 😆

**Comment by regiskuckaertz** [comment]
Ok, so in terms of `poll`, there's just `Fiber#poll` to turn into
```
def poll: IO[Unit, ExitResult[E, A]]
```
with similar changes in `RTS` and `interop.future.FiberObjOps`. The pattern of producing an `IO[Nothing, Option[A]]` appears in several other places, but I don't know whether they should all be updated:

- `FiberLocal#get`: one could argue that the current behaviour does not follow the idiom in Scala collections where `get` may fail and `getOption` produces an `Option[A]`. Perhaps we could do the same here.

- `system.env(variable)`: that one I don't think should be changed

- `FiberContext#unwindStack`: first off, I think the following line
```scala
f0.finalizer.sandboxed.redeemPure[Nothing, Option[Cause[Nothing]]](Some(_), _ => None)
```
can be improved, as we have two `redeem0` ops in sequence where one is enough. Then if we change it to `IO[Unit, Cause[Nothing]]`, we can rewrite:
```scala
doNotInterrupt(finalizer).map(io.cause ++ _) <> IO.now(io.cause)
```
and perhaps `zipCauses` can go away. The combination of finalizers gets more complex though. I don't know, what do you reckon @jdegoes ?

**Comment by sideeffffect** [comment]
for what it's worth, I liked the old one `def poll: IO[Nothing, Option[ExitResult[E, A]]]` better -- `poll` should behave like little peek if that thing has finished -- and that thing not being finished should be normally expected, it shouldn't be an erroneous exceptional scenario => thus `Option` instead of `fail` (`raiseChecked` maybe soon)

**Comment by regiskuckaertz** [comment]
> it shouldn't be an erroneous exceptional scenario 

imho, that is not the case. We talk about "checked errors" but that's purely a convention, the quantification on `E` is universal, like `Either e a`.

**Comment by sideeffffect** [comment]
> purely a convention

yeah, I get that, it's just that I like to follow the convention closely
thus in my mind:

```scala
poll: IO[Nothing, Option[ExitResult[E, A]]]
get: IO[Unit, ExitResult[E, A]]
```

my 2 ¢

**Comment by jdegoes** [comment]
@sideeffffect What are some use cases you're thinking of? We can see how hard it is to solve them using both approaches.

`IO[Nothing, Option[ExitResult[E, A]]` is a (bi) functor in a functor in a (bi) functor. It can be a little awkward to work with. `IO[Unit, ExitResult[E, A]]` is just a bifunctor in a bifunctor. One less level of nesting. Which can make it a little easier.

Maybe. We need use cases. 😄

**Comment by sideeffffect** [comment]
:D
![image](https://user-images.githubusercontent.com/9019485/50285982-312d4c80-045e-11e9-8eaf-0a0c0c25acb5.png)

let me answer with a question:
I see a value having all 3 methods on `Promise`
```scala
(1): IO[Nothing, Option[ExitResult[E, A]]]
(2): IO[Unit, ExitResult[E, A]]
(3): IO[E, A]
```
would you agree with that?

if so, how would you like to name them? I would suggest
 1. `poll`
 2. `get`
 3. `await`

and you're suggesting
 1. `pollOption`?
 2. `poll`
 3. `await`

did I get that right?

**Comment by jdegoes** [comment]
How about:

We could also just have (1) `poll` and (3) `await`, and then add a method:

```scala
trait IO[+E, +A] {
  def get[B](implicit ev1: E =:= Nothing, ev2: A =:= Option[B]): IO[Unit, B]
}
```

You could imagine `left` and `right` variants too.

Then you could do `poll.get` for the `Unit` erring variant.

**Comment by regiskuckaertz** [comment]
Oh sweet, yeah I like that!

**Comment by sideeffffect** [comment]
> ```scala
> trait IO[+E, +A] {
>   def get[B](implicit ev1: E =:= Nothing, ev2: A =:= Option[B]): IO[Unit, B]
> }
> ```

I've implemented this as an extension method over at https://github.com/scalaz/scalaz-zio/pull/469

**Comment by sideeffffect** [comment]
or do you think the `implicit ev1: E =:= Nothing` approach is better?
I myself am not very sure...

**Comment by jdegoes** [comment]
@sideeffffect It's fine either way. Since we're using the syntax pattern, let's stick with that.

The main advantage of the method style is that it is always there (easy to find for IDEs) and has good error messages. But if we want to do that, we should be consistent and port over the relevant syntax ones.

**Comment by sideeffffect** [comment]
@jdegoes cool, let's deal with it in another ticket: https://github.com/scalaz/scalaz-zio/issues/489

**Comment by ghostdogpr** [comment]
Closing as `poll` not returns an `Option`.
