### ISSUE TITLE
Add trampolining to Stream

### ISSUE THREAD

**Issue by iravid** [scalaz/scalaz-zio#428]
Currently, `Stream` has a single abstract method:
```scala
trait Stream[+E, +A] {
  def foldLazy[E1 >: E, A1 >: A, S](s: S)(cont: S => Boolean)(f: (S, A1) => IO[E1, S]): IO[E1, S]
}
```

Stream is currently not stack-safe. This issue consists of several parts:
1. Add stack-safety tests on Stream (specifically - left and right associated binds, left and right associated concatenations)
2. Change Stream.fold to use the following signature:
```scala
object Stream {
  type Fold[E, A, S] = IO[Nothing, (S, S => Boolean, (S, A) => IO[E, S]) => IO[E, S]]
}

trait Stream[+E, +A] {
  def fold[E1 >: E, A1 >: A, S]: Fold{E1, A1, S]
}
```
and verify that the stack-safety tests pass afterwards.
3. Run the benchmarks with and without the trampolining to measure the impact on performance.

**Comment by mijicd** [comment]
I'd like to work on this.

**Comment by iravid** [comment]
Thanks @mijicd!
