### ISSUE TITLE
Stream.fromQueue should end when the Queue is shutdown

### ISSUE THREAD

**Issue by iravid** [scalaz/scalaz-zio#441]

**Comment by ghostdogpr** [comment]
@jdegoes isn't it possible that we still want to use the queue even if the stream ends? e.g. to do a clean shutdown, I stop the stream then `takeAll` to save the remaining queue items somewhere.

**Comment by ghostdogpr** [comment]
@iravid I'm still discovering the stream semantics, maybe you can help me here. How do you end a stream? Can I just catch this by checking `cont`?

**Comment by iravid** [comment]
Once the Stream's `foldLazy` starts, it can only stop from "inside" (unless of course you fork and interrupt it). The usual strategy is to pass in an `f` and `cont` that will stop when needed.

E.g., carry a boolean inside `S` and check that boolean in `cont`.

Does that help?

**Comment by ghostdogpr** [comment]
@iravid thanks! I added `queue.shutdown` when `cont` is `false` to the PR.

**Comment by jdegoes** [comment]
@ghostdogpr Possibly, it should be an option to `shutdown`? Or maybe if you shut down a queue, it should allow the surplus to be taken before rejecting new attempts?

**Comment by ghostdogpr** [comment]
@jdegoes I think making it optional leaves the most flexibility for the user, they can decide if they want to keep using their queue or not. I'll add it.
