### ISSUE TITLE
Should Interrupted be a term of ExitResult rather than Cause?

### ISSUE THREAD

**Issue by iravid** [scalaz/scalaz-zio#444]
Currently `redeem0` has a continuation of type `Cause[E] => IO[E2, B]`, however this implies that `redeem0` can recover from `Interruption`.

Does this mean that `Interruption` should be a subtype of `ExitResult`? @regiskuckaertz any insights on this?

**Comment by iravid** [comment]
Copying @jdegoes's response from #443 here:

> Cause perfectly describes how fibers fail right now, because interruption is a perfectly valid way for a fiber to fail.
>
> In fact, the situation is more nuanced than this, because Cause can be composite from many fibers; some of which may have been interrupted, others of which may have failed for specific reasons.
> 
> Even more complicated, during the process of interruption, finalizers may throw unchecked errors, which means the cause is multi-factoral and must reflect both the interruption and the unchecked errors.
> 
> All of this is losslessly and precisely encoded with Cause. So it's a good bet that's not changing. 😆
> 
> The only "strange" thing is that when you call redeem, you think you might be able to handle Cause.Interrupted. But you can't really recover from interruption, by design (it's a simple change to make, but we decided against it). Anywhere else where you see a Cause, it's quite possible it's Cause.Interrupted (or contains a Cause.Interrupted, anyway).

That makes sense, but I'm wondering why is interruption classified as failure?

**Comment by iravid** [comment]
To clarify - I don't have an opinion on whether interruption should be recoverable or not, just that `redeem0` shouldn't trick us into thinking that ;)

**Comment by iravid** [comment]
Ok, I locally tried moving `Interruption` up to `ExitResult` and I see how that causes problems in `unwindStack` when coalescing the errors. You end up needing to represent composite failure causes differently as they need to also be able to represent interruption.

**Comment by jdegoes** [comment]
It's possible to introduce two type parameters into cause `Cause[I, E]`, then `Cause[Interrupted, E]` is interrupted but `Cause[Nothing, E]` would be not interrupted. I'm not sure if it's worth it, though, especially since we're not yet 100% sold on `redeem0` not allowing recovery from interruption.
