### ISSUE TITLE
Duration

### ISSUE THREAD

**Issue by NeQuissimus** [scalaz/scalaz-zio#450]
I would like to be able to do `10.seconds.toNanos` to emulate what I can do with the Scala/Java Duration class.

However, because `DurationSyntax` produces a `Duration` and not a `Finite`, there is no method `toNanos` available unless I pattern match on `10.seconds`.

I can see why `Infinite` does not have `toNanos` but it does make the syntax a bit hard to use in this case...

Edit: `toScalaDuration` and `toJavaDuration` would also be very useful!
Edit2: Why not allow negative durations?

**Comment by NeQuissimus** [comment]
Idea: Create a macro for `seconds`, `minutes` etc.
That should be able to return `Finite` for positive `Int` and `Duration` for negative `Int`, no?
Naturally, this only works at compile time, which is generally what these methods are used for anyways.

**Comment by jdegoes** [comment]
We could add `toNanos` and make it return `Long.MaxValue` for `Infinite`?

**Comment by NeQuissimus** [comment]
That would solve the issue but strictly speaking this would be incorrect.
