### ISSUE TITLE
Rename Stream.run to Stream.runWith ?

### ISSUE THREAD

**Issue by hepin1989** [scalaz/scalaz-zio#459]
It currently accepts a `Sink` as the parameter, `run` normally not take any parameter.

**Comment by jdegoes** [comment]
We use `runWith` for variants that accept a function, so that would not be appropriate here. It's very customary in FP for `run` methods to take a parameter (runReader, runState, etc.).

**Comment by hepin1989** [comment]
@jdegoes Thanks for the explanation.
