### ISSUE TITLE
leftFlatMap

### ISSUE THREAD

**Issue by NeQuissimus** [scalaz/scalaz-zio#487]
I have just found myself needing `leftFlatMap`. Was this a conscious decision to not include this function?

Here is my use case:

I have an `IO[E, A]` and would like to "get rid" of the `E`. I am doing this in my `RTS`, where I provide `run` with an `IO[Nothing, ExitStatus]`.
In my case, `type E = Throwable`, which I would like to log before returning an `ExitStatus.ExitNow(1)`.
So now I find myself with the following:

```scala

val work: IO[Throwable, Unit] = ???
def log: IO[Throwable, Unit] = ???

def run(): IO[Nothing, ExitStatus] = work
  .flip
  .flatMap((e: Throwable) => log(e))
  .flip
  .redeemPure(
    _ => ExitStatus.ExitNow(1),
    _ => ExitStatus.ExitNow(0)
  )
```

Clearly, the `.flip.flatMap.flip` chain is odd.
Am I missing some method that makes this easier?!

**Comment by regiskuckaertz** [comment]
`io.catchAll(log)`?

**Comment by jdegoes** [comment]
I'm not opposed to adding it. Note you can always do `io.flip.flatMap(f).flip`.

**Comment by NeQuissimus** [comment]
Yeah, that's what I did. Just seemed odd that I have to flip back and forth :)

**Comment by jdegoes** [comment]
We should have, at least, a combinator `flipWith`:

```scala
trait IO[E, A] {
  def flipWith[A1, E1](f: IO[A, E] => IO[A1, E1]): IO[E1, A] = f(self.flip).flip
```
