### ISSUE TITLE
Migrate from extension methods to implicit ev: A =:= B

### ISSUE THREAD

**Issue by sideeffffect** [scalaz/scalaz-zio#489]
Example:
```scala
trait IO[+E, +A] {
  def get[B](implicit ev1: E =:= Nothing, ev2: A =:= Option[B]): IO[Unit, B]
}
```
instead of
```scala
final class IOGetSyntax[A](val io: IO[Nothing, Option[A]]) extends AnyVal {
  def get: IO[Unit, A] = io.map(_.toRight(())).absolve
}
```

**Comment by NeQuissimus** [comment]
So is the idea to get rid of all the syntax extensions across ZIO?

**Comment by sideeffffect** [comment]
those that can be expressed with `implicit ev1: A =:= B` I suppose...

**Comment by jdegoes** [comment]
Yes, just those that can be expressed with implicit evidence. This will make the code more consistent and lead to better IDE auto-completion and better error messages.

**Comment by sideeffffect** [comment]
@jdegoes please include this in https://github.com/scalaz/scalaz-zio/issues/401

**Comment by leszekgruchala** [comment]
Couldn't methods like `IO.absolve/flatten/unsandbox/whenM/when` and their `*Syntax` counterparts also be moved to `trait IO` using the same pattern? Or do I miss something?

**Comment by sideeffffect** [comment]
@LGLO yep, looks good to me. thanks!
