### ISSUE TITLE
Start publishing releases. Deprecate scalaz/ioeffect

### ISSUE THREAD

**Issue by NeQuissimus** [scalaz/scalaz-zio#50]
1) Now that this properly exists, scalaz/ioeffect technically no longer needs to exist, does it?
2) Can we tag a release for ZIO, so people using scalaz/ioeffect can migrate onto a stable version?

**Comment by ktonga** [comment]
Not quite yet until I finish with #42

**Comment by jdegoes** [comment]
@ktonga Hurry, Gaston Kenobi, you're our only hope! 😉

**Comment by fommil** [comment]
One thing we should perhaps do, to avoid confusion in the future, would be to (hear me out) delete this repo (you backed up the tickets and the git repo, right?) and then rename `ioeffect` to `scalaz-zio`, then create a branch called `scalaz-ioeffect`, and force push **this** repo onto `master`. You'll have to start versioning from `v3.0.0` but that should be ok.

**Comment by ktonga** [comment]
Let me disagree with you on this one, Sam.

First of all and most importantly, this repo is already way more popular, it has (in order of importance) more external contributors, contributions, traffic, watchers and stars than the ioeffect one. This is important from a visibility and discoverability point of view for a new project that is trying to make it into a competitive ecosystem.

Secondly, ioeffect does not precisely enjoy of a lot of adoption, at least no one is using it in anger or in production. Trust me, ZIO got some important bug fixes that were not even reported in ioeffect.

Last but not least, let's stop underestimating our users :slightly_smiling_face:. I'm sure they will be able to figure out the differences between both ropos/projects, mostly based on the popularity of John's tweet announcing it as a brand new project with zero deps and being clearly the successor of the IO started within Scalaz.

**Comment by fommil** [comment]
Ok, we can just stick it into archive mode with a manual reference here.

**Comment by fommil** [comment]
Or push ioeffect onto a branch here...

**Comment by ktonga** [comment]
Yeah, I like that better.

**Comment by pshirshov** [comment]
Guys, it would be great if you start publishing releases. I've put zio into my production code though I have to depend on snapshot which is a dangerous practice :)

**Comment by ktonga** [comment]
We are working on it, JVM libs publishing is not necessarily a breeze. I'd recommend switch to source dependency in the meantime, it's way better than depending on a snapshot and sbt support for it is pretty decent.

**Comment by ktonga** [comment]
We recently had a few contributions to attempt start publishing non-snapshots versions but it's still not working. So if you say you can solve #172, please, be my guest :slightly_smiling_face: Help wanted!

**Comment by pshirshov** [comment]
I may, it all works, for example for my project. But I can't submit a complete P/R bcs in order to sign, for example I need to have PGP keys packed into an encrypted tar.gz and added into the repo.  

I have a short doc on secrets setup here: https://github.com/pshirshov/izumi-r2/blob/develop/doc/md/flow.md#secrets

**Comment by pshirshov** [comment]
To add POMs required by Sonatype you just need to add this snippet into primary `build.sbt`:

```
publishMavenStyle in ThisBuild := true
pomExtra in ThisBuild := <url>https://github.com/scalaz/scalaz-zio</url>
  <licenses>
    <license>
      <name>BSD-style</name>
      <url>http://www.opensource.org/licenses/bsd-license.php</url>
      <distribution>repo</distribution>
    </license>
  </licenses>
  <developers>
    <developer>
      <id>someone</id>
      <name>That Awesome Guy</name>
      <url>https://github.com/scalaz/scalaz-zio</url>
    </developer>
</developers>
```

**Comment by pshirshov** [comment]
@ktonga : could you review the P/R and my comments on it?..

**Comment by pshirshov** [comment]
Meanwhile this may be an option for those who need non-snapshot versions as-is:

```
libraryDependencies += "com.github.pshirshov.izumi.r2" %% "scalaz-zio" % "0.1.0"
```

I'm going to continue publishing these artifacts until the pipeline issues resolved in upstream.

**Comment by NeQuissimus** [comment]
I'll provide the rest that is needed in a bit.
