### ISSUE TITLE
flatMap on fail

### ISSUE THREAD

**Issue by NeQuissimus** [scalaz/scalaz-zio#500]
I am confused :)

I am looking at the current implementation of `IO.(f|F)latMap`
https://github.com/scalaz/scalaz-zio/blob/fb92adbb8d3e5bbfa02239afd2f2a156dc9df4ab/core/shared/src/main/scala/scalaz/zio/IO.scala#L87

https://github.com/scalaz/scalaz-zio/blob/fb92adbb8d3e5bbfa02239afd2f2a156dc9df4ab/core/shared/src/main/scala/scalaz/zio/IO.scala#L849

Should it not shortcut `flatMap` if the `IO` has already failed?

@jdegoes ?

**Comment by regiskuckaertz** [comment]
True that it's done in `map`.
