### ISSUE TITLE
Finish cleaning up the API

### ISSUE THREAD

**Issue by sideeffffect** [scalaz/scalaz-zio#507]
(from https://github.com/scalaz/scalaz-zio/pull/469#issuecomment-453850064 )

- [ ] Add missing `succeed` methods (some have `succeedLazy` but not `succeed`)
- [ ] `leftMap` => `mapError` (in `IO`, `Exit`, etc.)
- [ ] `redeemPure` => `fold`
- [ ] `asyncIO` => `asyncM`
- [x] `raceBoth` => `raceEither`
- [ ] `<||>` renamed to an alias

**EDIT**: Change to use named constructors for anything returned in IO.

 - `Ref.apply` => `Ref.make`
 - `RefM.apply` => `RefM.make`
 - `Managed.apply` => `Managed.make`
 - Etc.

Relocation:

 - Move `Chunk` from `scalaz.zio.stream` to `scalaz.zio`

Finally we have some cleanup to do on `Exit` /  `Exit.Cause` to make naming more consistent:

 - [ ] `Exit.fail` => `Exit.halt`
 - [ ] `Exit.checked` => `Exit.fail`
 - [ ] `Exit.unchecked` => `Exit.die`
 - [ ] `Exit.interrupted` => `Exit.interrupt`
 - [ ] `Cause.checked` => `Cause.fail`
 - [ ] `Cause.unchecked` => `Cause.die`
 - [ ] `Cause.interrupted` => `Cause.interrupt`
 - [ ] `Cause.Checked` => `Cause.Fail`
 - [ ] `Cause.Unchecked` => `Cause.Die`
 - [ ] `Cause.Interrupted` => `Cause.Interrupt`
 - [ ] `Cause#checked` => `Cause#failures`
 - [ ] `Cause#unchecked` => `Cause.defects`
 - [ ] `Cause#isChecked` => `Cause.isFailure`

**Comment by sideeffffect** [comment]
@jdegoes please include this in https://github.com/scalaz/scalaz-zio/issues/401

**Comment by ghostdogpr** [comment]
I'll do this one. A couple questions though:
- The deprecated functions are the aliases (e.g. `IO.traverse` is a deprecated alias for `IO.foreach`). I think the intention was to keep them for discoverability. Do you think we should get rid of them or keep them? Deprecated or not?
- `fold` and `asyncM` already exist but they are aliases at the moment. Do you want them to become the main function and the other ones (`redeemPure`, `asyncIO`) to be the alias instead?

**Comment by ghostdogpr** [comment]
OK, I will remove the deprecated methods then.
