### ISSUE TITLE
should it not be called ZIO?

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz-zio#51]
shouldn't the main class not be called `ZIO`? :smile: 

Then `IO[a]` could be an alias to `ZIO[Throwable, a]`

**Comment by leandrob13** [comment]
Right now that alias is called `Task` https://github.com/scalaz/scalaz-zio/blob/e20ba75df43a169f4830b27675114c0c80db865e/core/shared/src/main/scala/scalaz/zio/package.scala#L21

**Comment by emilypi** [comment]
Or better yet, `type IlluminatIO a = IO Throwable a`

**Comment by jdegoes** [comment]
I'm tempted to add:

```scala
type LosersWhoAreInLoveWithThrowable[A] = IO[Throwable, A]
```

😈

**Comment by fommil** [comment]
```scala
type MercenariesWhoSellTheirHaskellSoulForScalaMoney[a] = IO[Throwable, a]
```

**Comment by emilypi** [comment]
Well, this derailed quickly. How about we settle on 

```haskell
type SpaghettIO a = IO Throwable a
```

**Comment by jdegoes** [comment]
@emilypi 
![2chm5l](https://user-images.githubusercontent.com/156745/41593723-3547ae9e-737e-11e8-9512-433576c2e34a.jpg)

**Comment by emilypi** [comment]
@jdegoes GET DISTURBED BOIIIII

Square brackets around type parameters violate my code of conduct
