### ISSUE TITLE
Built-in support for testing IO programs

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#510]
Supersedes #263, #264

**Comment by jdegoes** [comment]
Closed by [ZIO environment](#582)

**Comment by guizmaii** [comment]
Hey @jdegoes,

The link in "Closed by ZIO environment" is not correct. 

It's: https://github.com/scalaz/scalaz-zio/issues/510#582
While it should be https://github.com/scalaz/scalaz-zio/issues/582

;)

**Comment by jdegoes** [comment]
@guizmaii Fixed! Apparently I don't know how to link to issues. 😄
