### ISSUE TITLE
Logs while running unit test "Checked(...)"

### ISSUE THREAD

**Issue by leobenkel** [scalaz/scalaz-zio#511]
Hey,

When I run test, using `RTS` trait in my test, I see a lot of `Checked(....)` in the log which are super annoying. It happens when I try to test that a test have failed properly. 

```
 def unsafeRunToEither[E, I](io: IO[E, I]): Either[Throwable, I] = unsafeRunSync(io).toEither
```
and then I can `assert(unsafeRunToEither(io).isLeft)` to make sure it has failed as expected. 

Is there a way to remove the logs ?

**Comment by NeQuissimus** [comment]
I have this as my base test suite, it clears the logs:

```scala
trait BaseSuite extends TestSuite with RTS {
  override lazy val env: Env = Env.newDefaultEnv(_ => IO.unit)
}
```

**Comment by leobenkel** [comment]
ah thank you !

**Comment by NeQuissimus** [comment]
This may be a candidate for #533, maybe we provide some sort of `TestingRTS`.
I think otherwise we have solved your issue? Reopen if not.
