### ISSUE TITLE
Add Twitter Future/ReactiveX Single/Java Future for IO Benchmarks

### ISSUE THREAD

**Issue by lemastero** [scalaz/scalaz-zio#514]
It would be nice to have:

1. [Twitter Future](https://twitter.github.io/finagle/guide/Futures.html)
2. [Java  Future](https://docs.oracle.com/javase/8/docs/api/index.html?java/util/concurrent/Future.html), [Java CompletableFuture](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html)
3. Java Thread
4. [ReactiveX](http://reactivex.io/documentation/single.html)

in IO Benchmarks:
- IOShallowAttemptBenchmark
- IONarrowFlatMapBenchmark
- IOMapBenchmark
- IODeepFlatMapBenchmark
- IODeepAttemptBenchmark

WDYT
I want to see the numbers from such benchmarks - can give it a shot.

**Comment by fkowal** [comment]
https://github.com/fkowal/scalaz-zio/tree/java_benchmarks

I wanted to see this for myself. I implemented java completablefuture, rxjava.single, reactor.mono

I could polish what done already and fillin the missing ones

**Comment by lemastero** [comment]
@fkowal  I think that would be nice PR (or two).

**Comment by fkowal** [comment]
#518 here's a first PR, open for comments

**Comment by fkowal** [comment]
PR merged. Java Future and Java thread are missing. 
Java Future is an interface with tons of implementations. So i am not sure about it.
Java Thread i am having trouble thinking of how this would look like

**Comment by lemastero** [comment]
@fkowal true :) Great job! Thank you very much for adding those benchmarks ❤️ I need those.
