### ISSUE TITLE
Remove bracket as a primitive, express using other more core operations

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#53]
General sketch of idea:

```scala
def bracket[E, A, B](acquire: IO[E, A])(release: ExitResult[E, A] => IO[Void, Unit])(use: A => IO[E, B]): IO[E, B] = 
  for {
    ref <- IORef[Option[ExitResult[E, A]]](None)
    b   <- (for {
             e <- acquire.run.flatMap(e => ref.write(Some(e)) *> IO.now(e)).uninterruptibly
             b <- e match {
                    case ExitResult.Completed(b)  => IO.now(b)
                    case ExitResult.Terminated(t) => IO.terminate(t)
                    case ExitResult.Failed(e)     => IO.fail(e)
                  }
           } yield b).ensuring(ref.read.flatMap(_.fold(IO.unit)(release)).uninterruptibly)
  } yield b

```

 - [x] Introduce derived bracket
 - [x] Introduce primitive Ensuring
 - [ ] Remove primitive Bracket, replace with derived functionality

**Comment by jdegoes** [comment]
Note that @regiskuckaertz implemented Phase 1 of this, which is introducing the new derived bracket.

The next step is to refactor RTS / IO so that `Ensuring` becomes the new primitive. Then the old bracket can be removed / replaced by the new derived one.

**Comment by jdegoes** [comment]
@regiskuckaertz Yes, only:

```scala
case IO.Tags.Ensuring =>
  val io = curIo.asInstanceOf[IO.Ensuring[E, Any]]
  val finalizer = Finalizer[E](_ => io.finalizer)
  stack.push(finalizer)
  curIo = io.io
```

You don't need `ref`. 

Then in step 3, the `Finalizer` structure can be simplified, as well as all the logic around collecting finalizers when `Bracket` is removed and replaced with the derived version.

**Comment by regiskuckaertz** [comment]
Gotcha. Did that and it failed two tests where the finalizer threw an exception. To get around that I ran the finalizer in the main IO action. [Check it out](https://github.com/scalaz/scalaz-zio/pull/67).

**Comment by regiskuckaertz** [comment]
The infamous step 3 😨 I've been doing some detective work but I'm not sure I got everything right. Assuming the following change:
```scala
final case class Finalizer[E](finalizer: Infallible[Unit]) extends Function[Any, IO[E, Any]] {
  final def apply(v: Any): IO[E, Any] = finalizer.widenError[E] *> IO.now(v)
}
```
means `finalizer` is threaded in when `nextInstr` is called. That explains why the `Ensuring` branch can be simplified to:
```scala
case IO.Tags.Ensuring =>
  val io = curIo.asInstanceOf[IO.Ensuring[E, Any]]
  stack.push(Finalizer[E](io.finalizer))
  curIo = io.io
```
The fun begins in the `Fail` branch 😄 The `error` in `catchError(error)` has nowhere to go, it will be consumed by the error handler of an `IO.Attempt` if it is found on the stack, or else evaluation ends in `Failed` state. We still have to compose finalizers though. I came up with:
```scala
final def catchError: IO[Void, List[Throwable]] = {
  var errorHandler: Any => IO[Any, Any] = null
  var finalizer: IO[Void, List[Throwable]] = null

  while ((errorHandler eq null) && !stack.isEmpty) {
    stack.pop() match {
      case a: IO.Attempt[_, _, _, _] =>
        errorHandler = a.err.asInstanceOf[Any => IO[Any, Any]]
      case f0: Finalizer[_] =>
        val f = f0.asInstanceOf[Finalizer[Void]]
        val currentFinalizer: IO[Void, List[Throwable]] = f(()).run.map(collectDefect)
        if (finalizer eq null) finalizer = currentFinalizer
        else finalizer = finalizer.zipWith(currentFinalizer)(_ ++ _)
      case _ =>
    }
  }

  if (errorHandler ne null) stack.push(errorHandler)

  finalizer
}
```
Same makeup applied to `interruptStack`. At that point I'm not sure that `Finalizer` still needs a type parameter?

All tests pass with these changes, but I'm not sure I got everything right 🤔

**Comment by jdegoes** [comment]
This is almost right. Make this change:

```scala
      case f0: Finalizer[_] =>
        val f = f0.asInstanceOf[Finalizer[E]].finalizer
        val currentFinalizer: IO[Void, List[Throwable]] = f(()).run.map(collectDefect)
        if (finalizer eq null) finalizer = currentFinalizer
        else finalizer = finalizer.zipWith(currentFinalizer)(_ ++ _)
      case _ =>
    }
```

Note how the error parameter is `E` and not `Void` (in `Finalizer[E]`), but extraction of the `finalizer` will allow you to access the finalizer that has the right type `IO[Void, Unit]`.

Similar change for `interruptStack`.

**Comment by jdegoes** [comment]
Oh, I think you still need `E` in `Finalizer` because it extends `Any => IO[E, Any]` so it can be pushed onto the stack without type coercion (in fact that type is not exactly right if the error changes, but that's the way it is now, I certainly wouldn't change it in this pull request).

**Comment by jdegoes** [comment]
@regiskuckaertz I made a note [here](https://github.com/scalaz/scalaz-zio/issues/68) on how `Ensuring` can be made safer than in the above example.

Basically it's changing:

```scala
case IO.Tags.Ensuring =>
  val io = curIo.asInstanceOf[IO.Ensuring[E, Any]]
  stack.push(Finalizer[E](io.finalizer))
  curIo = io.io
```

to:

```scala
case IO.Tags.Ensuring =>
  val io = curIo.asInstanceOf[IO.Ensuring[E, Any]]
  stack.push(enterUninterruptible.flatMap(_ => Finalizer[E](io.finalizer)).flatMap(_ => exitUninterruptible)
  curIo = io.io
```

This guards against the normal execution case (non-failure) where the fiber might be interrupted as soon as `Finalizer` is popped off the stack, but before it completes finalization.

**Comment by regiskuckaertz** [comment]
@jdegoes That makes sense, thanks for the explanation.

I thought the above refinement would fix the failing test in [my PR](https://github.com/scalaz/scalaz-zio/pull/69) but it doesn't. Will investigate later.

**Comment by jdegoes** [comment]
No, looks good, thanks!
