### ISSUE TITLE
Refactor Managed to be more general

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#543]
Concurrent data structures can benefit from a more general notion of managed resource, which allows acquisition to be interrupted.

To serve these aims, `Managed` must be refactored into something like this:

```scala
trait Managed[+E, +A] {
  def setup: IO[E, UseToken[E, A]]

  def use[E1 >: E, B](f: A => IO[E1, B]): IO[E1, B] = 
    setup.flatMap(token => token.acquire.flatMap(f).ensuring(token.release))
  ...
}
object Managed {
  final case class UseToken[E, A](acquire: IO[E, A], release: IO[Nothing, _])
}
```

It should be possible to reconstruct the same capabilities around this definition of `Managed`, including a careful reconstruction of `Managed.apply`.

After this is in place, we can leverage `Managed` in data structures like `Semaphore`, which can then expose "acquire" operations that are interruptible, e.g.:

```scala
class Semaphore {
  def acquire(n: Int): Managed[Unit]
}
```

To percolate this up through multiple levels of concurrent data structures, it may be necessary to augment the capabilities of `Managed`. Ideally the API stays backward compatible, however.

**Comment by iravid** [comment]
Sounds very useful. Would adding another constructor (e.g. `Managed.interruptible`) not work? Where instead of using `bracket` in `use`, we use `ensuring`?

**Comment by jdegoes** [comment]
Where would you get the `R` to feed to `release`?

**Comment by iravid** [comment]
`// with some Ref dances to ensure release is actually run even if f is interrupted` ;-)

**Comment by jdegoes** [comment]
The problem is that the release must be run _even if_ the acquire is interrupted, and does not produce the `R`.

**Comment by iravid** [comment]
Can we keep around a `Ref[Option[R]]`?

**Comment by jdegoes** [comment]
Yes, but the type signature of release demands you supply an `R`. That's why I think the above formulation is more general, because it doesn't assume that `R` is produced, so the bracket version can deal with that using a Ref Option (for example).

**Comment by iravid** [comment]
Ah, I see.

But let me refocus my question: I was originally trying to understand how `UseToken` is different than keeping an `acquire` and `release`.

If I understand correctly, we can create a `Managed` usable for `Semaphore` by plugging different logic in the `use` method. I'm not sure I follow why we need to keep both `acquire` and `release` in an `IO`.

**Comment by jdegoes** [comment]
This is mainly for concurrent data structures, which exhibit the following pattern:

1. They allocate memory (`setup`), typically a promise, which is effectful.
2. The acquire action only modifies state, but can be interrupted, _unlike_ acquire in bracket.
2. The release action is capable of knowing whether or not acquire succeeded merely by looking at the state (and the allocated memory, e.g. `Promise`), and can therefore undo the effects of acquisition safely (if acquire succeeded) or leave the state alone (if it was interrupted before it modified state).

This allows concurrent data structures whose "blocking" methods are interruptible. If they're not interruptible it's easy to "deadlock" them which can "leak" memory (among other problems).

**Comment by iravid** [comment]
Ah, thanks, this makes the purpose clearer. I also forgot that we rely on the `acquire` and `release` methods in the combinators, so we can't just stuff all the logic into `use`.

**Comment by iravid** [comment]
I'll give this a go some time this week.
