### ISSUE TITLE
Release monix task is failing master build

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#562]
See [here](
https://travis-ci.org/scalaz/scalaz-zio/jobs/490316716).

@NeQuissimus Do you think you could disable this until we get it fixed? I'd like to do a release.

**Comment by NeQuissimus** [comment]
Oh, bloody Travis CI...

**Comment by NeQuissimus** [comment]
I commented out `interop-monix` for now. I genuinely do not know why it is failing the way it is. But it is also late here and I am tired :)

**Comment by jdegoes** [comment]
@NeQuissimus Thanks for the quick fix...er bandaid. 😄 🙏

**Comment by gaspb** [comment]
Hello there, any chance to have Monix interop back on its feets?
Thanks in advance! :)
