### ISSUE TITLE
Split Queue into contravariant / covariant pieces 

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#564]
Currently `Queue[A]` has one type parameter. We should refactor it to have two:

```scala
trait Queue2[-I, +O] // Open to better names
```

Then define `type Queue[A] = Queue2[A, A]` and define `val Queue = Queue2` (a fake "companion object" for the `Queue` type synonym). 

Then because `Queue2` will not be invariant anymore, we can define combinators on Queues, such as:

```scala
// on I
contramap
// on O
map
flatMap
filter
zip
zipWith
++
// etc.
```

Since this would be a breaking change, I'd like to get this in before 1.0. Volunteers welcome, let me know if you need any help!

**Comment by LGLO** [comment]
What is definition of done for this issue? Does it contain all mentioned combinators or is it only about defining Queue2 and refactoring current code?

**Comment by ghostdogpr** [comment]
Isn’t Queue2 quite redundant with Stream? I don’t see what it brings that I couldn’t do with Stream.

**Comment by regiskuckaertz** [comment]
`Queue2` models [transducers](https://clojure.org/reference/transducers) and are not lazy (therefore not a good abstraction for infinite streams). Streams are much more powerful I would say, allow for a much broader set of usages.

**Comment by jdegoes** [comment]
@ghostdogpr What @regiskuckaertz said. 😄 

The filter method on a queue can be used to partition the work of the underlying queue into independent sets; e.g. imagine building a message hub on a queue where you want to return "views" of that queue for different components.

@LGLO I think definition of done is just making the separation (in a backward-compatible way). We can add methods to a class without breaking backward binary compatibility.

**Comment by ghostdogpr** [comment]
I see, thanks.

Can we construct a Queue2 directly or only through map/filter/etc on a Queue?

**Comment by jdegoes** [comment]
Queue will just be a type synonym for Queue2, and there's no need / way to construct one directly (i.e. different input / output parameters). But if you filter or map a Queue (e.g. `I` = `O`), then it will "change" into a Queue2, by which I mean you can't use the type synonym for it anymore.
