### ISSUE TITLE
Split Ref / RefM into covariant / convravariant pieces

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#566]
Currently `Ref` and `RefM` have one type parameter. We may benefit from versions that have two:

```scala
class Ref2[-A, +B]
class Ref2M[-A, +B]
```

Then type synonyms and fake package objects for the normal ones:

```scala
type Ref[A] = Ref2[A, A]
type RefM[A] = Ref2M[A, A]
val Ref = Ref2
val RefM = Ref2M
```

Then code which only needs to "get" can use `Ref2[_, A]`, while code that only needs to "set" can use `Ref2[_, A]`, and we can add methods to `Ref2` including standard ones like map, zip, contramap, etc.

**Comment by rightfold** [comment]
Code that only needs to get or set could just use `IO[Nothing, A]` and `KleisliIO[Nothing, A, Unit]`, no?

**Comment by jdegoes** [comment]
The main point of this is to add "views" of a ref. Maybe this isn't helpful since you can just pass the "get" function directly and map over that?
