### ISSUE TITLE
`bracket` type inference problem when `acquire` E is subtype of `use` E

### ISSUE THREAD

**Issue by LGLO** [scalaz/scalaz-zio#586]
```scala
  def test: Task[Double] = {
    val acquire: ZIO[Any, Exception, Int] = ???
    val use: Int => ZIO[Any, Throwable, Double] = ???
    val cleanup: Int => ZIO[Any, Nothing, Unit] = ???
    acquire.bracket(cleanup)(use)
  }
```
Currently it doesn't compile because `use` is expected to be `ZIO[Any, Exception, Int]`.

Should work when acquire E is subtype of use E and when use E is subtype of acquire E.

EDIT:
R type inference fails here:
```scala
type Resource = Unit
val acquire: ZIO[Any, Nothing, Resource] = ???
val release: Resource => ZIO[Any, Nothing, String] = ???
val use: Resource => ZIO[Unit, Nothing, Int] = ???
acquire.bracket(release)(use): ZIO[Unit, Nothing, Int]
ZIO.bracket(acquire)(release)(use): ZIO[Unit, Nothing, Int]
```

~Let me try to solve this puzzle.~

**Comment by LGLO** [comment]
Well, if anyone can implement it, don't wait for me. I have to master variance and type-inference before being able to implement it.

**Comment by jdegoes** [comment]
This would be a good test to add!

**Comment by regiskuckaertz** [comment]
It looks like this has been fixed with the latest changes to `bracket`.
