### ISSUE TITLE
Possible memory leak in queue.awaitShutdown

### ISSUE THREAD

**Issue by iravid** [scalaz/scalaz-zio#610]
Still requires investigation, but:
- Repeated executions of queue.awaitShutdown.fork.flatMap(_.interrupt) will:
   - allocate a promise
   - add the promise's completion to the queue's shutdown hook
- Assuming the queue is long running, a promise will be allocated for each execution of the above
- The promises will not be garbage collected as they are referenced by the shutdown hook

**Comment by jdegoes** [comment]
That's bad. Should be a simple fix though. Once the queue is shutdown, it should not add any more hooks, but should immediately return.

**Comment by ghostdogpr** [comment]
Right, we can simply have a single Promise at the queue level and have all calls to `awaitShutdown` point to it. I’ll submit a PR. 

@jdegoes it’s already the case, but the code should be even simpler after the fix
