### ISSUE TITLE
Revise FiberLocal

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#618]
Copy-on-write semantics with manual or auto (fork-driven) propagation.

1. A FiberLocal is created.
2. Fiber A sets the value of this FiberLocal to `42`.
3. Fiber A forks another fiber, Fiber B. 
4. Fiber B reads the value of the FiberLocal and sees `42`.
5. Fiber B sets the value of the FiberLocal to `3`.
6. Fiber B reads the value of the FiberLocal and sees `3`.
7. Fiber A reads the value of the FiberLocal and sees `42`.

**Comment by jdegoes** [comment]
It's not necessary to make `fork` the primitive that does propagation. One can imagine an `inherit` primitive:

```scala
for {
  propagate <- fiberLocal.copyOnWrite
  fiber     <- (propagate *> child).fork
} yield ...
```

I don't know what the API would look like. But it could be something like this, and possibly used automatically in `fork`, as that seems the most common use case.

**Comment by iravid** [comment]
yes please!!

**Comment by jdegoes** [comment]
@iravid What issues would this solve for you?

Basically it would solve all mine, ever. 😆

**Comment by iravid** [comment]
contextual logging, using the same pool for submitted Spark computations, etc...
