### ISSUE TITLE
<> should not recover from defects

### ISSUE THREAD

**Issue by iravid** [scalaz/scalaz-zio#619]
E.g. `IO.dieMessage(“ouch”) <> IO.unit` should result in fiber termination.

Reasoning: defect recovery should be reserved to explicit combinators like `run` and `sandbox`. Usage of `<>`, being more common, may hide defects.

**Comment by regiskuckaertz** [comment]
So, if the first IO fails with an `E` than the second one is evaluated, but if the first one “throws” then the exception is propagated?

I believe this is right indeed, makes exceptional error behaviour symmetric, and normal failure the unit of `<>`. Similar to STM.
