### ISSUE TITLE
Add TestConsole to `testkit` package

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#620]
Modeled after `TestClock`, the `TestConsole` should be an implementation of `Console.Service` that can be constructed with a `Ref[TestConsole.Data]`, which should read lines of input from a `input: List[String]` buffer, and save lines of output to a `output: Vector[String]` buffer.

**Comment by LGLO** [comment]
@jdegoes This looks like done via #626

**Comment by jdegoes** [comment]
@LGLO Thanks!
