### ISSUE TITLE
Add TestRandom to `testkit` package

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#623]
Modeled after `TestClock`, the `TestRandom` should be an implementation of `Random.Service` that can be constructed with a `Ref[TestRandom.Data]`, which should read "random" data from lists of the various types that appear in the `Random` service interface. For convenience, different types can have defaults with constants. If a list has more than one element, "wrap around" semantics should be used (e.g. `randomInts = 1 :: 2 :: 3` will produce random ints in sequence `1, 2, 3, 1, 2, 3, ...`).

**Comment by jupposessho** [comment]
Can I take this one?

**Comment by jupposessho** [comment]
@jdegoes is it ready to close?

**Comment by jdegoes** [comment]
@jupposessho Yep, looks good to me!
