### ISSUE TITLE
Upgrade Scalaz 7.x instances

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#651]
We have Scalaz 7.x instances in the interop module. However, they are overly restricted to use `IO`, when many can be generalized to support `ZIO` with arbitrary `R`. This ticket is to go through and generalize as many as possible to support `R` (mainly by using `ZIO` data type instead of `IO` type alias and adding `R` parameters where necessary). 

Finally, now that ZIO is a profunctor, we can think about implementing instances of a new range of type class instances for ZIO... (Maybe a separate ticket? Depends on who wants to do this one.)

**Comment by Cereopsis** [comment]
OK, I'm up for some type gymnastics...

**Comment by Cereopsis** [comment]
@jdegoes 
I'm wondering how far to go particularly regarding the tests. They currently pass with eg ZIO[Any, E, A] although of course this is equivalent to the original  IO[E, A]. I reckon I can make the GenIO work something like this:

```
def genZIO[R, E: Arbitrary: Cogen, A: Arbitrary: Cogen]: Gen[ZIO[R, E, A]] =
  Gen.oneOf(genSuccess[R, E, A], genFailure[R, E, A])

def genSuccess[R, E, A: Arbitrary]: Gen[ZIO[R, E, A]] = 
  Gen.oneOf(genSyncSuccess[R, E, A], genAsyncSuccess[R, E, A])

def genSyncSuccess[R, E, A: Arbitrary]: Gen[ZIO[R, E, A]] = 
  Arbitrary.arbitrary[A]
    .map(a => ZIO.accessM[R].apply[E,A](_ => ZIO.succeedLazy[A](a)))

// etc
```
What I'm not quite so clear on at the moment is what 'R' the tests would inject. I suppose this could also be Arbitrary if it isn't actually used. Is there any mileage in taking it that far?

**Comment by jdegoes** [comment]
I don't think there's mileage in that. A few tests, of course, for example profunctor tests, would test for that directly, but the majority of them would just have to synthesize an `R` that would then be ignored in `accessM` (because what can you do with an arbitrary `R`?), so I don't think it actually improves things. The `E` on the other hand is different because you get `genFailure` out of that.

**Comment by Cereopsis** [comment]
@jdegoes Yes, great, I was thinking it was redundant. I'll submit a WIP PR for your perusal

**Comment by Cereopsis** [comment]
@jdegoes I reverted to using IO[E,A] in scala72Spec as it does the job. ParIO is still using Any but there's no way around that, I think

**Comment by jdegoes** [comment]
ParIO can use R, take a look at how interop-cats does this.

**Comment by Cereopsis** [comment]
@jdegoes I have made the renaming changes suggested but need to go through the microsite quickly. If the naming is minor it could through as is? Otherwise I can get to it later
