### ISSUE TITLE
Testing ZIOs without DefaultRuntime uses "internal" Platform

### ISSUE THREAD

**Issue by jamesward** [scalaz/scalaz-zio#657]
I'm writing some tests for my ZIOs and running then with a custom `Runtime` which requires me to create a `Platform` which leads me to traits in a package named `internal` which seems scary.

**Comment by jdegoes** [comment]
It kind of is scary. The stuff inside `internal` is not purely functional.

How about preferred constructors for `Runtime` that use the default `Platform`, so that for most purposes, users would never need to supply one, unless they need custom behavior for `Platform`?

**Comment by jamesward** [comment]
In my case I needed to override Platform to not `println` failures:
https://github.com/WinterTechForum/zio-hello/blob/master/src/test/scala/MyAppSpec.scala#L25

Cause I didn't want those showing up when I run my tests.

**Comment by NeQuissimus** [comment]
hmm, yeah, that definitely needs to be a thing.
Maybe we should just have a "SilentPlatform" :D

**Comment by jdegoes** [comment]
Or maybe stderr instead of stdout by default?

**Comment by jdegoes** [comment]
I'l look at this later. Maybe helpers can be added to `Runtime` to change platform capabilities.

**Comment by jdegoes** [comment]
e.g. `Runtime#withReportError`, etc.

**Comment by NeQuissimus** [comment]
FYI, in 0.6.x I added this to my testing RTS:

```
override lazy val env: Env = Env.newDefaultEnv(_ => IO.unit)
```

Something equivalent would be nice (I have yet to update our code beyond 0.6) :)

**Comment by jdegoes** [comment]
As of #889, there are helpers on `Runtime` that can apply modifications to the default `Platform`, so no explicit use of `Platform` is required.
