### ISSUE TITLE
Add support for cross-building coreJVM with Dotty

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#672]
It's time to add cross-build support for Dotty to the coreJVM project! Shouldn't involve many (if any) code changes, just maybe a type annotation here or there. I'm happy to assist with any troubles that arise.

See [here](https://github.com/lampepfl/dotty-example-project) for an example project.

**Comment by ratoshniuk** [comment]
@jdegoes i will take a look

**Comment by ghostdogpr** [comment]
Done in #674
