### ISSUE TITLE
ZStream transduce makes spurious ZSink calls

### ISSUE THREAD

**Issue by quelgar** [scalaz/scalaz-zio#678]
I expected the following test case to pass, but it fails:

```scala
  private def transduceTermination = {
    val sink = Sink.fold(None: Option[Int]) { (_, a: Int) =>
      ZSink.Step.done(Some(a), Chunk.empty)
    }
    val transduced = ZStream(1).transduce(sink)
    val prg = transduced.run(ZSink.collect[Option[Int]])
    val list = unsafeRun(prg)  // List(Some(1), None)
    list must_=== List(Some(1))
  }
```

The issue is that once the last value from the upstream has been processed, `transduce` finishes off by calling `Sink#initial` followed by `Sink#extract`. In the above test cases, the sequence of calls to the sink are:

1. `initial` → Sets state to `None`
2. `step` → Sets state to `Some(1)`
3. `extract` → returns `Some(1)`
4. `initial` → Sets state to `None`
5. `extract` → returns `None`

meaning the transduced stream emits two values: `Some(1)` and `None`.

This issue doesn't show up for any sinks where `extract` errors if there hasn't been at least one call to `step`, as `transduce` eats all errors from the final `extract` call (I have no idea why), and nothing is emitted downstream.

I can have a go at fixing this, but I thought it worth confirming that this is really not expected.

**Comment by iravid** [comment]
Thanks for investigating this @quelgar! I agree that your test indicates the desired behavior. Please give this a shot if you have the time.

A few notes:
- The last calls to `initial` and `extract` are intended to process the leftovers from the last element, but that combinator is a bit of a maze so bugs are definitely possible.
- The `foldM` that swallows the errors at the end is a bit suspicious. Maybe @jdegoes remembers why is it there.

Let us know if you need any assistance in fixing this!

**Comment by iravid** [comment]
Looking back in the commit history, I see that I added the call to `redeem` (which is now `ZIO#foldM`) in https://github.com/scalaz/scalaz-zio/commit/b3198d153945787ec30afe004ce556246e92a6a4, but I can't recall why. So let's fix this indeed :-)
