### ISSUE TITLE
Change Console.Live.getStrLn to fail with EOFException rather than returning null

### ISSUE THREAD

**Issue by jamesward** [scalaz/scalaz-zio#679]
The Scala `StdIn.readLine` can produce a null value which feels weird to encounter in ZIO's `Console.Live`:
https://github.com/scalaz/scalaz-zio/blob/master/core/shared/src/main/scala/scalaz/zio/console/Console.scala#L71

Should this return an Either or Option instead?

**Comment by NeQuissimus** [comment]
Indeed!

**Comment by jdegoes** [comment]
Woah. Not good. How about we throw IOException there and force the user to deal with it that way?

**Comment by jamesward** [comment]
Yeah, not sure what the right semantics are for this.  I did a sum error:
https://github.com/WinterTechForum/zio-hello/blob/master/src/main/scala/MyApp.scala#L19-L32

**Comment by jdegoes** [comment]
I'm going to say we raise [EOFException](https://docs.oracle.com/javase/7/docs/api/java/io/EOFException.html), which is already compatible with the type signature of `getStr` / `getStrLn`.

**Comment by jdegoes** [comment]
For anyone who wants to take this ticket:

Change the implementation of `getStr` / `getStrLn` to fail with `ZIO.fail(new EOFException("There is no input left to read"))` or something similar whenever the underlying `StdIn.readLine()` returns `null`.

**Comment by Cereopsis** [comment]
I was going to have a bash at this...

Just noticed this in scalaz.zio.testkit.TestConsole: `.mapError(_ => new IOException("There is no more input left to read"))`

I guess it would be worth synchronising with this change?

**Comment by jdegoes** [comment]
@Cereopsis Yes, definitely!

**Comment by jamesward** [comment]
Fantastic!  Thanks @jdegoes.

**Comment by jdegoes** [comment]
Thanks to @Cereopsis! 😄 

Thanks for reporting @jamesward!
