### ISSUE TITLE
Fix issues with non-interruption after failure state

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#68]
Following #53, interruption can be made more precise, which may address #64. 

Currently `uninterruptibly` is implemented like so:

```scala
                    curIo = for {
                      _ <- enterUninterruptible
                      v <- io.io
                      _ <- exitUninterruptible
                    } yield v
```

This is not actually precise, because if `io.io`. fails, then the fiber will be in a permanently non-interruptible state. In theory, this can be solved by:

```scala
                    curIo = for {
                      _ <- enterUninterruptible
                      e <- io.io.attempt
                      _ <- exitUninterruptible
                      v <- e.fold(IO.fail)(IO.now)
                    } yield v
```

But this makes it much slower. With `Ensuring` becoming a fast operation thanks to #53, we can do better:

```scala
                    curIo = enterUninterruptible.flatMap(_ => io.io.ensuring(exitUninterruptible))
```

Because `enterUninterruptible` cannot fail, and because once in such a state, the fiber cannot be interrupted during the `flatMap`, the only place for the computation to fail is `io.io`, which is now attached with a finalizer that exits the uninterruptible section.

Now some care is needed elsewhere. In particular, when a `Finalizer` is being run.

```scala
def apply(a: Any): IO[E, Any] = finalizer.widenError[E] *> IO.now(a)
```

In the failure scenario, if the finalizer is popped off the stack during error or interruption, then it's uninterruptible status must be guaranteed (and, it seems like this is true!).

But in the success scenario, if the `Finalizer` is popped off the stack via `nextInstr`, then it's quite possible that the action will be interrupted before anything inside the `Finalizer.finalizer` is actually run.

In order to guard against this, one option is to modify `nextInstr` so that it checks to see if the next instruction is a `Finalizer`, and if so, it enters an uninterruptible section (`noInterrupt += 1`), and pushes another action on the stack (`_ => exitUninterruptible`) to exit the interruptible section after the finalizer has been executed.

Note there is no need and of course it would create a circular loop for `ensuring` to be used here. The reason is that if the finalizer fails (which is the only way the above composite io can fail), then the fiber will be terminated, so the lack of exiting the uninterruptible section has no effect.

Other logic around interruption / finalizers should be checked and confirmed in this ticket.

**Comment by regiskuckaertz** [comment]
Hi @jdegoes I think I picked up a few of those [in this PR](https://github.com/scalaz/scalaz-zio/pull/86), your feedback would be mucho appreciado 🙏
