### ISSUE TITLE
ClockSpec in Testkit not testing TestClock

### ISSUE THREAD

**Issue by mschuwalow** [scalaz/scalaz-zio#689]
Hi,
the following tests https://github.com/scalaz/scalaz-zio/blob/master/testkit/jvm/src/test/scala/scalaz/zio/testkit/ClockSpec.scala#L17-L40 seem to be testing the Clock.Live implementation. I assume they should test the TestClock instead?

**Comment by jdegoes** [comment]
@mschuwalow Good catch! They are leftover from a long time ago (old clock, pre Environment)

**Comment by mschuwalow** [comment]
Cool. I'll try to get a pr out later.
