### ISSUE TITLE
Add Scheduler helper(s)

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#690]
It would be nice to easily repeat actions until some condition is satisfied, then map the effect value to something else, which would then be returned by `ZIO#repeat`.

```scala
def doUntil(pf: PartialFunction[A, B]): ZSchedule[Any, A, B] = ???
```

In particular, I'm thinking about code like this:

```scala
effect.repeat(Schedule.doUntil { case Some(a) => a }) // Get the A out of the Option[A]
```

**Comment by VladKopanev** [comment]
Hi, I would like to help with this!
