### ISSUE TITLE
Make integration with Cats Effect more friendly

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#694]
Right now, the user requires an `implicit runtime: Runtime[R]` for their chosen environment `R` in order to summon the cats-effect instances.

It would be nice to provide this automatically. Possibly we can change `App`

```scala
trait App { 
  implicit runtime: Runtime[Environment] = this
  ...
}
```

Then at least, this makes `App` ready-to-go for Cats Effect. The drawback is that this implicit will make using custom environments harder. Indeed, `App` itself hard codes the `Environment` to be the core set of effects in ZIO—perhaps this should change?

There's still the issue of "what type do I use for cats-effect", which unfortunately varies depending on whether or not the user requires `Timer`.

Possibly in the cats-interop package, we could provide:

```scala
type TimerTask[A] = TaskR[Clock, A]
val TimerTask = TaskR
```

Then encourage Cats Effect users to use this unless they need a more powerful / custom `R`.

**EDIT**: Anything else we should stick inside the Cats type alias aside from `Clock`?

**Comment by gvolpe** [comment]
I'm giving it a spin at this and although it works it doesn't feel good to have two different types depending on the required capabilities.

I'm in favor of having an extra `import scalaz.zio.interop.catz.implicits.liveTimer` to bring in the `Clock.Live` instance so we can just keep using `Task` as the default effect compatible with `cats`. (As [suggested](https://github.com/scalaz/scalaz-zio/pull/589#issuecomment-468958858) by @kaishh ). We can just document it.

OTOH that `implicit val runtime` hardcoded in `App` would probably create difficulties when working with custom environments as you have mentioned. What about extending `App`?

```scala
trait RuntimeApp extends App {
  implicit val runtime: Runtime[Environment] = this
}
```

> EDIT: Anything else we should stick inside the Cats type alias aside from Clock?

I think that's it. I added tests for summoning `ContextShift` and `Clock` just in case.

**Comment by jdegoes** [comment]
All right, I'm on board with this: extra import to bring in `liveTimer`. Which will allow people to use just `Task` in their `App`. 👍

**Comment by gvolpe** [comment]
Okay, will get a PR ready soon. How about the `RuntimeApp`? @jdegoes
