### ISSUE TITLE
Make Managed's new reservation capability more first class

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#696]
`Managed` has a new methods of specifying allocation and disposal of a resource: namely, it's new constructor:

```scala
case class ZManaged[R, E, A](reserve: ZIO[R, E, ZManaged.Reservation[R, E, A]]) 
```

This provides "interruptible acquisition", unlike `bracket`. It's also safe, in that it has no possibility of leaking resources when properly utilized.

Unfortunately, people aren't discovering it there. To make it more discoverable, we should make the following changes:

1. First, pull out `Reservation` to the top level, as a class inside the `scalaz.zio` package. 
2. Second, add a new `ZManaged.reserve` method, which accepts a `Reservation`.
3. Third, add a method to `ZIOFunctions` inside `ZIO.scala`, which has this signature:
    ```scala
    def reserve[R, E, A, B](reservation: ZIO[R, E, Reservation[R, E, A]])(use: A => ZIO[R, E, B]): ZIO[R, E, B]
    ```
    This function will merely call `ZManaged.reserve` on the `reservation`, followed by `use` with the specified function.
4. Add Scaladoc for everything.
5. Ideally, update the microsite with a short notice.

/cc @mvv

**Comment by jdegoes** [comment]
Related to #580

**Comment by Cereopsis** [comment]
I can take this one.

**Comment by Cereopsis** [comment]
@jdegoes I'll try and finish the microsite bit this weekend but I was thinking of picking up #687 anyway. Perhaps I should start that sooner rather than later.

**Comment by jdegoes** [comment]
@Cereopsis Sure, whichever you prefer, I'm grateful for either. 😄

**Comment by Cereopsis** [comment]
@jdegoes Perhaps I won't make a meal of the code examples now, rather wait until mdoc for that. Right now I'll tweak a few words. I'm thinking that now it's enough to say that Reservation encapsulates the acquisition/release and ZManaged controls the usage of it.

**Comment by mschuwalow** [comment]
Isn't Reservation enough to provide a conversion between Resource from catz and Managed?
Something like https://github.com/mschuwalow/zio-todo-backend/blob/develop/app/src/main/scala/com/schuwalow/zio/todo/config.scala#L52-L56. Or is this something unsafe to do.
If its safe to do it might be interesting to provide something like this in interop

**Comment by jdegoes** [comment]
`Resource` can be safely converted to `Managed`, but not visa versa without losing interruptibility (it would be "safe" to do that, but in some situations, having interruptible acquisition is necessary for preventing "temporal" leaks).

**Comment by kaishh** [comment]
@jdegoes
Resource's `Suspend` is interruptible,  so I think it should be possible to preserve interruption in Managed - https://github.com/typelevel/cats-effect/blob/c38156e7396988d3160480665f022ec42966c487/core/shared/src/main/scala/cats/effect/Resource.scala#L127
