### ISSUE TITLE
Dotty failure in master

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#702]
See [here](https://travis-ci.org/scalaz/scalaz-zio/jobs/512037894)

```
[error] -- [E007] Type Mismatch Error: /home/travis/build/scalaz/scalaz-zio/core/shared/src/main/scala/scalaz/zio/ZSchedule.scala:595:86 
[error] 595 |      pf.lift(a).fold(Decision.cont(decision.delay, decision.state, Option.empty[B])) { b =>
[error]     |      ^
[error]     |Found:    scalaz.zio.ZSchedule.Decision[scalaz.zio.Schedule[A, A]#State, Option[B]]
[error]     |Required: scalaz.zio.ZSchedule.Decision[Nothing, Option[B]]
[error] 596 |        Decision.done(decision.delay, decision.state, Some(b))
[error] 597 |      }
[error] one error found
[error] (coreJVM / Compile / compileIncremental) Compilation failed
[error] Total time: 21 s, completed Mar 27, 2019 3:05:05 PM
```

Looks like it will need a type annotation. 

@VladKopanev, can I convince you to fix this one? 😄

**Comment by VladKopanev** [comment]
Sure, will do ASAP, hopefully today

**Comment by VladKopanev** [comment]
I've created a PR for this, pls review.
I tried a lot of stuff and the only thing I can come up with for now it's assigning the result of `identity[A]` to a variable with type annotation. It seems like dotty compiler, in most cases, thinks that the `State` type member of `Schedule` of `identity[A]` should be `Nothing` hence when doing `reconsider` it aks the resulting `Decision` to have a `Nothing` as a state wich is impossible.

**Comment by jdegoes** [comment]
Fixed by #703

**Comment by jdegoes** [comment]
@VladKopanev Thanks so much for your work on this! It was a huge life saver.

When you get a chance, can you do a followup PR that adds a "Dotty" comment, similar to the other ones? We're trying to provide as much information to the Scala 3 compiler team to help them identify and fix these problems early on.

**Comment by VladKopanev** [comment]
Of course, this makes sense to me.
