### ISSUE TITLE
Add interruptible operation

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#706]
```scala
object ZIO {
  def interruptible[R, E, A](zio: ZIO[R, E, A]): ZIO[R with UninterruptibleEscape, E, A]

  def uninterruptible[R, E, A](zio: ZIO[R with UninterruptibleEscape, E, A]): ZIO[R, E, A]
}
```

Thanks to types, `interruptible` can only be nested inside `uninterruptible`, whereupon it returns an effect whose interruption (or other cause of failure) can be exposed with `run`, `sandbox`, `orElse`, etc., when inside an uninterruptible block.

Note that `interruptible` allows only _localized_ catching of interruption. Outside the highest `uninterruptible`, the fiber will still be in an interrupted state and will still terminate.

# Tests To Add

1. `IO.uninterruptible(interruptible(IO.never) orElse IO.succeed(42)).fork >>= _.interrupt` is 42
2. Same as above but for: `run`
3. Same as above but for: `sandbox`

# Examples

## Simplified Bracket

```scala
ZIO.uninterruptible {
  for {
    a    <- acquire
    exit <- use(a).interruptible.ensuring(release(a))
    b    <- IO.done(exit)
  } yield b
}
```

/cc @mvv

**Comment by mvv** [comment]
A couple of points/questions:

- I would be cautious to introduce the ability to do something other than `ZIO.interrupt` on the `effect` interruption in `ZIO.interruptible(effect)`, "eaten up" interruptions could be hard to debug. I also suspect it would make implementation a bit more tricky. Do you see it as an essential feature?

- Would `effect` be interruptible in
  ```scala
  def foo = { ... ZIO.interruptible(effect) ... }.uninterruptible
  def bar = { ... foo ... }.uninterruptible // Author of bar does not necessarily know about foo implementation
  bar
  ```
  ?

- Would you agree that `queue.take.interruptible.uninterruptible` should not be interruptible after a value is dequeued from `queue`?
 
I could give implementing this a try after semantics is clarified.

**Comment by jdegoes** [comment]
1. A fiber interrupted will still be set into interrupted state regardless of whether it's in `interruptible` or `uninterruptible`. However, it will only actually begin the winddown process when it's not in an uninterruptible state, or when in it's in an interruptible state inside an uninterruptible state. In the latter case (`uninterruptible { ... interruptible { } ... }`), the fiber can be locally interrupted, bringing control back to inside the parent `uninterruptible`, but of course with a `None` value. The parent `uninterruptible` can decide what if anything to do about that, including merely yield `IO.interrupt` to pass along the interruption.

Does that make sense / seem well-defined?

**Comment by jdegoes** [comment]
> Would you agree that queue.take.interruptible.uninterruptible should not be interruptible after a value is dequeued from queue?

This turns on interruptibility inside the `take`, so it can be interrupted inside there, and if it is, then it enters the parent as a `None`, who then has to deal with that.

**Comment by iravid** [comment]
Why `Option[A]` rather than an interrupted IO?

**Comment by kaishh** [comment]
Unlike Haskell's `mask*` family, the `.interruptible` API here is not tied to the enclosing `uninterruptible`, so the meaning of something like this
```scala
def x = abc.interruptible
```
Would change non-locally depending on whether there is a surrounding `.uninterruptible` scope or not. This may be surprising. Purely theoretically IMHO,  the best behavior API reasoning-wise might be:
```scala
def x = IO.uninterruptibleWith {
  unmask => unmask(abc)
}
```
Where `unmask` closure provided to the user is _uniquely_ tied to the uninterruptible scope created with `uninterruptibleWith` (e.g. there's an equivalent of `Map[Long, InterruptionContext]` with `var interruptionCtxCounter: Long` in `FiberContext`), such that even if the user cheats and returns `unmask` as in
```scala
IO.uninterruptibleWith(IO.succeed)
```
the closure would become a no-op when leaving the specific uninterruptible scope that spawned it.

It's likely overkill, but I think would give you the most reasonable, forcibly-local, semantics.

**Comment by jdegoes** [comment]
@kaishh The runtime behavior of the closure still depends on where it is applied (inside or outside the right block). So I'm not sure it changes anything.

We could, however, make it statically impossible to put `interruptible` anywhere except inside an `uninterruptible` block:

```scala
def interruptible(zio: ZIO[R, E, A]): ZIO[R with Interruptible, E, A]

def uninterruptible(zio: ZIO[R with Interruptible, E, A]): ZIO[R, E, A]
```

Now you have to stuff the interruptible inside the uninterruptible block, since it's the only way to eliminate `Interruptible` from `R`.

> Why Option[A] rather than an interrupted IO?

Assuming the user can `orElse` inside the uninterruptible section, e.g. `myInterruptible orElse myBackup`, then they are equivalent. The use of `Option` forces the user to deal with the possibility that the interruptible section was in fact interrupted. Hopefully leading to better logic, because the user using the code will have to deal at the type level with the case of interruption. Rather than just silently ignore it.

I'm flexible though.

**Comment by iravid** [comment]
Yes, I figured that was the reason. How about `Exit[Nothing, A]`? That way we can also preserve the rest of the fiber structure that was interrupted.

I like the intersection with `Interruptible`, but that is inconsistent with the fact that *everything* in ZIO is interruptible (except what's `uninterruptible`).

**Comment by jdegoes** [comment]
This `Interruptible` marker could be renamed `InsideUninterruptible` or something. The idea is not that it _is_ interruptible, but that it is interruptible and must _occur_ inside an `uninterruptible` block to have meaning. Maybe `UninterruptibleEscape`. 

> Yes, I figured that was the reason. How about Exit[Nothing, A]? That way we can also preserve the rest of the fiber structure that was interrupted.

How about a full-on `Exit[E, A]`? It's weird to put the defects in one place but the failure in another place. Also you have to lose information anytime you pull a `Cause` apart.

**Comment by iravid** [comment]
Right I get you. I like the `Masked/Unmasked` terminology but that may be a bit obscure for anyone not into Haskell / IRQs :-P

So `ZIO[R, Nothing, Exit[E, A]]`? 👍

**Comment by iravid** [comment]
Also, I like the `IO.uninterruptible { unmask =>`. It makes it easier to reason about what's happening with regards to interruption. Does that satisfy the original requirement?

Everything converges to GHC's model eventually...

**Comment by jdegoes** [comment]
> Also, I like the IO.uninterruptible { unmask =>. It makes it easier to reason about what's happening with regards to interruption.

I want to understand this one. How does it make reasoning easier? I suppose you only have to follow the `umask` thread (where it is passed, etc.) in order to see what could be interrupted. Enforcing it has now effect unless used properly could be a bit tricky.

I think that's an alternative approach to `Exit[E, A]`. The reason being: the `Exit[E, A]` forces the interruption to the value level, where you have to deal with it explicitly. You can look at the type and determine that you might not get your `A` out anymore, and you have to decide what to do with that in your uninterruptible section.

If we do the `unmask`, which we should of course call `interruptible` because no one knows what the hell IRQs or masking are, then we probably don't need `Exit[E, A]`, rather, `interruptible` can just take and return something of the same type.

For added security, we could tag the `R` returned by `interruptible` with `UninterruptibleEcape` or something. Just so there's no way to run one of those. 

Actually, it occurs to me that the taggling alone kind of solves the global reasoning problem. If you have a `ZIO` with `UninterruptibleEscape` as part of `R`, you know it can be interrupted. 

Maybe that negates the need both for `unmask` as well as `Exit[E, A]`. The types tell you everything.

**Comment by iravid** [comment]
```scala
def inner(p: Promise[E, A]) = promise.await.interruptible

def outer = 
  (for {
     p <- Promise.make[E, A]
    _ <- inner(p)
  } yield ()).uninterruptible
```

Looking at these two functions, any sort of tagging (type-level / value-level) would be sufficient to make reasoning about interruption possible. So yes, I agree.

**Comment by iravid** [comment]
Sorry, almost true: adding `Exit` or `Option` has an additional benefit that forces you to also deal with the value-level implications of interruption inside `outer.`

**Comment by jdegoes** [comment]
All right so new proposal:

```scala
def interruptible(zio: ZIO[R, E, A]): ZIO[R with UninterruptibleEscape, E, A]

def uninterruptible(zio: ZIO[R with UninterruptibleEscape, E, A]): ZIO[R, E, A]
```

with or without `Option[A]` for the `interruptible` one.

This formulation ensures:

1. You can't actually put an interruptible anywhere, except inside an uninterruptible, so its meaning never changes depending on the location because its location is constrained by types.
2. You will always know, by looking at types, if some code you are passed is secretly interruptible.
3. The fact that (2) is true prevents the need for global reasoning; local reasoning is sufficient.

**Comment by iravid** [comment]
Cool 👍

**Comment by iravid** [comment]
Interestingly, this is similar to the `ZIO.lock` design and somewhat to the supervision design. What's the general pattern here? Monadic regions?

**Comment by mvv** [comment]
I like this one better. Implementation-wise, how `R with
UninterruptibleEscape` is supposed to be constructed in `uninterruptible`?

**Comment by kaishh** [comment]
With a cast since it's a phantom.

**Comment by jdegoes** [comment]
@iravid Yes, monadic regions.

@kaishh No need even for a cast with a cool trick I developed while prototyping `ZIO[Effect with EffectAsync, E, A]`. I ended up abandoning it because cost / benefit ratio didn't feel right, but looks like it may come in handy here...

**Comment by mvv** [comment]
@jdegoes 
Unfortunately, Scala fails to infer `R` when
```scala
def uninterruptible[R >: LowerR, E <: UpperE, A](zio: ZIO[R with UninterruptibleEscape, E, A]): ZIO[R, E, A]
```
is applied to an effect that does not use `interruptible`, e. g.
```
def foo[R, E, A](zio: ZIO[R, E, A]): ZIO[R, E, (A, A)] =
  ZIO.uninterruptible(zio.flatMap(a => zio.map((a, _))))
```
fails with
```
type mismatch;
[error]  found   : scalaz.zio.ZIO[R(in method foo),E,(A, A)]
[error]  required: scalaz.zio.ZIO[R(in method uninterruptible) with scalaz.zio.InsideUninterruptible,E,(A, A)]
[error]     ZIO.uninterruptible(zio.flatMap(a => zio.map((a, _))))

**Comment by jdegoes** [comment]
@mvv You're missing a type bound on R, aren't you?

**Comment by mvv** [comment]
@jdegoes 
Where? `foo` is a valid program (vs `uninterruptible` type signature), it just needs type parameters to be explicitly specified:
```
def foo[R, E, A](zio: ZIO[R, E, A]): ZIO[R, E, (A, A)] =
  ZIO.uninterruptible[R, E, A](zio.flatMap(a => zio.map((a, _))))
```

**Comment by jdegoes** [comment]
@mvv 

We should work on type inference for this.

I clarified the (ongoing) spec above, so that instead of `Option[A]`, it returns `Exit[E, A]`, and am beginning to see how to implement it. Basically by tracking `interrupt` count and by internally using redeem to catch the full cause (modifying the conditions that allow it to do so) The tricky parts are at the boundaries (making sure the runtime stops unwinding the stack at the edge of `interruptible`) and making sure the `interrupt -= 1` occurs in an `ensuring`.

**Comment by mvv** [comment]
@jdegoes 
I still think that the whole `Option`/`Exit` thing is crummy (I personally would not need it 99% of the time). I would much prefer to have two combinators, each doing it's own thing, i.e (forget about `R` for a minute):
```scala
def interruptible(zio: ZIO[R, E, A]): ZIO[R, E, A]
```
only affects interruptibility of `zio` and
```scala
def evaluate(zio: ZIO[R, E, A]): ZIO[R, Nothing, Exit[E, A]]
```
that allows you to "catch" any `Cause` you want. Then, if you _really_ need it, you can use
```scala
evaluate(interruptible(zio)).flatMap {...}
```

**Comment by kaishh** [comment]
@mvv `evaluate` is currently named `.sandbox`

**Comment by mvv** [comment]
@kaishh @jdegoes 
Less work to do ). Regardless of the user-facing type signature, `interruptible` can then be implemented with `Finalizers` only (already done that in #580). I'll try draft a PR this weekend, the `UninterruptibleEscape` and `Exit` stuff can be added on top of it.

**Comment by jdegoes** [comment]
I'm not opposed to having `interruptible` return the same type. It may be a little unexpected for a developer coding in an uninterruptible section to have to deal with interruption, but at least we have it in the type so it will be discoverable.

**Comment by jdegoes** [comment]
@mvv Spec clarified. Better now?

I still think how you want to use this is dangerous. 😉 

In some cases the async operation will acquire the result, but before it has a chance to resume the fiber, the fiber will be interrupted, resulting in a leak of whatever resource it represents. Maybe this is ok in your application. The ultimate solution would be to use `Managed`, which is the only safe way of doing interruptible acquisition (because you get the cleanup action that is always run after the initial allocation). Whether you can use it depends on if you can make some "reserve token" that you can use to do cleanup. Some third-party APIs cannot have such a thing.

Anyway, despite potential for leaks if used improperly, if we do this thing correctly, it will enable use to make simpler versions of bracket and give power users a way out. While still not requiring global reasoning because of the type constraints on `R`.

**Comment by mvv** [comment]
@jdegoes 
Made the PR (#724). Tackled inference for Scala, but not for Dotty. Will add tests tomorrow. Re-implemented `bracket*`, `effectAsyncM` and `raceWith` seem to test fine.
