### ISSUE TITLE
Return types of apply methods

### ISSUE THREAD

**Issue by rnd4222** [scalaz/scalaz-zio#716]
For now, **IO.apply** and **ZIO.apply** returns **Task**.
Wouldn't it be better to return **UIO** here, so it can be used with whatever **E** I want?

**Comment by mschuwalow** [comment]
I think having a **Task** here is a safe default, as this makes the failure recoverable if in doubt.
@jdegoes I would think that it is preferable to use the explicit effect or effectTotal respectively here, is that right?

**Comment by rnd4222** [comment]
Is it an option to add **ZIO.pure** which doesn't use call-by-name argument? Now it's not very clear how to create pure instances of **ZIO[Any, Nothing, A]** (except using **UIO.apply**).

**Comment by mschuwalow** [comment]
I think ZIO.succeed is the canonical solution to this. With ZIO.succeedLazy as the lazy variant

**Comment by rnd4222** [comment]
@mschuwalow OK, makes sense. Thanks, I'm closing the issue.
