### ISSUE TITLE
`Error` typeclass

### ISSUE THREAD

**Issue by ktonga** [scalaz/scalaz-zio#72]
In the same vein as [Haskell's Exception](https://hackage.haskell.org/package/base-4.10.1.0/docs/Control-Exception.html#g:1)

In addition to be just a marker TC it could have functions such as `defaultError` which could be useful to define a meaningful `MonadPlus` for `IO`

**Comment by fommil** [comment]
@emilypi ^^^

**Comment by jdegoes** [comment]
@ktonga Why not `mzero`(Monoid zero) for `MonadPlus`?

**Comment by ktonga** [comment]
That makes it harder to distinguish the `empty` `IO` (from other failed) in `plus` to hold the identity laws. It's not impossible, the implementation will differ from the one in `Plus` and we have to add `Monoid` and `Equal` constrains to `E`. If the default error is a singleton it is simpler and clearer.

**Comment by ktonga** [comment]
Another useful method could be `isRetryable`. I'm not saying we should mark `E` with it everywhere, just add the constraint when it makes sense and we can provide more functionality. For instance there could be two flavors of `maybeRetry` one with the constraint and another accepting an `E => Boolean`

**Comment by fommil** [comment]
(I'll code it up so we can see exactyl what I mean...)

**Comment by fommil** [comment]
https://github.com/scalaz/ioeffect/pull/61

**Comment by ktonga** [comment]
Monoidal `E` it is
