### ISSUE TITLE
Minor renames with deprecated old names

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#739]
For consistency, we should do a few more renames, and mark the old names as deprecated for 1.0 release, giving people an RC or two to update code.

These include the following:

 - `#void` => `#unit`. This matches `either` and `option`, whereas `void` is inherited from Haskell and has a different meaning in Java / Scala. Lots of data types have a void method that needs renaming.
 - `scalaz.zio.blocking.interruptible` should be renamed `scalaz.zio.blocking.effectBlocking` for consistency (all FFI methods start with `effect`).
 - `contramap` => `provideSome`. Actually, I am not sure about this one, but we seem half way there already.

TODO: More incoming.

**Comment by jadireddi** [comment]
I am working on this PR.

**Comment by jadireddi** [comment]
https://github.com/scalaz/scalaz-zio/pull/742

**Comment by jadireddi** [comment]
@jdegoes , Fixed points 1 and 2.

Please do let me know, once we are conformed changing `contramap` => `provideSome` and other `TODO's`

**Comment by jdegoes** [comment]
Here are some other potential renames / deprecations we could make if we wanted:

 - `IO` => `BIO`
 - `TaskR` => `RIO`
 - `Task` => `IO`.

We'd have to think about the latter one as there would be a clash. But we could make the deprecation warning all the same. Maybe using an intermediate type alias.

**Comment by nebtrx** [comment]
Hey @jdegoes I pushed a PR addressing the first two bullet points of your previous comment. 

Could you take a look at it? 

Also, I was thinking about the intermediate type alias for `Task`,  what about `IOTask`?

**PS:**  _Just to be sure about it, the intermediate type alias strategy refers to doing everything in two steps:_

1.

```
IO => BIO (or EIO?)
TaskR => RIO
Task => <Intermediate Type Alias>
```

2. ` <Intermediate Type Alias> => IO`

_Right? Do you have something else in mind?_

**Comment by jdegoes** [comment]
@nebtrx I will close this ticket and open a new one specifically to address the `IO` renames...
