### ISSUE TITLE
IOApp: add shutdown hook to interrupt main fiber

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#74]
`IOApp` can be modified to add a shutdown hook that interrupts the main fiber.

This will allow clean termination of main programs.

```java
Runtime.getRuntime().addShutdownHook(new Thread...)
```

**Comment by alex-thc** [comment]
I'll be happy to help with this. What's the best way to interrupt the main fiber given that it's not forked from any of the fibers? I can perhaps save the FiberContext it's being executed in and call interrupt() on that context in the shutdown hook.

**Comment by jdegoes** [comment]
I think you just fork the user-supplied main `IO` (to get a `Fiber`), and then add a shutdown hook that calls `unsafePerformIO` on `Fiber.interrupt`.

**Comment by jdegoes** [comment]
Fixed in #113
