### ISSUE TITLE
Hide all classes that should be private

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#745]
Several classes are showing up in Scaladoc that are not directly necessary or exposed. Examples include: `ZIOFunctions`, `ZIO_E_Any`, etc., and probably various classes in the `scalaz.zio.internal` package that will never be exposed because they are only used internally by `FiberContext`.

To present clear and useful Scaladoc, all internal classes / traits should be hidden from the user, so that only types intended to be used by end-users appear in the documentation.

This can be done, at least, by making classes / traits private where relevant.

**Comment by GodPlaysChess** [comment]
I would like to take that!

**Comment by jdegoes** [comment]
@GodPlaysChess It's all yours! 🙏
