### ISSUE TITLE
Zip consistency

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#746]
Every data type that has `zip` should also have:

 - `<*` AND `zipLeft`, which perform a `a.zip(b).map(_._1)`. The named operator can delegate to the symbolic operator.
 - `*>` AND `zipRight`, which perform a `a.zip(b).map(_._2)`.  The named operator can delegate to the symbolic operator.
 - `<*>` and `zip`. The named operator can delegate to the symbolic operator.

Every data type that has `zipPar` should also have:

 - `<&` AND `zipParLeft`, which perform a `a.zipPar(b).map(_._1)`. The named operator can delegate to the symbolic operator.
 - `&>` AND `zipParRight`, which perform a `a.zipPar(b).map(_._2)`.  The named operator can delegate to the symbolic operator.
 - `<&>` and `zipPar`. The named operator can delegate to the symbolic operator.

This conventions are already in place (except for the `zipPar` aliases), just not uniformly across all data types.

**Comment by jadireddi** [comment]
@jdegoes , I would like to work on this PR.

**Comment by jdegoes** [comment]
@jadireddi Going to close this, I think / hope we got everything. 😄

**Comment by jadireddi** [comment]
Sure @jdegoes. We can close it. We have got everything.
