### ISSUE TITLE
Fix equals and hashCode for Exit.Cause

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#747]
The `Exit.Cause` structure inside `core` (`Exit.scala`) is a _free semiring_, without multiplicative or additive identity.

In particular, for sequential composition `++` (currently called `Then`) and parallel composition `&&` (currently called `Both`), we have:

 - Associativity of sequential: `a ++ (b ++ c) == (a ++ b) ++ c`
 - Associativity of parallel: `a && (b && c) == (a && b) && c`
 - Commutativity of parallel: `a && b == b && a`
 - Distributivity of sequential: `a ++ (b && c) == (a ++ b) && (a ++ c)` (right)
 - Distributivity of sequential: `(b && c) ++ a == (b ++ a) && (c ++ a)` (left)

Unfortunately, the `equals` and `hashCode` do not respect these. 

This ticket is to fix `equals` and `hashCode` on `Cause` and to add tests to verify these equalities are respected (either with ScalaCheck, or on a few interesting cases).

**Comment by Cereopsis** [comment]
@jdegoes Looks like this is down to how flatten works. Taking right sequential distribution as an example:

```a ++ (b && c) must_===((a ++ b) && (a ++ c))```

```
def flatten(c: Cause[_]) = c match {
    case t@Then(_,_) => t.flatten
    case b@Both(_,_) => b.flatten
    case i@Interrupt   => Set(i)
 }

flatten(Interrupt ++ (Interrupt && Interrupt))
// Set(Interrupt, Both(Interrupt, Interrupt))

flatten((Interrupt ++ Interrupt) && (Interrupt ++ Interrupt))
// Set(Then(Interrupt, Interrupt))
```

Obviously Set's hashCode is going to arrive at two distinct values in this case making any equality comparison fail. I guess the question is whether a more thorough flattening operation is the answer e.g

```
def flatten(c: Cause[_]): Set[Cause[_]] = c match {
  case Then(a,b) => flatten(a) ++ flatten(b)
  case Both(a,b) => flatten(a) ++ flatten(b)
  case other     => Set(other)
}
```

**Comment by Cereopsis** [comment]
Interesting. Lifting flatten (as defined above), hashCode and equals up into the trait works for all the equalities defined in this issue BUT breaks the single existing test case which exercises stripFailures.

I'll have to poke around a bit more to see why that is.

**Comment by Cereopsis** [comment]
OK, so somehow that broke the pattern match in stripFailures. The case `if (c.died) c.stripFailures must beSome` was failing with input `Die(java.lang.RuntimeException)`

Turns out  the first case `case Interrupt => None` was matching and by moving `case d @ Die(_) => Some(d)` to the top it worked.

Next step, try to work out the logic behind that!

**Comment by Cereopsis** [comment]
One other fly in the ointment: IOSpec.testOrElseDefectHandling fails.

**Comment by jdegoes** [comment]
@Cereopsis Right now the use of set for sequence means that `a ++ b` compares equal to `b ++ a`. But that's incorrect. The first one says the error `a` came _before_ the error `b`, but the latter says the reverse. They say opposite things and should not be equal.

**Comment by Cereopsis** [comment]
@jdegoes Yes, it felt far too simplistic/naive :-)  I just need to grok some simple patterns to see how to make the right comparisons.

**Comment by msosnicki** [comment]
@jdegoes can I have a look into this one? I changed the implementation and created ScalaCheck tests for it, but at the moment all the tests but left distributivity pass and I will gladly dig it deeper :)

**Comment by Cereopsis** [comment]
No arguments here, I probably won’t get round to looking til next week now anyway
