### ISSUE TITLE
Environments compatibility

### ISSUE THREAD

**Issue by tampler** [scalaz/scalaz-zio#761]
Hello

I'm trying to test the env feature with my code, but have a hard time integrating it. Could you pls help me to resolve the issue below ?
```scala
object Env extends App {

  case class Config(server: String, port: Int)
  // Exec Effects
  val runtime = new DefaultRuntime {}  

  def run(args: List[String]): ZIO[Environment, Nothing, Int] = 
    test.fold(_ => 1, _ => 0)

 val test: ZIO[Config, Nothing, String] = 

  for {
    server <- ZIO.access[Config](_.server)
    port   <- ZIO.access[Config](_.port)
  } yield s"Server: $server, port: $port"
}
```
```bash
[error] /home/bku/work/scala/scala_katas/src/main/scala/zio/Env.scala:15:14: type mismatch;
[error]  found   : scalaz.zio.ZIO[ZIOIntro.Env.Config,Nothing,Int]
[error]  required: scalaz.zio.ZIO[ZIOIntro.Env.Environment,Nothing,Int]
```
How do I repack ZIO[Config, Nothing,Int] into ZIO[Environment, Nothing, Int] ?

Thank you!
Boris

**Comment by ksarath** [comment]
Can't we use `provideSome(_ => Config)` for this case?

**Comment by jdegoes** [comment]
`test.provide(Config(...)).fold(_ => 1, _ => 0)`

**Comment by jdegoes** [comment]
Also you don't need `DefaultRuntime` because `App` already contains a runtime...

**Comment by tampler** [comment]
@jdegoes Thanks, worked like a charm. 

I plan to attend the Lambda Conf 2019. I'd also like to contribute into Zio. Should I join some group in  https://scalaz.mobilize.io to do that ?

**Comment by jdegoes** [comment]
@tampler No need for that! Just stick around here to contribute. 😄 

Look forward to meeting you at LC2019, and welcome contributions. 🎉
