### ISSUE TITLE
RefM should permit errors in modify etc

### ISSUE THREAD

**Issue by TimPigden** [scalaz/scalaz-zio#771]
Currently the signature for RefM.modify is
```final def modify[R, B](f: A => ZIO[R, Nothing, (B, A)]): ZIO[R, Nothing, B] =```
This is restrictive, in that the method f might reasonably return an error. Something like
```final def modify[R, E, B](f: A => ZIO[R, E, (B, A)]): ZIO[R, E, B] =```
would be more useful

**Comment by GodPlaysChess** [comment]
I will take this!
