### ISSUE TITLE
Granular interruption levels

### ISSUE THREAD

**Issue by mvv** [scalaz/scalaz-zio#776]
I was about to write a patch that prevents `ZQueue.take` from "losing" dequeued items on interruption, but immediately got reminded of the idea to make all potentially blocking operations in ZIO to use `interruptible` to prevent deadlocks, unfortunately, at the expense of modularity.

That got me thinking that, if we are essentially copying the Haskell approach, when why not copy it in full detail. Haskell has three levels of interruptibility instead of ZIO's two:

1. `Unmasked` (that's our `interruptible`) - both memory allocations and blocking operations are interruptible.
2. `MaskedInterruptible` (this we are trying to emulate by forcing interruptiblity of certain operations) - memory allocations are not interruptible, but blocking operations are.
3. `MaskedUninterruptible` (that's our `uinterruptible`) - both memory allocations and blocking operations are uninterruptible.

So, if we also introduce the third level, we would regain modularity and keep the concept of blocking operations at the same time (names pending):

1. `Interruptible` - both flatMaps and blocking operations are interruptible.
2. `NonBlockingUninterruptible` (that's what `uninterruptible` and `uninterruptibleMask` do) - flatMaps are not interruptible, but blocking operations are.
3. `BlockingUninterruptible` - both flatMaps and blocking operations are uninterruptible.

For example
```scala
Promise {
  def await: IO[E, A] = IO.blockingOperation { ... }
}
```

Here `IO.blockingOperation` keeps `Interruptible` and `BlockingUninterruptible` states, but changes `NonBlockingUninterruptible` to `Interruptible` for its body. This way we can

1. Have `Promise.await` to be interruptible inside `uninterruptible` and `uninterruptibleMask`.
2. Have combinators like `blockingUninterruptible` and `blockingUninterruptibleMask`, that would allow running blocking operations without interruptions (in cases when you know that they won't really block from the context, or you just happen to really need that, e.g. a blocking operation inside `bracket`'s `release`).

@jdegoes What do you think?

**Comment by jdegoes** [comment]
@mvv I will think on this, but my current thought is that I would rather leave core operations with _undefined_ interruptibility, and let the user choose, than introduce a 3rd mode.

A tri-state interruptibility model is very hard to explain and understand, lacks symmetry, and will not support the same sort of laws that we can define with the current model.

If we don't choose the interruptibility status for anything in ZIO, then it will be up to the user to choose, via `interruptible` or `uninterruptible`. ZIO itself can remain unopinionated on that matter.

Would that work for you?

**Comment by mvv** [comment]
Sure. It is fine for application-level code, just hope nobody starts using `interruptible` directly in libraries.

**Comment by jdegoes** [comment]
@mvv Right.

I think the safest way to deal with untrusted code is to `run` it from within your `uninterruptible` block. Because after all, even if it is not interruptible / interrupted, it can still be defective (throwing errors), which will be detrimental to resource safety. 

It adds a little more boilerplate but it helps make it bulletproof to untrusted code.
