### ISSUE TITLE
Add more context to the default Platform#reportFailure

### ISSUE THREAD

**Issue by iravid** [scalaz/scalaz-zio#778]
Currently, it just prints the `cause.toString`. We could add some more context (e.g. `"An unhandled failure occured:"`) and maybe assist the user in checking what went wrong. 

(I'd love to know myself what to do to get rid of these! cc @jdegoes )

**Comment by jdegoes** [comment]
I think recently the Cause has been imlroved to show stack trace...if not, we should add that. The message printed should be enough to diagnose the problem.

Also I changed to print to std err by default.

**Comment by iravid** [comment]
When exactly does this get called? On all defects? Would be good to have that printed as well

**Comment by jdegoes** [comment]
It will be called on all unhandled typed errors, and all defects.
