### ISSUE TITLE
Implement cats-effect `ConcurrentEffect` instance for `IO`

### ISSUE THREAD

**Issue by ktonga** [scalaz/scalaz-zio#79]

**Comment by jdegoes** [comment]
I think this depends on #81

**Comment by ktonga** [comment]
Nope, it is already in [0.10.1](https://github.com/typelevel/cats-effect/blob/v0.10.1/core/shared/src/main/scala/cats/effect/ConcurrentEffect.scala)

**Comment by ktonga** [comment]
I have it mid implemented already but I have to fix a bug in `runAsync` first

**Comment by jdegoes** [comment]
I mean the laws were improved and ZIO has no chance to pass the old ones

**Comment by ktonga** [comment]
Dunno, we're passing the old laws for `Effect`. You saying for `Concurrent` it's somehow different? We've got other finalization and cancellation semantics. Haven't we?

**Comment by jmcardon** [comment]
Yes. We didn't pass concurrent laws which prompted a super long discussion.

**Comment by ghostdogpr** [comment]
Closed by #446
