### ISSUE TITLE
Proper attribution for STM

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#794]
The design of the API for STM was lifted directly from Haskell and is due proper attribution (the implementation is original and does not resemble the Haskell implementation at all).

**Comment by jdegoes** [comment]
Should look at other things too and provide proper attribution.

**Comment by justinhj** [comment]
I'd be interested in doing this. Two questions though: Where will the documentation go, inline in the code or on the microsite or both? How much detail do you think I should put? I'm thinking it is enough for a brief summary of where it came from a link?

**Comment by justinhj** [comment]
I've made a first pass at this
