### ISSUE TITLE
Timing IO

### ISSUE THREAD

**Issue by NeQuissimus** [scalaz/scalaz-zio#801]
I would like to time the execution of (parts of) my IO.

This work but I was wondering if folks out there have a better idea :)

I would give this an "Ops" class, so one could just do `io.timed(reporter)`

```scala
import java.util.concurrent.TimeUnit
import scalaz.zio._
import scalaz.zio.clock.Clock
import scalaz.zio.duration._

  def timed[R <: Clock, E, A](zio: ZIO[R, E, A], reporter: Duration => ZIO[R, Nothing, _]): ZIO[R, E, A] = zio.flatMap { a: A =>
    clock.currentTime(TimeUnit.NANOSECONDS).bracket(startTime => clock.currentTime(TimeUnit.NANOSECONDS).flatMap(endTime => reporter(Duration.fromNanos(endTime - startTime))))
      { _ =>
      ZIO.succeed(a)
      }
  }
```

**Comment by ghostdogpr** [comment]
Just to be sure: are you aware of the existing `timed`, `timedWith` and `summarized` operators?

**Comment by NeQuissimus** [comment]
Lol, apparently not... I'll check them out :+1:

**Comment by ghostdogpr** [comment]
Will add `timed` to my [ZIO Cheat Sheet](https://github.com/ghostdogpr/zio-cheatsheet) ;)

**Comment by NeQuissimus** [comment]
They do what I need, thanks! I'm in the process of updating from 0.6.x.never encountered these guys before...
My implementation chains nicer though 😜
