### ISSUE TITLE
Fibers debug in Chisel

### ISSUE THREAD

**Issue by tampler** [scalaz/scalaz-zio#821]
Hello

I'm trying to integrate ZIO into a [circuit simulator](https://github.com/freechipsproject/chisel-testers) to support parallel hardware simulations in [Chisel](https://github.com/freechipsproject/chisel3).

I define some function inside my test class:
```scala
driveInputs (size:Int, channel:String):Unit 
```
and call it twice for upper and lower channels . This works fine, but sequentially, see below
![sequential](https://user-images.githubusercontent.com/2816743/57178189-88fcab00-6e75-11e9-860b-3224ebde04a1.png)
I then define a parallel block like this:
```scala
  val res = for {
    f0  <- IO.fail(driveInputs (xlen, "a")).fork
    f1  <- IO.succeed(driveInputs (ylen, "b")).fork  

    //_ <- f0.join
    //_ <- f1.join
    fib  = f0 zip f1
    _ <- fib.join  
  } yield(fib)
```
and get an interruption after the first defined method is joined, whatever I do:
![fibers](https://user-images.githubusercontent.com/2816743/57178219-e09b1680-6e75-11e9-8012-90d4d2e098a8.png)
The only way to see any activity on the bottom channel is to comment everything related to the upper channel and thus fiber f0.

Here's my top level method:
```scala
object GridMain extends App {

  val runtime = new DefaultRuntime {}

  def run(args: List[String]) =
    appmain.fold(_ => 1, _ => 0)
  val appmain = IO.succeed(iotesters.Driver.execute ( Array[String](""), () => new GridShell){
    c => new GridUnitTest(c)} )
  //val top  = runtime.unsafeRun(appmain)  
}
```
Any ideas? How do I debug this?

Thanks,
Boris

**Comment by iravid** [comment]
If `driveInputs` contains side-effects, you must use `Task(...)` to delay them. Otherwise, It will be evaluated on the calling thread. Moreover, `IO.succeed(driveInputs).fork` will not actually perform any computations on a separate fiber as `driveInputs` would have already been evaluated.

**Comment by tampler** [comment]
Hi @iravid . Thanks for your advice, but that didn't work for me. I did the following:
```scala
val t0:Task[Unit]  = ZIO.effect(driveInputs (xlen, "a"))
val t1:Task[Unit]  = ZIO.effect(driveInputs (ylen, "b"))
...
  val res = for {
    f0  <- t0.fork
    f1  <- t1.fork  

    //r0 <- f0.join
    //r1 <- f1.join
    fib  = f0 zip f1
    //_ <- fib.join  
  } yield(fib)
```
The code above results in a ZERO output on my waveform. Seem like tasks were never launched.
If I try with the runtime, it works sequentially, as with the linear code:
```scala
  val runtime = new DefaultRuntime {}
  val t0:Task[Unit]  = ZIO.effect(driveInputs (xlen, "a"))
  val t1:Task[Unit]  = ZIO.effect(driveInputs (ylen, "b"))  

  runtime.unsafeRun(t0)
  runtime.unsafeRun(t1)
```
Anything else to try ?

Boris

**Comment by iravid** [comment]
did you `runtime.unsafeRun(res)`?

**Comment by tampler** [comment]
@iravid Yes, my bad. Forgot about running it :). Now, results are interesting and require more thought.
Here's my code:
```scala
  val runtime = new DefaultRuntime {}
  val t0:Task[Unit]  = ZIO.effect(driveInputs (xlen, "a"))
  val t1:Task[Unit]  = ZIO.effect(driveInputs (ylen, "b"))
  
  // Run seqeuntially
  runtime.unsafeRun(t0)
  runtime.unsafeRun(t1)

  def runpar0 () = {
    val res = for {
      f0  <- t0.fork
      f1  <- t1.fork
      r0  <- f0.join
      r1  <- f1.join  
    } yield(r0,r1)
    runtime.unsafeRun(res)
  }
  
  def runpar1 () = {
    val res = for {
      f0  <- t0.fork
      f1  <- t1.fork
      fib  = f0 zip f1
      r <- fib.join  
    } yield(r)
    runtime.unsafeRun(res)
  }
  step (5)
  runpar0()
  step (5)
  runpar1()
```
![res0](https://user-images.githubusercontent.com/2816743/57182296-266fd300-6ea6-11e9-803d-e1f988513fac.png)
As we see, runpar0() yields in a mess, where control signal length is random. 
runpar1() outputs the same result, as for sequential compute.

What I expect to see is **a nice overlap**, as below:
![exp](https://user-images.githubusercontent.com/2816743/57182385-07257580-6ea7-11e9-8e17-276bad483039.png)


Any more thoughts ?

**Comment by 7robertodantas** [comment]
@tampler you seem to be misusing / misunderstanding the usage of runtime and IO effect. Ideally the `runtime.unsafeRun` should be called at the edges / end of your program. Its execution is done synchronously, that's possibly why it's not overlapping as you expect (though I do not understand how this circuit thing that you're showing works).

Try to refactor your code to compose these `par0` and `par1` into one for comprehension, fork them, and then finally run this last one into the `unsafeRun`, doing that it might work as you expect to.

Something like:

```scala
val t0:Task[Unit]  = ZIO.effect(driveInputs (xlen, "a"))
val t1:Task[Unit]  = ZIO.effect(driveInputs (ylen, "b"))

val par0: Task[Unit] = ???
val par1: Task[Unit] = ???

val combine = for{
  _ <- par0.fork
  _ <- par1.fork
} yield ()

runtime.unsafeRun(combine)
```

**Comment by tampler** [comment]
@7robertodantas thank you for suggestion, still no cigar. I believe, joining threads is necessary to ensure a valid sync. See results below
```scala
  val t0:Task[Unit]  = ZIO.effect(driveInputs (xlen, "a"))
  val t1:Task[Unit]  = ZIO.effect(driveInputs (ylen, "b"))

  def runpar0 () = {
    val res = for {
      f0  <- t0.fork
      f1  <- t1.fork
      //r0  <- f0.join
      //r1  <- f1.join
    } yield()
    runtime.unsafeRun(res)
  }  
  
  def runpar1 () = {
    val res  = t0 <&> t1    
    runtime.unsafeRun(res)
  }

sequential ()
runpar0()
runpar1()
```
![res1](https://user-images.githubusercontent.com/2816743/57190525-c455b300-6f23-11e9-9079-13e960992ca3.png)

Other thoughts ?

Boris

**Comment by tampler** [comment]
After experimenting for a while with ZIO fibers, I came up with some conclusions. See the pic below to start with

![res2](https://user-images.githubusercontent.com/2816743/57192860-e78d5c00-6f3d-11e9-9d92-90b515aad07b.png)

I slightly refactored my code and let each function to actually return before executing the end-of-the-world. 

I can't upload my code, since that's a commercial project and most of you won't mess with extra dependencies and set up. 

But the generic principle is simple: I wanna run multiple fibers from a single-threaded Scala app. Here's my code:
```scala
  def driveA () = {

    for {
      i <- 0 until xlen
      j <- 0 until ylen
      } yield {
        poke (uut.adin(0).valid, 1)
        poke (uut.adin(0).bits.data, A.get(i,j).toInt)
        step(1)
    }
    poke (uut.adin(0).valid, 0)
    poke (uut.adin(0).bits.data, 0)
    
  }

  def driveB () = {

    for {
      i <- 0 until xlen
      j <- 0 until ylen
      } yield {
        poke (uut.adin(1).valid, 1)
        poke (uut.adin(1).bits.data, B.get(i,j).toInt)
        step(1)
    }
    poke (uut.adin(1).valid, 0)
    poke (uut.adin(1).bits.data, 0)
    
  }

  val runtime = new DefaultRuntime {}

  val t0:Task[Unit]  = ZIO.effect(driveA ())
  val t1:Task[Unit]  = ZIO.effect(driveB ())
  
  runtime.unsafeRun(t0)
  runtime.unsafeRun(t1)

  def runpar0 () = {

    val res = for {

      f0  <- t0.fork
      f1  <- t1.fork

      r0  <- f0.join
      r1  <- f1.join
  
    //} yield(f0.join, f1.join)
    } yield()
  
    res
  }
  
  def runpar1 () = {

    val res = for {

      f0  <- t0.fork
      f1  <- t1.fork

      fib  = f0 zip f1
      r <- fib.join
  
    } yield(r)

    res
  }
  
  def runpar2 () = {
    val res  = t0 race t1 
    res
  }

  step (5)
  runtime.unsafeRun(runpar0())
  
  step (5)
  runtime.unsafeRun(runpar1())
  
  step (5)
  runtime.unsafeRun(runpar2())
```

If you check the picture, you'll see that the [simulator](https://github.com/freechipsproject/chisel-testers) indeed spawns two threads, but their synchronization is under the question.

The 2-nd beat shows that fiber sync can break the app logic, spreading computation over more than 4 cycles. The 3-d beat shows that fibers may be scheduled out-of-order, but both **ZIO par** and **ZIO race** methods schedule an eager execution, spawning the 2-nd fiber only after the first has returned.

Correct me if I'm wrong. I don't understand how to explain this scheduling behavior and looking for a help from ZIO community

Thank you,
Boris

**Comment by kaishh** [comment]
You can control the behavior of forking by swapping the underlying `Executor` in the runtime. e.g. to pin every fiber to a separate thread you can create a `cachedThreadPool` with unlimited threads and set `yieldOpCount` in runtime to `Long.MaxValue`

**Comment by iravid** [comment]
Feel free to continue this conversation in the Gitter chatroom - closing this out for now.

**Comment by tampler** [comment]
Hey @iravid 
I didn't grant you a permission to close my issues, since they are not yet solved.
I'm trying to innovate and solve a real world business problem with ZIO and need a community support. Your solution didn't work. So pls provide a better solution, if you can, or let other and smarter people to solve this issue and build new apps upon ZIO.

If you can't, reopen this issue and don't touch my tickets anymore, just because you can

Thank you,
Boris von Vladimirovich
