### ISSUE TITLE
Cats Interop for ZManaged

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#826]
`ZManaged` is a different take on Cats `Resource`, which provides additional capabilities, including:

 - A final encoding (no intermediate representation necessary)
 - Safely interruptible acquisition, which composes
 - Parallel composition

In order to enhance interop with the Cats Effect ecosystem, we need to add helper functions inside the cats interop module, which are capable of performing conversion:

 - `toResource` on `ZManaged.type`, which converts a `ZManaged` into a `Resource`. Note that this conversion is "lossy", because there is no way to represent interruptible acquisition with `Resource`
 - `toManaged` on `Resource.type`, which converts a `Resource` into a `ZManaged`. This can be done safely and without loss of any properties of the original `Resource`.

To add these methods onto existing types, we can use extension methods, e.g.:

```scala
implicit class ResourceSyntax[F[_], A](resource: Resource[F, A]) {
  def toManaged: ZManaged[Any, Throwable, A] = ???
}

implicit class ZManagedSyntax[R, A](managed: ZManaged[R, Throwable, A]) {
  def toResource: Resource[ZManaged[R, Throwable, ?], A] = ???
```

These can be placed in the cats interop package, so a single import can bring them into scope. Note that to convert as specified, we may require Cats Effect type class instances, which have been omitted from the above examples (which also probably do not compile :smile:!).

When this ticket is done, it will be possible to convert from `ZManaged` (or `Managed`) to `Resource`, and from `Resource` to `ZManaged`, albeit only one of those directions will be "lossless", in the sense of retaining all properties of the original.

**Comment by mschuwalow** [comment]
I have begun adding instances here: https://github.com/scalaz/scalaz-zio/pull/827
About the conversion methods:

I think we would need natural transformations between F and ZIO to go between these two types.
I don't think we can do better here than https://github.com/typelevel/cats-effect/blob/master/core/shared/src/main/scala/cats/effect/Resource.scala#L151-L163
