### ISSUE TITLE
ZManaged API discussion: retry

### ISSUE THREAD

**Issue by mschuwalow** [scalaz/scalaz-zio#847]
As discussed here https://github.com/scalaz/scalaz-zio/pull/839 it would be cool to introduce aretry method to ZManaged. The problem is that it is not quite clear how the semantics should be here. I see 4 different options:

1. Retry reservation
2. Retry acquisition
3. Retry both separately (this could be surprising as it might lead to twice the number of retries in some cases)
4. Retry both while threading state between the schedules

This issue is just for determining how the semantics should be. I'll gladly take care of implementing.

**Comment by regiskuckaertz** [comment]
I think option 4 makes sense if I understand correctly
```
ZManaged#retry(n) ≅ reserve.retry(m) *> acquire.retry(n - m) where 0 < m <= n?
```
?

**Comment by mschuwalow** [comment]
Yeah exactly. I agree that this makes the most sense
