### ISSUE TITLE
Feature Request: Local Variable Propogation Mechanism

### ISSUE THREAD

**Issue by mdedetrich** [scalaz/scalaz-zio#850]
I have been eying out ZIO to use at our work as a possible replacement of Monix Task however there is one feature that is missing that is currently putting a dampener on us and its the absence of a `ThreadLocal` like mechanism, i.e. the equivalent of Monix's `TaskLocal`, see the following for more information

* https://medium.com/pragmatic-scala/local-variable-propagation-with-monix-part-1-106b80e652bb
* https://olegpy.com/better-logging-monix-1/

While the feature may seem a bit "anti functional" (and the using it for something like logging as questionable) there is one area in use (for us) where its better than any alternative which comes down to tracing (i.e. https://opentracing.io/). We have attempted to use the functional solutions of opentracing before and we have found that it caused huge amounts of friction (a more detailed explanation can be seen here https://github.com/mdedetrich/monix-opentracing#design).

In terms of design space, I would design it similarly to how Monix Task works i.e.

* The feature is entirely optional with default turned off (since it has a performance hit)
* There is a purely functional variant (which Monix calls `TaskLocal`)
* Side effect variant (which acts as a supertpe of `ThreadLocal` but with better scoping to work with lazy effects). Note that this is a nice to have for people implementing a solution using local variable propagation but users are never expected to use this unless they have to interopt with Java/side effect land

For an example of the problems that local variable propagation is meant to solve, have a look at

* https://github.com/mdedetrich/monix-opentracing
* https://github.com/mdedetrich/monix-mdc/

I understand this is a contentious issue, there is also a question of how we should scope such a thing (i.e. we are currently having issues of how we should think that `Future` interopt of local variable propagation should work) but I would like to get an idea if such a concept is welcome in ZIO (if so I would try and spend some time implementing it myself, as a basis it would be an extension ontop of ZIO's fiber).

**Comment by mdedetrich** [comment]
Closing, just saw https://scalaz.github.io/scalaz-zio/datatypes/fiberlocal.html

**Comment by iravid** [comment]
There's also #618, which would further enhance `FiberLocal` and add inheritance of locals when fibers are forked. There's some WIP work at #665.
