### ISSUE TITLE
Motivation for Void

### ISSUE THREAD

**Issue by alexknvl** [scalaz/scalaz-zio#89]
I believe we made a mistake by introducing `Void` as a newtype. Could someone provide some motivation for it?

### Name clash with java.lang.Void

It is really annoying.

### Dead code warnings
Dead code warnings are not real warnings in pure code. The only case where they make sense is if you "accidentally" create a "value" of type `Nothing`, e.g.
```scala
def foo: Unit = {
  doStuff
  val x = throw new Foo // A "value" of type Nothing
  doMoreStuff(x) // Dead code
}
```

It does not make any sense in pure code, because the only way we can obtain a value of type `Nothing` is if someone gives it to us:
```scala
def thisWillNeverRun(v: Nothing): Int = {
  (v : List[List[Int]]).head.head
}
```
this code is indeed dead, but how is it a useful warning? What should we be worried about? That we *accidentally* put `Nothing` as an argument?

### Resolution issues
The original motivation for `Void` (at least in `leibniz`) was to work around the implicit resolution bugs, that apparently existed back in the day. There is no indication that they still exist in 2.12.6 (I asked around and no one knew any examples), and regardless of that,
```scala
type Bottom <: Nothing
```
would work equally well w.r.t. implicit resolution.

### Scalaz depending on ZIO for Void

It's not a problem, but it is confusing IMHO.

**Comment by jdegoes** [comment]
@alexknvl All dead code warnings are fatal errors in the build. In general, eliminating `Void` from any sum type will lead to a dead code fatal error (or at least warning). How do we fix this?

**Comment by alexknvl** [comment]
Just remove the flag `-Ywarn-dead-code`.

**Comment by jmcardon** [comment]
@jdegoes dead code warnings are really shitty in scala. I propose removing the flag altogether,  honestly.

**Comment by jdegoes** [comment]
@alexknvl @jmcardon My main concern is not `ZIO`, but third-party libraries that depend on ZIO. Basically we're saying they can't compile user-land code that uses ZIO without removing the flag.

I'm not necessarily opposed to that, just worth thinking through first.

**Comment by jdegoes** [comment]
All right, let's do it!

**Comment by issackurian** [comment]
I'd like to help with this - does this just need `-Ywarn-dead-code` to be removed from `project/ScalazBuild.scala`

**Comment by ktonga** [comment]
@issackurian no, the idea is to rollback #45 and remove that flag which seems to be the only motivation to introduce `Void` in first place

**Comment by issackurian** [comment]
Ah ok, thanks for explaining.

**Comment by jdegoes** [comment]
Subsumed by #118
