### ISSUE TITLE
Flaky ZManaged tests

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#899]
Lots of the new ZManaged tests use sleeps without latches, resulting in much slower running tests, and test flakiness that needs to be fixed.

/cc @mschuwalow 

```
[error]     x Runs finalizers if returning None and reservation is successful
[error]  Falsified after 0 passed tests.
[error]  
[error]  The seed is uTcnQQ0M6JZHVu6qULMbE1ex6WCEZCGVUYXYyTYJsqD=
[error]  
[error]  > 0 != 1 (ZManagedSpec.scala:375)
```

**Comment by mschuwalow** [comment]
I'll try to get this fixed this weekend. Sorry 🙏

**Comment by jdegoes** [comment]
I think I got it. But would be nice to delete or eliminate all the other sleep tests...
