### ISSUE TITLE
Question on behavior

### ISSUE THREAD

**Issue by alexandru** [scalaz/scalaz-zio#90]
Hi all,

In order to ensure that Cats-Effect 1.0.0 supports ZIO and Monix's Task auto-cancelable behavior, I may have discovered a problem with an assumption about `start` (`fork`) that I need to verify with you.

In this piece of code, is the specified `release` guaranteed to run?

```scala
val task = IO(1).bracket(release)(use)

task.fork.flatMap(f => f.cancel *> f.join)
```

The answer is probably *no*, but want to double check with you.

Thanks,

**Comment by alexandru** [comment]
Never mind, found out the answer, closing.

**Comment by jdegoes** [comment]
@alexandru The release is only guaranteed to run if `IO(1)` completes successfully. However, it may not complete at all (due to error or defect), or it may not be started (due to interruption).

**Comment by alexandru** [comment]
Thanks @jdegoes, yes, that’s what I thought, wanted to double check.

**Comment by jdegoes** [comment]
@alexandru Happy to help, let me know if you need a review or any help on the cats-effect changes.
