### ISSUE TITLE
Both fiber join and interrupt should themselves be losslessly interruptible

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#93]
Interrupting fiber join or fiber interrupt should not leak resources.

```scala
fiber.interrupt.fork(_.interrupt)
fiber.join.fork(_.interrupt)
```

This requires modifying the implementation of `join` and `interrupt` to return `Async.maybeLater` values, with cancelers that do the right thing when invoked.

**Comment by regiskuckaertz** [comment]
Is this still happening, I don't think so?

**Comment by jdegoes** [comment]
I would be surprised if you can (actually) interrupt a join or interrupt. That requires cancelation logic to remove the listeners, which AFAIK doesn’t exist yet. The current code should do the right thing but leak listeners (observers).

**Comment by jdegoes** [comment]
This will add overhead for a fringe use case. Will close.
