### ISSUE TITLE
Create IOQueue.bounded, IOQueue.unbounded

### ISSUE THREAD

**Issue by jdegoes** [scalaz/scalaz-zio#98]
The documentation should state that bounded queues do not lose elements when they reach maximum capacity—rather, they suspend new `offer`s.

The `unbounded` implementation can simply create a bounded queue with `Int.MaxValue`. Because there is no pre-allocation, this should work fine.

/cc @adamw

**Comment by regiskuckaertz** [comment]
What about `IOQueue.dropping` (dropping new elements when full) and `IOQueue.sliding` (dropping old elements when full)?

**Comment by jdegoes** [comment]
@regiskuckaertz Sounds good to me. 👍 

The design of `offer` will have to be thought through for `dropping` and `sliding`—I suppose it means that `offer` never suspends and always returns right away.
